/**
 * NEXUS ECHO — evidence art library, CASE NX-037.
 *
 * One authored dataset drives the generated images, the manifest, and the
 * development showcase catalog. Every record shares the same universe: the same
 * building, the same night, the same cameras, the same personnel, the same
 * identifiers. That shared fiction is what makes the archive investigable —
 * a player who notices CAM-07 in a surveillance frame, then CAM-07 on a torn
 * maintenance label, then CAM-07 in a photograph's metadata is doing the work
 * the game intends, without being told to.
 */

export const CASE = {
  id: 'NX-037',
  title: 'EAST CORRIDOR',
  institution: 'HALDER INSTITUTE FOR CONTINUITY STUDIES',
  bureau: 'BUREAU OF CONTINUITY RECORDS',
  node: 'B-04',
  terminal: '07',
  build: 'NX-4.17',
  site: 'HALDER INSTITUTE — ADMIN BUILDING (1974) — EAST WING',
  officer: 'OBSERVATION / A. REHAL',
  incidentNight: '14 OCT 94',
  keyTime: '03:17:11',
  anomalousTime: '17 APR 98',
  locationCode: 'LOC-C214',
}

/** Minimum coverage the brief requires the generated set to satisfy. */
CASE.requirements = {
  PHOTOGRAPH: 10,
  SURVEILLANCE: 8,
  DOCUMENT: 8,
  FRAGMENT: 8,
  MAP: 4,
  PERSONNEL: 4,
  NOTE: 8,
  AUDIO: 5,
}
CASE.damagedMinimum = 5

export const PERSONNEL_ROSTER = {
  'L.V.-0029': { name: 'VEY, LINA MARGARET', role: 'PROJECT LEAD / MEMORY RESEARCH', grade: 'RESEARCH GRADE 4', unit: 'MEMORY RESEARCH', access: 'LEVEL 3 — LAB 04', appointed: '14 SEP 1981', dob: '11 JUN 1954' },
  'M.C.-0114': { name: 'CARTER, MARCUS A.', role: 'DEPUTY LEAD / SYSTEM THEORY', grade: 'RESEARCH GRADE 3', unit: 'SYSTEM THEORY', access: 'LEVEL 3 — LAB 02', appointed: '02 FEB 1986', dob: '30 APR 1949' },
  'N.R.-0471': { name: 'RAHAL, NOOR', role: 'FIELD OBSERVATION', grade: 'OFFICER GRADE 2', unit: 'SECURITY / OBSERVATION', access: 'ALL EXTERIOR — CAM READ', appointed: '19 MAY 1992', dob: '04 SEP 1968' },
  'M.S.-0388': { name: 'SELIM, MARA', role: 'ARCHIVIST', grade: 'ADMIN GRADE 3', unit: 'CENTRAL ARCHIVE', access: 'LEVEL 1 — ARCHIVE', appointed: '08 JAN 1989', dob: '22 NOV 1961' },
  'TECH-11': { name: 'FACILITIES / TECHNICIAN 11', role: 'MAINTENANCE', grade: 'TRADE GRADE 2', unit: 'FACILITIES ENGINEERING', access: 'PLANT ROOM + ALL WINGS', appointed: '11 MAR 1979', dob: '03 JUL 1957' },
}

export const LOCATION_CODES = {
  C214: 'LOC-C214 / EAST CORRIDOR',
  C101: 'LOC-C101 / CENTRAL ARCHIVE',
  C118: 'LOC-C118 / STAIRWELL 1',
  C202: 'LOC-C202 / SCIENCE WING LAB',
  C305: 'LOC-C305 / EQUIPMENT ROOM',
  C001: 'LOC-C001 / MAIN ENTRANCE',
  SUB: 'LOC-S01 / SUB-BASEMENT PLANT',
  C214B: 'LOC-C214 / EAST CORRIDOR (NORTH)',
}

/* ───────────────────────────── photographs ───────────────────────────── */

export const PHOTOGRAPHS = [
  {
    asset: 'photo_nx037_b_01',
    code: 'NX-037-B-01',
    title: 'East Corridor, North Approach',
    description: 'Handheld frame taken from the archive doorway. The corridor is empty. The second fixture is out.',
    type: 'PHOTOGRAPH',
    condition: 'NORMAL',
    state: 'UNREVIEWED',
    location: LOCATION_CODES.C214,
    device: 'FIELD-CAM-02',
    capturedAt: '14 OCT 94 03:12:44',
    acquiredAt: '14 OCT 94 03:48',
    integrity: 'VERIFIED',
    source: 'OBS-02 FIELD RECOVERY',
    scene: 'corridor',
    sceneOptions: { seed: 11, doorSide: 'alternate', lightStart: 2.4, lightEvery: 4.6 },
    camera: { position: { x: -0.35, y: 1.6, z: 0.2 }, yaw: 0.05, pitch: -0.03, focal: 780 },
    cameraBounce: 0.22,
    treatment: { exposure: 1.5, vignette: 0.6, grain: 0.036, noise: 0.05 },
    props: [
      { kind: 'sign', x: -1.26, y: 2.16, z: 4.6, w: 0.46, h: 0.15, color: [178, 174, 158], emissive: 0.16 },
      { kind: 'box', x: 0.9, y: 0.06, z: 1.4, w: 0.3, h: 0.12, d: 0.3, color: [70, 70, 66] },
    ],
    relationships: [
      { to: 'NX-CAM-07', kind: 'TEMPORAL', note: 'CAM-07 covers the same segment two minutes later.' },
      { to: 'NX-037-D-01', kind: 'SPATIAL', note: 'Incident record names LOC-C214.' },
    ],
  },
  {
    asset: 'photo_nx037_b_02',
    code: 'NX-037-B-02',
    title: 'East Corridor, Disputed Segment',
    description: 'Second frame. A figure stands at the corridor mouth. Development is uneven; the body is not resolvable.',
    type: 'PHOTOGRAPH',
    condition: 'NORMAL',
    state: 'FLAGGED',
    location: LOCATION_CODES.C214B,
    device: 'FIELD-CAM-02',
    capturedAt: '14 OCT 94 03:17:11',
    acquiredAt: '14 OCT 94 03:49',
    integrity: 'QUESTIONED',
    source: 'OBS-02 FIELD RECOVERY',
    scene: 'corridor',
    sceneOptions: { seed: 12, length: 30, lightStart: 3.0, lightEvery: 5.0, doorSide: 'both' },
    camera: { position: { x: 0.55, y: 1.58, z: 0.4 }, yaw: -0.06, pitch: -0.01, focal: 720 },
    cameraBounce: 0.3,
    treatment: { exposure: 2.0, vignette: 0.68, grain: 0.05, noise: 0.07, blur: 2 },
    props: [
      { kind: 'figure', x: -0.1, y: 0, z: 13.5, height: 1.76, facing: 0.1, color: [14, 14, 16] },
      { kind: 'crate', x: 1.0, y: 0, z: 6.2, w: 0.44, h: 0.4, d: 0.38 },
    ],
    relationships: [
      { to: 'NX-CAM-07', kind: 'TEMPORAL', note: 'Clock reads the same second as the CAM-07 frame.' },
      { to: 'NX-037-P-01', kind: 'PERSONNEL', note: 'Build matches L.V.-0029; cannot be confirmed.' },
    ],
  },
  {
    asset: 'photo_nx037_b_03',
    code: 'NX-037-B-03',
    title: 'Central Archive, Aisle 2',
    description: 'Records room after hours. A run of boxes has been pulled and not replaced.',
    type: 'PHOTOGRAPH',
    condition: 'NORMAL',
    state: 'REVIEWED',
    location: LOCATION_CODES.C101,
    device: 'FIELD-CAM-02',
    capturedAt: '14 OCT 94 02:41:09',
    acquiredAt: '14 OCT 94 04:02',
    integrity: 'VERIFIED',
    source: 'OBS-02 FIELD RECOVERY',
    scene: 'archive',
    sceneOptions: { seed: 13, lit: false },
    camera: { position: { x: -0.2, y: 1.66, z: 0.3 }, yaw: 0.02, pitch: -0.06, focal: 700 },
    cameraBounce: 0.34,
    treatment: { exposure: 2.5, vignette: 0.7, grain: 0.04, noise: 0.06, tint: [1, 0.99, 1.05] },
    props: [
      { kind: 'chair', x: 0.6, y: 0, z: 2.2 },
      { kind: 'box', x: 0.35, y: 0.04, z: 3.05, w: 0.4, h: 0.08, d: 0.3, color: [176, 170, 152] },
    ],
    relationships: [
      { to: 'NX-037-P-05', kind: 'PERSONNEL', note: 'M.S.-0388 works this room.' },
      { to: 'NX-037-F-07', kind: 'REFERENCE', note: 'Torn shelf label recovered from the same aisle.' },
    ],
  },
  {
    asset: 'photo_nx037_b_04',
    code: 'NX-037-B-04',
    title: 'Stairwell 1, Half Landing',
    description: 'The handrail has been wiped. The damp on the wall is newer than the paint.',
    type: 'PHOTOGRAPH',
    condition: 'NORMAL',
    state: 'REVIEWED',
    location: LOCATION_CODES.C118,
    device: 'FIELD-CAM-02',
    capturedAt: '14 OCT 94 02:58:30',
    acquiredAt: '14 OCT 94 04:05',
    integrity: 'VERIFIED',
    source: 'OBS-02 FIELD RECOVERY',
    scene: 'stairwell',
    sceneOptions: { seed: 14, lit: false },
    camera: { position: { x: 0.1, y: 1.55, z: 0.2 }, yaw: -0.03, pitch: 0.06, focal: 760 },
    cameraBounce: 0.26,
    treatment: { exposure: 2.6, vignette: 0.66, grain: 0.045, noise: 0.065 },
    props: [],
    relationships: [{ to: 'NX-CAM-03', kind: 'SPATIAL', note: 'CAM-03 covers this landing.' }],
  },
  {
    asset: 'photo_nx037_b_05',
    code: 'NX-037-B-05',
    title: 'Science Wing, Lab 04',
    description: 'The bench has been cleared. The whiteboard still carries the previous night\'s arithmetic.',
    type: 'PHOTOGRAPH',
    condition: 'NORMAL',
    state: 'UNREVIEWED',
    location: LOCATION_CODES.C202,
    device: 'FIELD-CAM-02',
    capturedAt: '14 OCT 94 02:20:15',
    acquiredAt: '14 OCT 94 04:11',
    integrity: 'VERIFIED',
    source: 'OBS-02 FIELD RECOVERY',
    scene: 'lab',
    sceneOptions: { seed: 15, lit: true },
    camera: { position: { x: 0.4, y: 1.62, z: 0.3 }, yaw: -0.04, pitch: -0.04, focal: 720 },
    treatment: { exposure: 0.62, vignette: 0.6, grain: 0.034, noise: 0.05 },
    props: [{ kind: 'chair', x: 1.1, y: 0, z: 4.4 }],
    relationships: [{ to: 'NX-037-P-01', kind: 'PERSONNEL', note: 'Lab 04 is L.V.-0029\'s assigned bench.' }],
  },
  {
    asset: 'photo_nx037_b_06',
    code: 'NX-037-B-06',
    title: 'Main Entrance, Night Approach',
    description: 'Sodium light over the canopy. The doors were chained from the inside at 22:00.',
    type: 'PHOTOGRAPH',
    condition: 'NORMAL',
    state: 'REVIEWED',
    location: LOCATION_CODES.C001,
    device: 'FIELD-CAM-01',
    capturedAt: '14 OCT 94 01:52:03',
    acquiredAt: '14 OCT 94 04:14',
    integrity: 'VERIFIED',
    source: 'OBS-02 FIELD RECOVERY',
    scene: 'entrance',
    sceneOptions: { seed: 16, night: true },
    camera: { position: { x: 1.2, y: 1.68, z: 0.2 }, yaw: -0.12, pitch: 0.02, focal: 700 },
    treatment: { exposure: 2.0, vignette: 0.66, grain: 0.04, noise: 0.055, tint: [1.02, 0.99, 0.96] },
    props: [],
    relationships: [{ to: 'NX-CAM-01', kind: 'SPATIAL', note: 'CAM-01 covers the entrance bay.' }],
  },
  {
    asset: 'photo_nx037_b_07',
    code: 'NX-037-B-07',
    title: 'East Corridor, Underside',
    description: 'Flash was fired toward the ceiling. The print is unusable for detail, but the fixture spacing is legible.',
    type: 'PHOTOGRAPH',
    condition: 'DAMAGED',
    state: 'UNRESOLVED',
    location: LOCATION_CODES.C214,
    device: 'FIELD-CAM-01',
    capturedAt: '14 OCT 94 03:0_:__',
    acquiredAt: '14 OCT 94 04:18',
    integrity: 'PARTIAL',
    source: 'OBS-02 FIELD RECOVERY',
    scene: 'corridor',
    sceneOptions: { seed: 17, length: 28, lightStart: 2.0, lightEvery: 4.2 },
    camera: { position: { x: 0.0, y: 1.6, z: 0.2 }, yaw: 0, pitch: 0.52, focal: 700 },
    treatment: { exposure: 0.62, vignette: 0.5, grain: 0.05, noise: 0.07, blur: 3, flashStrength: 0.4 },
    damageKind: 'OVEREXPOSED',
    props: [],
    relationships: [{ to: 'NX-037-B-01', kind: 'REFERENCE', note: 'Same corridor, same camera body.' }],
  },
  {
    asset: 'photo_nx037_b_08',
    code: 'NX-037-B-08',
    title: 'Sub-Basement Plant Room, Valve Tree',
    description: 'Water on the floor. One valve has been closed and re-marked in grease pencil.',
    type: 'PHOTOGRAPH',
    condition: 'NORMAL',
    state: 'FLAGGED',
    location: LOCATION_CODES.SUB,
    device: 'FIELD-CAM-02',
    capturedAt: '14 OCT 94 01:31:47',
    acquiredAt: '14 OCT 94 04:21',
    integrity: 'VERIFIED',
    source: 'OBS-02 FIELD RECOVERY',
    scene: 'plant',
    sceneOptions: { seed: 18, lit: true },
    camera: { position: { x: -0.1, y: 1.5, z: 0.2 }, yaw: 0.03, pitch: -0.05, focal: 660 },
    cameraBounce: 0.2,
    treatment: { exposure: 2.4, vignette: 0.72, grain: 0.05, noise: 0.07, tint: [0.97, 1, 1.02] },
    props: [],
    relationships: [{ to: 'NX-037-F-04', kind: 'REFERENCE', note: 'Torn maintenance label names the same valve tree.' }],
  },
  {
    asset: 'photo_nx037_b_09',
    code: 'NX-037-B-09',
    title: 'Equipment Room 305, Crates',
    description: 'Storage was used as storage. Several crates are stencilled with a department that closed in 1991.',
    type: 'PHOTOGRAPH',
    condition: 'NORMAL',
    state: 'UNREVIEWED',
    location: LOCATION_CODES.C305,
    device: 'FIELD-CAM-02',
    capturedAt: '14 OCT 94 02:05:52',
    acquiredAt: '14 OCT 94 04:24',
    integrity: 'VERIFIED',
    source: 'OBS-02 FIELD RECOVERY',
    scene: 'storage',
    sceneOptions: { seed: 19, lit: false },
    camera: { position: { x: 0.5, y: 1.6, z: 0.2 }, yaw: -0.05, pitch: -0.03, focal: 680 },
    cameraBounce: 0.3,
    treatment: { exposure: 2.7, vignette: 0.7, grain: 0.05, noise: 0.07 },
    props: [],
    relationships: [{ to: 'NX-037-D-05', kind: 'REFERENCE', note: 'Custody form lists crate 14 from this room.' }],
  },
  {
    asset: 'photo_nx037_b_10',
    code: 'NX-037-B-10',
    title: 'Archive Office, Desk 04',
    description: 'A terminal left running. The screen holds a directory listing that does not match the building.',
    type: 'PHOTOGRAPH',
    condition: 'NORMAL',
    state: 'FLAGGED',
    location: 'LOC-C101A / ARCHIVE OFFICE',
    device: 'FIELD-CAM-02',
    capturedAt: '14 OCT 94 02:48:20',
    acquiredAt: '14 OCT 94 04:27',
    integrity: 'VERIFIED',
    source: 'OBS-02 FIELD RECOVERY',
    scene: 'office',
    sceneOptions: { seed: 20, lit: false },
    camera: { position: { x: -0.3, y: 1.6, z: 0.3 }, yaw: 0.08, pitch: -0.05, focal: 700 },
    cameraBounce: 0.24,
    treatment: { exposure: 2.5, vignette: 0.68, grain: 0.045, noise: 0.06 },
    props: [],
    relationships: [{ to: 'NX-037-P-05', kind: 'PERSONNEL', note: 'Desk 04 is assigned to M.S.-0388.' }],
  },
  {
    asset: 'photo_nx037_b_11',
    code: 'NX-037-B-11',
    title: 'Lecture Room 214, Empty',
    description: 'Seating plan unchanged since 1993. Row B seat 7 carries a name written in pencil.',
    type: 'PHOTOGRAPH',
    condition: 'NORMAL',
    state: 'REVIEWED',
    location: 'LOC-C214H / LECTURE ROOM',
    device: 'FIELD-CAM-02',
    capturedAt: '14 OCT 94 02:33:58',
    acquiredAt: '14 OCT 94 04:30',
    integrity: 'VERIFIED',
    source: 'OBS-02 FIELD RECOVERY',
    scene: 'classroom',
    sceneOptions: { seed: 21, lit: true },
    camera: { position: { x: 0.0, y: 1.72, z: 0.2 }, yaw: 0, pitch: -0.02, focal: 700 },
    treatment: { exposure: 1.55, vignette: 0.62, grain: 0.036, noise: 0.05 },
    props: [],
    relationships: [{ to: 'NX-037-P-01', kind: 'PERSONNEL', note: 'L.V.-0029 taught this room.' }],
  },
  {
    asset: 'photo_nx037_b_12',
    code: 'NX-037-B-12',
    title: 'East Corridor, Water Damage',
    description: 'A frame taken after the incident. The print has been wet and dried. The timestamp is gone.',
    type: 'PHOTOGRAPH',
    condition: 'DAMAGED',
    state: 'CONTRADICTED',
    location: LOCATION_CODES.C214,
    device: 'FIELD-CAM-02',
    capturedAt: '14 OCT 94 __:17:__',
    acquiredAt: '14 OCT 94 04:35',
    integrity: 'DEGRADED',
    source: 'OBS-02 FIELD RECOVERY',
    scene: 'corridor',
    sceneOptions: { seed: 22, length: 26, lightStart: 2.6, lightEvery: 4.8, doorSide: 'right' },
    camera: { position: { x: 0.2, y: 1.58, z: 0.3 }, yaw: 0.04, pitch: -0.02, focal: 740 },
    treatment: { exposure: 2.05, vignette: 0.66, grain: 0.055, noise: 0.075, tint: [0.98, 1, 1.03] },
    condition_visual: 'STAIN',
    damageKind: 'STAIN',
    props: [{ kind: 'crate', x: -1.0, y: 0, z: 9.0, w: 0.5, h: 0.42, d: 0.44 }],
    relationships: [
      { to: 'NX-037-B-02', kind: 'CONTRADICTION', note: 'Both claim LOC-C214 at the same minute.' },
      { to: 'NX-CAM-07', kind: 'TEMPORAL', note: 'Only surviving seconds in this run.' },
    ],
  },
]

/* ──────────────────────────── surveillance ──────────────────────────── */

export const SURVEILLANCE = [
  {
    asset: 'surv_cam07_031711',
    code: 'NX-CAM-07',
    title: 'CAM-07 / East Corridor, 03:17:11',
    description: 'Recorder frame. The corridor is empty. CAM-07 covers the same segment the field camera photographed at the same second.',
    type: 'SURVEILLANCE',
    condition: 'PARTIAL',
    state: 'CONTRADICTED',
    surveillanceState: 'SIGNAL DEGRADED',
    integrity: 'FRAME DROPOUT 03:17:05–03:17:18',
    location: LOCATION_CODES.C214,
    device: 'CAM-07 / DVR NODE B-04',
    cameraLabel: 'CAM-07',
    osdLocation: LOCATION_CODES.C214,
    osdDate: '14-10-94',
    osdTime: '03:17:11',
    frame: 118842,
    totalFrames: 345600,
    capturedAt: '14 OCT 94 03:17:11',
    acquiredAt: '19 OCT 94 11:20',
    source: 'DVR NODE B-04 / TAPE 7',
    scene: 'corridor',
    sceneOptions: { seed: 31, length: 24, lightStart: 2.4, lightEvery: 4.6, doorSide: 'alternate' },
    camera: { position: { x: 0, y: 2.92, z: 0.35 }, yaw: 0, pitch: -0.5 },
    hfov: 106,
    damageKind: 'PARTIAL',
    props: [
      { kind: 'sign', x: -1.24, y: 2.1, z: 5.2, w: 0.44, h: 0.14, color: [176, 172, 156], emissive: 0.2 },
    ],
    relationships: [
      { to: 'NX-037-B-02', kind: 'CONTRADICTION', note: 'Same second. The frame shows no one.' },
      { to: 'NX-037-F-03', kind: 'REFERENCE', note: 'Torn label assigns CAM-07 to this corridor.' },
    ],
  },
  {
    asset: 'surv_cam01_015203',
    code: 'NX-CAM-01',
    title: 'CAM-01 / Main Entrance, 01:52:03',
    description: 'Entrance bay. The doors are chained. No movement for the length of the tape.',
    type: 'SURVEILLANCE',
    condition: 'NORMAL',
    state: 'REVIEWED',
    surveillanceState: 'SIGNAL STABLE',
    integrity: 'RECORD INTACT',
    location: LOCATION_CODES.C001,
    device: 'CAM-01 / DVR NODE B-04',
    cameraLabel: 'CAM-01',
    osdLocation: LOCATION_CODES.C001,
    osdDate: '14-10-94',
    osdTime: '01:52:03',
    frame: 66420,
    totalFrames: 345600,
    capturedAt: '14 OCT 94 01:52:03',
    acquiredAt: '19 OCT 94 11:04',
    source: 'DVR NODE B-04 / TAPE 1',
    scene: 'entrance',
    sceneOptions: { seed: 32, night: true },
    camera: { position: { x: 0, y: 4.4, z: 3.4 }, yaw: 0, pitch: -0.34 },
    hfov: 96,
    props: [],
    relationships: [{ to: 'NX-037-B-06', kind: 'TEMPORAL', note: 'Field camera at the same minute.' }],
  },
  {
    asset: 'surv_cam03_025830',
    code: 'NX-CAM-03',
    title: 'CAM-03 / Stairwell 1, 02:58:30',
    description: 'Landing. Low light. The camera has not been serviced since the wing closed.',
    type: 'SURVEILLANCE',
    condition: 'NORMAL',
    state: 'UNREVIEWED',
    surveillanceState: 'LOW LIGHT',
    integrity: 'LOW LIGHT / GAIN AT MAXIMUM',
    location: LOCATION_CODES.C118,
    device: 'CAM-03 / DVR NODE B-04',
    cameraLabel: 'CAM-03',
    osdLocation: LOCATION_CODES.C118,
    osdDate: '14-10-94',
    osdTime: '02:58:30',
    frame: 104664,
    totalFrames: 345600,
    capturedAt: '14 OCT 94 02:58:30',
    acquiredAt: '19 OCT 94 11:31',
    source: 'DVR NODE B-04 / TAPE 3',
    scene: 'stairwell',
    sceneOptions: { seed: 33, lit: false },
    camera: { position: { x: 0.4, y: 3.0, z: 0.4 }, yaw: -0.1, pitch: -0.62 },
    hfov: 112,
    props: [],
    relationships: [{ to: 'NX-037-B-04', kind: 'SPATIAL', note: 'Field photograph of the same landing.' }],
  },
  {
    asset: 'surv_cam02_024120',
    code: 'NX-CAM-02',
    title: 'CAM-02 / Central Archive, 02:41:20',
    description: 'Records room. The aisle light cycles. A person is at the far shelving, back to camera.',
    type: 'SURVEILLANCE',
    condition: 'NORMAL',
    state: 'FLAGGED',
    surveillanceState: 'SIGNAL STABLE',
    integrity: 'RECORD INTACT',
    location: LOCATION_CODES.C101,
    device: 'CAM-02 / DVR NODE B-04',
    cameraLabel: 'CAM-02',
    osdLocation: LOCATION_CODES.C101,
    osdDate: '14-10-94',
    osdTime: '02:41:20',
    frame: 97484,
    totalFrames: 345600,
    capturedAt: '14 OCT 94 02:41:20',
    acquiredAt: '19 OCT 94 10:52',
    source: 'DVR NODE B-04 / TAPE 2',
    scene: 'archive',
    sceneOptions: { seed: 34, lit: true },
    camera: { position: { x: -0.6, y: 3.05, z: 0.5 }, yaw: 0.18, pitch: -0.44 },
    hfov: 104,
    props: [{ kind: 'figure', x: 0.6, y: 0, z: 7.4, height: 1.7, facing: 2.6, color: [30, 30, 32] }],
    relationships: [{ to: 'NX-037-B-03', kind: 'TEMPORAL', note: 'Field camera eleven seconds later.' }],
  },
  {
    asset: 'surv_cam05_022015',
    code: 'NX-CAM-05',
    title: 'CAM-05 / Lab 04, 02:20:15',
    description: 'Laboratory. Benches cleared. The whiteboard is legible in frame and was not legible in the field print.',
    type: 'SURVEILLANCE',
    condition: 'NORMAL',
    state: 'REVIEWED',
    surveillanceState: 'SIGNAL STABLE',
    integrity: 'RECORD INTACT',
    location: LOCATION_CODES.C202,
    device: 'CAM-05 / DVR NODE B-04',
    cameraLabel: 'CAM-05',
    osdLocation: LOCATION_CODES.C202,
    osdDate: '14-10-94',
    osdTime: '02:20:15',
    frame: 84060,
    totalFrames: 345600,
    capturedAt: '14 OCT 94 02:20:15',
    acquiredAt: '19 OCT 94 10:31',
    source: 'DVR NODE B-04 / TAPE 5',
    scene: 'lab',
    sceneOptions: { seed: 35, lit: true },
    camera: { position: { x: 0.2, y: 2.9, z: 0.4 }, yaw: 0, pitch: -0.5 },
    hfov: 100,
    treatment: { exposure: 1.15 },
    props: [],
    relationships: [{ to: 'NX-037-B-05', kind: 'SPATIAL', note: 'Field photograph of the same bench.' }],
  },
  {
    asset: 'surv_cam04_024820',
    code: 'NX-CAM-04',
    title: 'CAM-04 / Archive Office, 02:48:20',
    description: 'Terminal running. Directory listing on screen. No one at the desk for the length of the tape.',
    type: 'SURVEILLANCE',
    condition: 'NORMAL',
    state: 'FLAGGED',
    surveillanceState: 'SIGNAL STABLE',
    integrity: 'RECORD INTACT',
    location: 'LOC-C101A / ARCHIVE OFFICE',
    device: 'CAM-04 / DVR NODE B-04',
    cameraLabel: 'CAM-04',
    osdLocation: 'LOC-C101A / ARCHIVE OFFICE',
    osdDate: '14-10-94',
    osdTime: '02:48:20',
    frame: 103200,
    totalFrames: 345600,
    capturedAt: '14 OCT 94 02:48:20',
    acquiredAt: '19 OCT 94 10:44',
    source: 'DVR NODE B-04 / TAPE 4',
    scene: 'office',
    sceneOptions: { seed: 36, lit: true },
    camera: { position: { x: -0.8, y: 2.7, z: 0.4 }, yaw: 0.12, pitch: -0.46 },
    hfov: 102,
    props: [],
    relationships: [{ to: 'NX-037-B-10', kind: 'TEMPORAL', note: 'Field camera at the same second.' }],
  },
  {
    asset: 'surv_cam06_0316_offline',
    code: 'NX-CAM-06',
    title: 'CAM-06 / Sub-Basement, 03:16:00',
    description: 'The camera is not transmitting. The recorder kept the last frame it ever received and kept trying.',
    type: 'SURVEILLANCE',
    condition: 'INCOMPLETE',
    state: 'UNRESOLVED',
    surveillanceState: 'CAMERA OFFLINE',
    integrity: 'NO SIGNAL — LAST FRAME RETAINED',
    location: LOCATION_CODES.SUB,
    device: 'CAM-06 / DVR NODE B-04',
    cameraLabel: 'CAM-06',
    osdLocation: LOCATION_CODES.SUB,
    osdDate: '14-10-94',
    osdTime: '03:16:00',
    capturedAt: '14 OCT 94 03:16:00',
    acquiredAt: '19 OCT 94 12:02',
    source: 'DVR NODE B-04 / TAPE 6',
    scene: 'plant',
    sceneOptions: { seed: 37, lit: true },
    camera: { position: { x: 0, y: 2.5, z: 0.4 }, yaw: 0, pitch: -0.5 },
    hfov: 108,
    props: [],
    relationships: [{ to: 'NX-037-B-08', kind: 'SPATIAL', note: 'Field photograph of the same room.' }],
  },
  {
    asset: 'surv_cam08_0305_partial',
    code: 'NX-CAM-08',
    title: 'CAM-08 / Equipment Room, 03:05:41',
    description: 'Storage. A recording interval is missing between 03:04:12 and 03:07:30. The recorder does not log why.',
    type: 'SURVEILLANCE',
    condition: 'DAMAGED',
    state: 'UNRESOLVED',
    surveillanceState: 'PARTIAL RECORD',
    integrity: 'INTERVAL MISSING 03:04:12–03:07:30',
    location: LOCATION_CODES.C305,
    device: 'CAM-08 / DVR NODE B-04',
    cameraLabel: 'CAM-08',
    osdLocation: LOCATION_CODES.C305,
    osdDate: '14-10-94',
    osdTime: '03:05:41',
    frame: 130662,
    totalFrames: 345600,
    capturedAt: '14 OCT 94 03:05:41',
    acquiredAt: '19 OCT 94 12:14',
    source: 'DVR NODE B-04 / TAPE 8',
    scene: 'storage',
    sceneOptions: { seed: 38, lit: false },
    camera: { position: { x: 0.3, y: 2.6, z: 0.4 }, yaw: -0.06, pitch: -0.56 },
    hfov: 110,
    damageKind: 'DAMAGED',
    props: [],
    relationships: [{ to: 'NX-037-B-09', kind: 'SPATIAL', note: 'Field photograph of the same room.' }],
  },
  {
    asset: 'surv_cam09_0225_lecture',
    code: 'NX-CAM-09',
    title: 'CAM-09 / Lecture Room 214, 02:25:07',
    description: 'Lecture room. A single seat is occupied. The tape holds eleven minutes of nothing else happening.',
    type: 'SURVEILLANCE',
    condition: 'NORMAL',
    state: 'FLAGGED',
    surveillanceState: 'SIGNAL STABLE',
    integrity: 'RECORD INTACT',
    location: 'LOC-C214H / LECTURE ROOM',
    device: 'CAM-09 / DVR NODE B-04',
    cameraLabel: 'CAM-09',
    osdLocation: 'LOC-C214H / LECTURE ROOM',
    osdDate: '14-10-94',
    osdTime: '02:25:07',
    frame: 88200,
    totalFrames: 345600,
    capturedAt: '14 OCT 94 02:25:07',
    acquiredAt: '19 OCT 94 12:40',
    source: 'DVR NODE B-04 / TAPE 9',
    scene: 'classroom',
    sceneOptions: { seed: 39, lit: true },
    camera: { position: { x: 0, y: 2.9, z: 0.3 }, yaw: 0, pitch: -0.44 },
    hfov: 98,
    props: [{ kind: 'figure', x: 0.0, y: 0.44, z: 4.0, height: 1.3, facing: 0, color: [34, 34, 36] }],
    relationships: [{ to: 'NX-037-B-11', kind: 'SPATIAL', note: 'Field photograph of the same room.' }],
  },
]

/* ────────────────────────────── documents ────────────────────────────── */

export const DOCUMENTS = [
  {
    asset: 'doc_nx037_incident_rev03',
    code: 'NX-037-D-01',
    title: 'Incident Record 037, Section 4 — East Wing',
    description: 'The typed record that opened the case. Section 2 lists four recovered items; only three arrived intact.',
    type: 'DOCUMENT',
    condition: 'NORMAL',
    state: 'REVIEWED',
    form: 'incident',
    revision: 'REV 03',
    control: 'IR-037-04',
    location: 'BUREAU OF CONTINUITY RECORDS',
    device: 'TYPEWRITER / REMINGTON 42',
    capturedAt: '19 OCT 94',
    acquiredAt: '19 OCT 94 09:10',
    integrity: 'VERIFIED',
    source: 'CASE FILE NX-037',
    summary: 'At approximately 03:17 on 14 October 1994 the observation team entered the east wing of the admin building following a report of movement. The corridor designated LOC-C214 was found empty. One fixture between the archive door and the north stair was not operating. No person was recovered, and none was recorded leaving.',
    attestation: 'I certify that the material listed above was recovered by the undersigned and has not been altered. Item C was wet on receipt and is filed in that state.',
    officer: 'N. RAHAL / OBSERVATION',
    signer: 'N. RAHAL / OBSERVATION',
    filed: '19 OCT 94',
    redactions: [
      { x: 56, y: 690, w: 300, h: 15, label: 'WITHHELD' },
      { x: 56, y: 710, w: 214, h: 15, label: 'WITHHELD' },
    ],
    relationships: [
      { to: 'NX-037-B-02', kind: 'REFERENCE', note: 'Item A is the disputed corridor frame.' },
      { to: 'NX-037-F-02', kind: 'REFERENCE', note: 'Item C is the wet torn label.' },
    ],
  },
  {
    asset: 'doc_nx037_ledger_sectorc',
    code: 'NX-037-D-02',
    title: 'Maintenance Ledger, Sector C, Vol. 3',
    description: 'Bound repair log. The 12 October entry describes a camera relocation that no other record mentions.',
    type: 'DOCUMENT',
    condition: 'NORMAL',
    state: 'FLAGGED',
    form: 'ledger',
    seed: 41,
    sheetTitle: 'MAINTENANCE LEDGER — SECTOR C',
    location: 'FACILITIES ENGINEERING',
    device: 'BOUND LEDGER',
    capturedAt: '1994',
    acquiredAt: '19 OCT 94 09:40',
    integrity: 'VERIFIED',
    source: 'FACILITIES ENGINEERING / VOL 3',
    control: 'LOG-C-V3',
    bookRef: 'VOL. 3 / PG. 118',
    entries: [
      ['04 OCT', 'ROUTINE. LAMPS 1-4 EAST. NO ACTION.'],
      ['09 OCT', 'CAM-07 REAIMED. OPERATOR DID NOT SIGN.'],
      ['11 OCT', 'VALVE TREE SUB-BASEMENT. REPAIRED.'],
      ['12 OCT', 'CAM-07 MOVED TO C214. TAPE ROUTED.'],
      ['13 OCT', 'NO CALL-OUT RECEIVED.'],
      ['14 OCT', 'ATTENDED 01:40. LEFT BEFORE 02:00.'],
    ],
    relationships: [
      { to: 'NX-CAM-07', kind: 'SOURCE', note: 'The ledger is the only record of the relocation.' },
      { to: 'NX-037-F-04', kind: 'REFERENCE', note: 'Torn label continues this ledger.' },
    ],
  },
  {
    asset: 'doc_nx037_access_export',
    code: 'NX-037-D-03',
    title: 'Access Control Export, 14 October',
    description: 'Continuous-form printout from the registry. One credential reads at 03:17:11 and does not exist.',
    type: 'DOCUMENT',
    condition: 'NORMAL',
    state: 'UNREVIEWED',
    form: 'printout',
    seed: 42,
    location: 'NEXUS NODE B-04 / TERMINAL 07',
    device: 'REGISTRY PRINTER / DOT MATRIX',
    capturedAt: '14 OCT 94 04:40',
    acquiredAt: '19 OCT 94 10:02',
    integrity: 'VERIFIED',
    source: 'NODE B-04',
    control: 'ACC-EXP-2214',
    queryAt: '03:17:11Z',
    rows: [
      'HALL      CRED    HOLDER             ZONE        RESULT',
      '--------  ------  -----------------  ----------  ------',
      'EAST-C    L.V.0029  VEY, L.         LAB 04      GRANTED',
      'EAST-C    ----    <UNASSIGNED>       C214        GRANTED',
      'EAST-C    M.C.0114  CARTER, M.      LAB 02      GRANTED',
      'EAST-C    ----    <UNASSIGNED>       C214        GRANTED',
      'EAST-C    N.R.0471  RAHAL, N.       ALL EXT     GRANTED',
      'ARCH      M.S.0388  SELIM, M.       ARCHIVE     GRANTED',
      '--------  ------  -----------------  ----------  ------',
      'ENTRIES 00007   UNASSIGNED 00002   ANOMALOUS',
    ],
    trailer: 'WARNING: CREDENTIAL BLOCK NOT PRESENT IN DIRECTORY SNAPSHOT',
    relationships: [
      { to: 'NX-037-B-02', kind: 'TEMPORAL', note: 'The unassigned reads at the photograph\'s timestamp.' },
      { to: 'NX-037-P-01', kind: 'PERSONNEL', note: 'L.V.-0029 is the nearest real holder.' },
    ],
  },
  {
    asset: 'doc_nx037_memo_operations',
    code: 'NX-037-D-04',
    title: 'Memorandum — East Wing Operations',
    description: 'Internal memo on continuing the east wing after the archive move. The carbon copy is the only one that survived.',
    type: 'DOCUMENT',
    condition: 'PARTIAL',
    state: 'UNREVIEWED',
    form: 'memo',
    seed: 43,
    carbon: true,
    to: 'DIRECTOR, INTERNAL OPERATIONS',
    from: 'M. CARTER / DEPUTY LEAD',
    date: '04 OCT 94',
    re: 'CONTINUED OCCUPANCY — EAST WING',
    ref: 'OPS/EW-1114',
    location: 'INTERNAL OPERATIONS',
    device: 'CARBON SET / DUPLICATED',
    capturedAt: '04 OCT 94',
    acquiredAt: '19 OCT 94 10:20',
    integrity: 'PARTIAL',
    source: 'OPERATIONS FILE',
    paragraphs: [
      'The east wing is to remain in use through the winter. Archive transfer is deferred to the spring. Doors are to be chained nightly from the inside; the chain is not to be removed in the morning.',
      'CAM-07 has been re-aimed to cover the corridor mouth. Its tape route now passes through the sub-basement. Facilities are to log the work in the sector ledger.',
    ],
    carbonText: 'CAM-07 has been re-aimed to cover the corridor mouth. Its tape route now passes through the sub-basement.',
    signer: 'M. CARTER',
    relationships: [
      { to: 'NX-037-D-02', kind: 'REFERENCE', note: 'The ledger entry that follows this memo.' },
      { to: 'NX-CAM-07', kind: 'SOURCE', note: 'Names the re-aim directly.' },
    ],
  },
  {
    asset: 'doc_nx037_accesscard_ley',
    code: 'NX-037-D-05',
    title: 'Access Card, Level 3 — L.V.-0029',
    description: 'The card itself, photographed on a light table. The laminate is lifted at one corner.',
    type: 'DOCUMENT',
    condition: 'NORMAL',
    state: 'REVIEWED',
    form: 'card',
    seed: 44,
    level: 'LEVEL 3',
    zone: 'RESEARCH DIVISION',
    holder: 'VEY, L.   L.V.-0029',
    cardNumber: '03-4471-886',
    issued: '04 MAR 94',
    expires: '31 MAR 97',
    bandColor: '#7a2b26',
    hologram: true,
    location: 'RECOVERED — LOC-C214',
    device: 'LIGHT TABLE / FIELD-CAM-02',
    capturedAt: '14 OCT 94 04:10',
    acquiredAt: '14 OCT 94 04:12',
    integrity: 'VERIFIED',
    source: 'OBS-02 FIELD RECOVERY',
    relationships: [{ to: 'NX-037-P-01', kind: 'PERSONNEL', note: 'Confirms the holder is L.V.-0029.' }],
  },
  {
    asset: 'doc_nx037_custody_sheet',
    code: 'NX-037-D-06',
    title: 'Chain of Custody, Item NX-037-B-02',
    description: 'Custody transfers for the disputed frame. The last transfer has no receiving signature.',
    type: 'DOCUMENT',
    condition: 'DAMAGED',
    state: 'UNRESOLVED',
    form: 'custody',
    seed: 45,
    damageKind: 'TORN',
    tearEdge: 'right',
    tearDepth: 0.1,
    caseNo: 'NX-037',
    itemControl: 'NX-037-B-02',
    recoveredAt: 'EAST CORRIDOR / LOC-C214',
    recoveredBy: 'OBS-02',
    location: 'BUREAU OF CONTINUITY RECORDS',
    device: 'FILED FORM 2-A',
    capturedAt: '14 OCT 94',
    acquiredAt: '19 OCT 94 10:44',
    integrity: 'PARTIAL',
    source: 'CASE FILE NX-037',
    transfers: [
      ['14/10 0348', 'OBS-02', 'ARCHIVE', 'INTAKE', 'N.R.'],
      ['15/10 0915', 'ARCHIVE', 'EXAM 1', 'EXAMINATION', 'M.S.'],
      ['18/10 1102', 'EXAM 1', 'NODE B-04', 'IMAGING', '——'],
      ['19/10 1420', 'NODE B-04', 'REGISTRY', 'FILED', '——'],
    ],
    conditionText: 'RECEIVED WET. TIMESTAMP FIELD PARTIALLY LOST IN TRANSIT. FRAME SHOWS NO SUBJECT.',
    relationships: [
      { to: 'NX-037-B-02', kind: 'REFERENCE', note: 'This is the custody record for the disputed frame.' },
      { to: 'NX-CAM-07', kind: 'CONTRADICTION', note: 'Registry and recorder disagree.' },
    ],
  },
  {
    asset: 'doc_nx037_requisition',
    code: 'NX-037-D-07',
    title: 'Facilities Requisition 2214 — Sub-Basement',
    description: 'Work order for the valve tree. The sign-off time is earlier than the call-out it answers.',
    type: 'DOCUMENT',
    condition: 'NORMAL',
    state: 'FLAGGED',
    form: 'custody',
    seed: 46,
    caseNo: 'REQ-2214',
    itemControl: 'SUB-BASEMENT / VALVE TREE',
    recoveredAt: 'LOC-S01 / PLANT',
    recoveredBy: 'FACILITIES',
    location: 'FACILITIES ENGINEERING',
    device: 'FILED FORM 2-A',
    capturedAt: '11 OCT 94',
    acquiredAt: '19 OCT 94 11:12',
    integrity: 'VERIFIED',
    source: 'FACILITIES ENGINEERING',
    transfers: [
      ['11/10 0740', 'REQ', 'TECH-11', 'CALL-OUT', 'F.E.'],
      ['11/10 1130', 'TECH-11', 'WORKS', 'COMPLETE', 'T11'],
      ['11/10 1155', 'WORKS', 'CLOSED', 'FILED', 'F.E.'],
    ],
    conditionText: 'WORK COMPLETE 11:30. SIGN-OFF TIMESTAMP READS 06:55 ON RE-ENTRY TO FILE.',
    relationships: [{ to: 'NX-037-B-08', kind: 'SPATIAL', note: 'The same valve tree, photographed.' }],
  },
  {
    asset: 'doc_nx037_surveillance_log',
    code: 'NX-037-D-08',
    title: 'Recorder Log Sheet, Node B-04',
    description: 'The operator\'s own log of the night. It records a manual stop on Tape 7 that no system log shows.',
    type: 'DOCUMENT',
    condition: 'PARTIAL',
    state: 'UNRESOLVED',
    form: 'ledger',
    seed: 47,
    damageKind: 'STAIN',
    stainX: 0.78,
    stainY: 0.7,
    sheetTitle: 'RECORDER LOG — NODE B-04',
    bookRef: 'TAPE 7 / PG. 02',
    location: 'NEXUS NODE B-04',
    device: 'BOUND LOG',
    capturedAt: '14 OCT 94',
    acquiredAt: '19 OCT 94 11:26',
    integrity: 'PARTIAL',
    source: 'NODE B-04',
    control: 'DVR-LOG-B04',
    entries: [
      ['14 OCT', 'ON DUTY 22:00. ALL CAMERAS REPORT.'],
      ['14 OCT', '03:12 RE-ARM TAPE 7 AFTER FAULT.'],
      ['14 OCT', '03:17 MANUAL STOP. NO REASON GIVEN.'],
      ['14 OCT', '03:24 RESUME. 04:40 PULL TAPES.'],
      ['15 OCT', 'BLANK LINE — WRITER JAM'],
    ],
    relationships: [
      { to: 'NX-CAM-07', kind: 'TEMPORAL', note: 'The manual stop falls inside the dropout window.' },
      { to: 'NX-037-D-01', kind: 'REFERENCE', note: 'Incident record cites this log as item D.' },
    ],
  },
  {
    asset: 'doc_nx037_damaged_photo_log',
    code: 'NX-037-D-09',
    title: 'Photographic Processing Log, 14 October',
    description: 'Lab log for the field rolls. One frame is marked as rejected before it was printed, and the reason is not the exposure.',
    type: 'DOCUMENT',
    condition: 'DAMAGED',
    state: 'CONTRADICTED',
    form: 'printout',
    seed: 48,
    damageKind: 'MISSING',
    missingY: 0.44,
    missingH: 0.045,
    location: 'BUREAU LAB 3',
    device: 'LAB PRINTER / DOT MATRIX',
    capturedAt: '15 OCT 94',
    acquiredAt: '19 OCT 94 11:40',
    integrity: 'PARTIAL',
    source: 'BUREAU LAB 3',
    control: 'LAB-3-1014',
    queryAt: '16:20:00Z',
    rows: [
      'ROLL  FIELD-CAM-02      PRINTER  BUREAU LAB 3',
      'FRAME  EXPOSURE  NOTE',
      '------  -------  ----------------------------------',
      'B-01    1/8      ACCEPTED',
      'B-02    1/15     ACCEPTED',
      'B-03    1/8      ACCEPTED',
      'B-04    1/30     ACCEPTED',
      'B-05    1/4      ACCEPTED',
      'B-06    1/8      ACCEPTED',
      'B-07    —        REJECTED / OVEREXPOSED',
      'B-08    1/8      ACCEPTED',
      'B-09    1/8      ACCEPTED',
      'B-10    1/8      ACCEPTED',
      'B-11    1/8      ACCEPTED',
      'B-12    1/4      ACCEPTED / WET ON RECEIPT',
      '------  -------  ----------------------------------',
      'PRINTS 00012   REJECTED 00001',
    ],
    trailer: 'NOTE APPENDED: FRAME B-02 RESHOT BY ORDER OF M.C.0114 — SEE SEPARATE REQUEST',
    relationships: [
      { to: 'NX-037-B-07', kind: 'REFERENCE', note: 'The rejected frame.' },
      { to: 'NX-037-B-02', kind: 'CONTRADICTION', note: 'The log says this frame was reshot.' },
    ],
  },
]

/* ────────────────────────────── fragments ────────────────────────────── */

const fragText = (lines, opts = {}) => {
  const size = opts.size ?? 13
  const leading = opts.leading ?? 19
  let out = ''
  lines.forEach((line, i) => {
    out += `<text x="${opts.x ?? 40}" y="${(opts.y ?? 70) + i * leading}" font-family="'Courier New',Courier,monospace" font-size="${size}" fill="${opts.color ?? '#2a2620'}" opacity="0.92">${line.replace(/&/g, '&amp;').replace(/</g, '&lt;')}</text>`
  })
  return out
}

export const FRAGMENTS = [
  {
    asset: 'frag_nx037_c_01',
    code: 'NX-037-F-01',
    title: 'Torn Section — Incident Record',
    description: 'The middle of a typed report, torn from the file. Both ends of the sentence are gone.',
    type: 'FRAGMENT',
    condition: 'TORN',
    state: 'UNRESOLVED',
    width: 720, height: 380, rotation: -3, seed: 51,
    location: 'RECOVERED — LOC-C214',
    device: 'FILED PAPER',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 03:52',
    integrity: 'PARTIAL',
    source: 'OBS-02 FIELD RECOVERY',
    material: 'paper',
    base: () => `${fragText([
      '...the observation team records that the corridor',
      'was found without light between the archive',
      'door and the north stair, and that the fixture',
      'had been removed rather than failed. No tool',
      'mark was recovered. The team was of the',
    ], { y: 90 })}
      ${fragText(['opinion that the removal predated the', 'survey of 06 JUN 94, when the corridor was', 'last inspected as complete and lit, but the', 'surveyor\'s note could not be produced and the', 'surveyor had left the Institute in MAR 93...'], { y: 90 + 6 * 19, color: '#2a2620' })}
      <line x1="40" y1="60" x2="680" y2="60" stroke="#6f6653" stroke-width="0.8"/>
      <text x="40" y="48" font-family="'Courier New',Courier,monospace" font-size="10" letter-spacing="1.4" fill="#5c5546">IR-037-04 — SECTION 4, PAGE 1 OF 2 (PORTION)</text>`,
    relationships: [{ to: 'NX-037-D-01', kind: 'REFERENCE', note: 'A page of the incident record.' }],
  },
  {
    asset: 'frag_nx037_c_02',
    code: 'NX-037-F-02',
    title: 'Torn Maintenance Label',
    description: 'A stencilled equipment label, wet and torn. It names a camera the building has no record of.',
    type: 'FRAGMENT',
    condition: 'STAIN',
    state: 'FLAGGED',
    width: 620, height: 300, rotation: 4, seed: 52, wet: true,
    location: 'RECOVERED — LOC-C214',
    device: 'ADHESIVE LABEL',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 03:56',
    integrity: 'DAMAGED',
    source: 'OBS-02 FIELD RECOVERY',
    material: 'label',
    stamp: 'EVIDENCE',
    stampX: 40, stampY: 190,
    base: () => `<rect x="30" y="40" width="560" height="220" fill="#c8c2ac"/>
      <rect x="38" y="48" width="544" height="204" fill="none" stroke="#3a362c" stroke-width="2"/>
      <text x="56" y="92" font-family="'Courier New',Courier,monospace" font-size="13" letter-spacing="2" fill="#3a362c">FACILITIES ENGINEERING · ASSET LABEL</text>
      <line x1="56" y1="104" x2="564" y2="104" stroke="#3a362c" stroke-width="1"/>
      <text x="56" y="134" font-family="'Courier New',Courier,monospace" font-size="12" fill="#2a2620">ASSET  CAM-07</text>
      <text x="56" y="158" font-family="'Courier New',Courier,monospace" font-size="12" fill="#2a2620">ZONE   LOC-C214  EAST CORRIDOR</text>
      <text x="56" y="182" font-family="'Courier New',Courier,monospace" font-size="12" fill="#2a2620">MOUNT  CEILING, NORTH END</text>
      <text x="56" y="206" font-family="'Courier New',Courier,monospace" font-size="12" fill="#2a2620">DATE   12 OCT 94</text>
      <text x="56" y="230" font-family="'Courier New',Courier,monospace" font-size="11" fill="#4a4437">SERVICE BY: ______________  SIGNED: __________</text>`,
    relationships: [{ to: 'NX-CAM-07', kind: 'REFERENCE', note: 'Names the camera the incident record omits.' }],
  },
  {
    asset: 'frag_nx037_c_03',
    code: 'NX-037-F-03',
    title: 'Ripped Print Corner',
    description: 'A corner of a photographic print, recovered separately from the frame. The emulsion is scratched through.',
    type: 'FRAGMENT',
    condition: 'DAMAGED',
    state: 'UNRESOLVED',
    width: 560, height: 420, rotation: -6, seed: 53, points: 11, irregularity: 0.3,
    location: 'RECOVERED — LOC-C214',
    device: 'PRINT',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 04:00',
    integrity: 'DAMAGED',
    source: 'OBS-02 FIELD RECOVERY',
    material: 'photo',
    base: () => `<g opacity="0.92">
        <rect x="20" y="20" width="520" height="380" fill="#0d0e0d"/>
        <ellipse cx="300" cy="200" rx="150" ry="110" fill="#22241f"/>
        <rect x="120" y="120" width="70" height="200" fill="#2c2e28" opacity="0.7"/>
        <rect x="330" y="80" width="46" height="16" fill="#c9c4ae" opacity="0.7"/>
        <rect x="330" y="330" width="46" height="16" fill="#c9c4ae" opacity="0.6"/>
        <text x="34" y="374" font-family="'Courier New',Courier,monospace" font-size="13" fill="#d8d2bd" opacity="0.8">...:-__</text>
      </g>
      ${Array.from({ length: 9 }, (_, i) => `<line x1="${30 + i * 58}" y1="20" x2="${70 + i * 58}" y2="400" stroke="#e6e0cc" stroke-width="0.7" stroke-opacity="0.3"/>`).join('')}`,
    relationships: [{ to: 'NX-037-B-12', kind: 'REFERENCE', note: 'Same emulsion batch.' }],
  },
  {
    asset: 'frag_nx037_c_04',
    code: 'NX-037-F-04',
    title: 'Ledger Continuation, Torn',
    description: 'The bottom of a ledger page, separated at the binding. The last written line stops mid-word.',
    type: 'FRAGMENT',
    condition: 'TORN',
    state: 'UNREVIEWED',
    width: 640, height: 260, rotation: 2, seed: 54,
    location: 'RECOVERED — LOC-C214',
    device: 'LEDGER PAGE',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 04:04',
    integrity: 'PARTIAL',
    source: 'OBS-02 FIELD RECOVERY',
    material: 'paper',
    stock: 'ledger',
    base: () => `${Array.from({ length: 6 }, (_, i) => `<line x1="20" y1="${60 + i * 30}" x2="620" y2="${60 + i * 30}" stroke="#8a9a8c" stroke-width="0.7" stroke-opacity="0.55"/>`).join('')}
      <line x1="70" y1="20" x2="70" y2="240" stroke="#a8636a" stroke-width="1" stroke-opacity="0.5"/>
      <text x="26" y="50" font-family="'Segoe Print','Bradley Hand',cursive" font-size="14" fill="#25304a" transform="rotate(-1 26 50)">14 OCT</text>
      <text x="80" y="50" font-family="'Segoe Print','Bradley Hand',cursive" font-size="14" fill="#25304a" transform="rotate(1 80 50)">TAPE ROUTE RERUN VIA SUB-BASEMENT. JOINT</text>
      <text x="80" y="80" font-family="'Segoe Print','Bradley Hand',cursive" font-size="14" fill="#25304a" transform="rotate(-1 80 80)">FAILED AT 03:19. TAPE 7 NOT WRITTEN</text>
      <text x="80" y="110" font-family="'Segoe Print','Bradley Hand',cursive" font-size="14" fill="#25304a" transform="rotate(1 80 110)">03:17 TO 03:24 BY ORDER OF D. WRIGHT-</text>
      <text x="80" y="140" font-family="'Segoe Print','Bradley Hand',cursive" font-size="14" fill="#25304a" transform="rotate(-1 80 140)">____ WHO IS NOT ON THE ESTABLISH</text>`,
    relationships: [
      { to: 'NX-037-D-02', kind: 'REFERENCE', note: 'Continues the sector C ledger.' },
      { to: 'NX-037-P-06', kind: 'PERSONNEL', note: 'The name is cut off before it can be read.' },
    ],
  },
  {
    asset: 'frag_nx037_c_05',
    code: 'NX-037-F-05',
    title: 'Burnt Paper Fragment',
    description: 'Recovered from a brazier in the sub-basement. Most of the sheet is gone.',
    type: 'FRAGMENT',
    condition: 'BURNED',
    state: 'UNRESOLVED',
    width: 520, height: 400, rotation: 8, seed: 55, burned: true, points: 10, irregularity: 0.34,
    location: 'RECOVERED — LOC-S01',
    device: 'PAPER',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 01:40',
    integrity: 'DAMAGED',
    source: 'OBS-02 FIELD RECOVERY',
    material: 'paper',
    base: () => `${fragText(['SCENE LOG — SUB-BASEMENT', '', '01:12  BRAZIER LIT.', '01:20  SHEET FOUND IN ASH.', '01:26  PARTIAL TEXT:', '', '   ...the corridor is not a place', '   that empties. It is a place', '   that is emptied...'], { x: 40, y: 70, size: 13, leading: 22 })}`,
    relationships: [{ to: 'NX-037-B-08', kind: 'SPATIAL', note: 'Found beside the valve tree.' }],
  },
  {
    asset: 'frag_nx037_c_06',
    code: 'NX-037-F-06',
    title: 'Access Card, Cut',
    description: 'A card cut through the laminate. The photograph and half the number are gone.',
    type: 'FRAGMENT',
    condition: 'TORN',
    state: 'FLAGGED',
    width: 600, height: 320, rotation: -4, seed: 56,
    location: 'RECOVERED — LOC-C214',
    device: 'LAMINATE',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 03:58',
    integrity: 'PARTIAL',
    source: 'OBS-02 FIELD RECOVERY',
    material: 'card',
    base: () => `<rect x="20" y="20" width="560" height="280" fill="#d5cfbb"/>
      <rect x="20" y="20" width="560" height="280" fill="none" stroke="#8a8271" stroke-width="1.4"/>
      <rect x="20" y="140" width="560" height="42" fill="#7a2b26" fill-opacity="0.9"/>
      <text x="40" y="60" font-family="'Arial Narrow',Arial,sans-serif" font-size="14" letter-spacing="3" fill="#3c362c">HALDER INSTITUTE</text>
      <text x="40" y="170" font-family="'Arial Narrow',Arial,sans-serif" font-size="26" letter-spacing="6" fill="#f2eee0">LEVEL 3</text>
      <text x="40" y="212" font-family="'Courier New',monospace" font-size="14" fill="#241f19">03-44██-8██</text>
      <text x="40" y="238" font-family="'Courier New',monospace" font-size="11" fill="#4a4437">BEARER  ██.██████</text>
      <rect x="360" y="30" width="200" height="100" fill="#b3ac98"/>
      <rect x="360" y="30" width="200" height="100" fill="none" stroke="#4a4437" stroke-width="1.2"/>`,
    relationships: [{ to: 'NX-037-D-05', kind: 'REFERENCE', note: 'Same card number prefix.' }],
  },
  {
    asset: 'frag_nx037_c_07',
    code: 'NX-037-F-07',
    title: 'Archive Shelf Label, Detached',
    description: 'A shelf label in the archive aisle, adhesive still wet on the reverse.',
    type: 'FRAGMENT',
    condition: 'NORMAL',
    state: 'REVIEWED',
    width: 520, height: 200, rotation: 2, seed: 57,
    location: 'RECOVERED — LOC-C101',
    device: 'SHELF LABEL',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 02:50',
    integrity: 'VERIFIED',
    source: 'OBS-02 FIELD RECOVERY',
    material: 'label',
    base: () => `<rect x="20" y="30" width="480" height="140" fill="#e0dac6"/>
      <rect x="20" y="30" width="480" height="140" fill="none" stroke="#8a8271" stroke-width="1"/>
      <text x="36" y="66" font-family="'Arial Narrow',Arial,sans-serif" font-size="12" letter-spacing="2" fill="#5c5546">AISLE 2 · SHELF 4</text>
      <line x1="36" y1="76" x2="484" y2="76" stroke="#8a8271" stroke-width="0.6"/>
      <text x="36" y="108" font-family="'Courier New',monospace" font-size="15" fill="#241f19">NX-037 / OPERATIONS</text>
      <text x="36" y="134" font-family="'Courier New',monospace" font-size="12" fill="#4a4437">BOXES 1-3 SIGNED OUT 09 OCT 94 — NOT RETURNED</text>
      <rect x="40" y="176" width="120" height="16" fill="#c8c2ac" fill-opacity="0.8"/>
      <rect x="360" y="176" width="120" height="16" fill="#c8c2ac" fill-opacity="0.8"/>`,
    relationships: [{ to: 'NX-037-B-03', kind: 'SPATIAL', note: 'Taken from the aisle in this frame.' }],
  },
  {
    asset: 'frag_nx037_c_08',
    code: 'NX-037-F-08',
    title: 'Handwritten Note, Partial',
    description: 'A field note recovered folded in a pocket. Only the lower half survived.',
    type: 'FRAGMENT',
    condition: 'TORN',
    state: 'UNRESOLVED',
    width: 540, height: 300, rotation: -2, seed: 58,
    location: 'RECOVERED — LOC-C214',
    device: 'FIELD NOTE',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 03:59',
    integrity: 'PARTIAL',
    source: 'OBS-02 FIELD RECOVERY',
    material: 'paper',
    base: () => `<line x1="20" y1="150" x2="520" y2="148" stroke="#8fa0a8" stroke-width="0.7" stroke-opacity="0.5"/>
      <line x1="20" y1="182" x2="520" y2="180" stroke="#8fa0a8" stroke-width="0.7" stroke-opacity="0.5"/>
      <line x1="20" y1="214" x2="520" y2="212" stroke="#8fa0a8" stroke-width="0.7" stroke-opacity="0.5"/>
      <line x1="20" y1="246" x2="520" y2="244" stroke="#8fa0a8" stroke-width="0.7" stroke-opacity="0.5"/>
      <text x="30" y="120" font-family="'Segoe Print','Bradley Hand',cursive" font-size="16" fill="#22293a" opacity="0.3">...(upper half lost)</text>
      <text x="30" y="142" font-family="'Segoe Print','Bradley Hand',cursive" font-size="16" fill="#22293a" transform="rotate(-0.6 30 142)">the light is off but the shadows are</text>
      <text x="30" y="174" font-family="'Segoe Print','Bradley Hand',cursive" font-size="16" fill="#22293a" transform="rotate(0.5 30 174)">right. I want that written down before</text>
      <text x="30" y="206" font-family="'Segoe Print','Bradley Hand',cursive" font-size="16" fill="#22293a" transform="rotate(-0.4 30 206)">I stop believing it. Ask Carter where</text>
      <text x="30" y="238" font-family="'Segoe Print','Bradley Hand',cursive" font-size="16" fill="#22293a" transform="rotate(0.7 30 238)">the survey of June went. Ask again on</text>
      <text x="30" y="270" font-family="'Segoe Print','Bradley Hand',cursive" font-size="16" fill="#22293a" transform="rotate(-0.5 30 270)">paper. — A.R.</text>`,
    relationships: [{ to: 'NX-037-F-01', kind: 'REFERENCE', note: 'Both mention the June survey.' }],
  },
  {
    asset: 'frag_nx037_c_09',
    code: 'NX-037-F-09',
    title: 'Floor Plan Fragment, East Wing',
    description: 'A corner of a drawing, cut rather than torn. The room it belongs to is labelled with a code nobody uses.',
    type: 'FRAGMENT',
    condition: 'DAMAGED',
    state: 'FLAGGED',
    width: 660, height: 460, rotation: 3, seed: 59, points: 12, irregularity: 0.24,
    location: 'RECOVERED — LOC-C214',
    device: 'DRAWING',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 04:08',
    integrity: 'DAMAGED',
    source: 'OBS-02 FIELD RECOVERY',
    material: 'plan',
    base: () => `<rect x="20" y="20" width="620" height="420" fill="#ddd8c6"/>
      <g stroke="#2b2a24" fill="none">
        <rect x="60" y="60" width="300" height="200" stroke-width="2.4"/>
        <rect x="380" y="60" width="220" height="200" stroke-width="2.4"/>
        <rect x="60" y="280" width="540" height="130" stroke-width="2.4"/>
        <line x1="300" y1="60" x2="300" y2="160" stroke-width="1.2"/>
        <line x1="300" y1="240" x2="300" y2="280" stroke-width="1.2"/>
        <path d="M 300 160 A 80 80 0 0 1 220 240" stroke-width="0.9"/>
      </g>
      <text x="210" y="170" text-anchor="middle" font-family="'Arial Narrow',Arial,sans-serif" font-size="12" letter-spacing="1.4" fill="#2b2a24">E. CORRIDOR</text>
      <text x="210" y="188" text-anchor="middle" font-family="'Courier New',monospace" font-size="10" fill="#5c5546">C214</text>
      <text x="490" y="170" text-anchor="middle" font-family="'Arial Narrow',Arial,sans-serif" font-size="12" letter-spacing="1.4" fill="#2b2a24">ROOM</text>
      <text x="490" y="188" text-anchor="middle" font-family="'Courier New',monospace" font-size="10" fill="#5c5546">C214-X</text>
      <text x="330" y="360" text-anchor="middle" font-family="'Arial Narrow',Arial,sans-serif" font-size="11" letter-spacing="1.2" fill="#2b2a24">N. STAIR</text>
      <text x="60" y="440" font-family="'Courier New',monospace" font-size="9" fill="#5c5546">A-201-G · ISSUE 02 · NO ROOM C214-X ON ISSUE 03</text>
      <path d="M 400 120 L 560 120 L 560 220 L 400 220 Z" fill="none" stroke="#a8322a" stroke-width="2.4" stroke-dasharray="8 5"/>
      <text x="480" y="108" text-anchor="middle" font-family="'Arial Narrow',Arial,sans-serif" font-size="10" fill="#a8322a">ADDED IN PENCIL</text>`,
    relationships: [
      { to: 'NX-037-M-02', kind: 'REFERENCE', note: 'The current drawing has no C214-X.' },
      { to: 'NX-CAM-07', kind: 'SPATIAL', note: 'The marked room contains the CAM-07 mount point.' },
    ],
  },
  {
    asset: 'frag_nx037_c_10',
    code: 'NX-037-F-10',
    title: 'Personnel Record, Detached Page',
    description: 'The endorsement page of a personnel file, torn out at the staple.',
    type: 'FRAGMENT',
    condition: 'TORN',
    state: 'UNRESOLVED',
    width: 560, height: 420, rotation: -5, seed: 60,
    location: 'RECOVERED — LOC-C101',
    device: 'FILE PAGE',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 04:10',
    integrity: 'PARTIAL',
    source: 'OBS-02 FIELD RECOVERY',
    material: 'paper',
    stamp: 'ENDORSEMENT',
    stampX: 330, stampY: 60,
    base: () => `<text x="36" y="56" font-family="'Arial Narrow',Arial,sans-serif" font-size="11" letter-spacing="2" fill="#3c362c">HALDER INSTITUTE — ENDORSEMENTS (CONT.)</text>
      <line x1="36" y1="66" x2="524" y2="66" stroke="#3c362c" stroke-width="0.9"/>
      ${fragText([
        'L.V.-0029  VEY, LINA M.',
        '',
        '04 OCT 94   REASSIGNED EAST WING ACCESS',
        '            EFFECTIVE IMMEDIATELY.',
        '            SIGNED  M. CARTER',
        '',
        '            NOTE: SUBJECT REQUESTS THAT',
        '            HER ACCESS BE WITHDRAWN',
        '            FROM THE EAST CORRIDOR PENDING',
        '            REVIEW. DECLINED.',
      ], { x: 36, y: 96, size: 12, leading: 21 })}`,
    relationships: [
      { to: 'NX-037-P-01', kind: 'PERSONNEL', note: 'The same personnel number.' },
      { to: 'NX-037-F-04', kind: 'CONTRADICTION', note: 'Dated the day the camera was re-aimed.' },
    ],
  },
]

/* ───────────────────────────────── maps ───────────────────────────────── */

export const MAPS = [
  {
    asset: 'map_admin_ground_a201g',
    code: 'NX-037-M-01',
    title: 'Admin Building, Ground Floor — A-201-G',
    description: 'The drawing of record. Issue 03. Everything in the case sits on this sheet.',
    type: 'MAP',
    condition: 'NORMAL',
    state: 'VERIFIED',
    seed: 61,
    sheetTitle: 'ADMIN BUILDING — GROUND FLOOR',
    dwg: 'A-201-G',
    issue: '03',
    issueDate: 'MAR 94',
    control: 'DWG A-201-G ISSUE 03',
    location: 'FACILITIES ENGINEERING',
    device: 'DRAWING / REPROGRAPH',
    capturedAt: 'MAR 94',
    acquiredAt: '19 OCT 94 12:02',
    integrity: 'VERIFIED',
    source: 'FACILITIES ENGINEERING',
    rooms: [
      { x: 90, y: 90, w: 300, h: 230, label: 'CENTRAL ARCHIVE', code: 'C101', door: { side: 'bottom', x: 200 }, window: true, hatch: true },
      { x: 410, y: 90, w: 240, h: 230, label: 'ARCHIVE OFFICE', code: 'C101A', door: { side: 'bottom', x: 500 } },
      { x: 670, y: 90, w: 380, h: 230, label: 'EAST CORRIDOR', code: 'C214', door: { side: 'bottom', x: 760 }, note: 'OBSERVED EMPTY 14 OCT 94' },
      { x: 90, y: 350, w: 300, h: 210, label: 'PLANT / SUB-BASEMENT', code: 'S01', door: { side: 'top', x: 200 }, hatch: true },
      { x: 410, y: 350, w: 240, h: 210, label: 'EQUIPMENT ROOM', code: 'C305', door: { side: 'top', x: 500 } },
      { x: 670, y: 350, w: 380, h: 210, label: 'N. STAIRWELL', code: 'C118', door: { side: 'top', x: 800 }, window: true },
    ],
    cameras: [
      { x: 200, y: 150, label: 'CAM-02' },
      { x: 520, y: 150, label: 'CAM-04' },
      { x: 800, y: 140, label: 'CAM-07' },
    ],
    marked: true,
    markX: 670, markY: 90, markW: 380, markH: 230,
    markLabel: 'EAST CORRIDOR — DISPUTED SEGMENT',
    relationships: [
      { to: 'NX-CAM-07', kind: 'SPATIAL', note: 'CAM-07 shown at the north end of C214.' },
      { to: 'NX-037-F-09', kind: 'CONTRADICTION', note: 'Issue 03 has no room C214-X.' },
    ],
  },
  {
    asset: 'map_east_wing_issue02',
    code: 'NX-037-M-02',
    title: 'Admin Building, Ground Floor — A-201-G ISSUE 02',
    description: 'The superseded issue. It contains a room that the current drawing no longer has.',
    type: 'MAP',
    condition: 'FADED',
    state: 'CONTRADICTED',
    seed: 62,
    sheetTitle: 'ADMIN BUILDING — GROUND FLOOR',
    dwg: 'A-201-G',
    issue: '02',
    issueDate: 'AUG 91',
    control: 'SUPERSEDED — NOT FOR CONSTRUCTION',
    location: 'FACILITIES ENGINEERING',
    device: 'DRAWING / REPROGRAPH',
    capturedAt: 'AUG 91',
    acquiredAt: '19 OCT 94 12:06',
    integrity: 'PARTIAL',
    source: 'FACILITIES ENGINEERING',
    rooms: [
      { x: 90, y: 90, w: 300, h: 230, label: 'CENTRAL ARCHIVE', code: 'C101', door: { side: 'bottom', x: 200 }, window: true, hatch: true },
      { x: 410, y: 90, w: 240, h: 230, label: 'ARCHIVE OFFICE', code: 'C101A', door: { side: 'bottom', x: 500 } },
      { x: 670, y: 90, w: 380, h: 120, label: 'EAST CORRIDOR', code: 'C214', door: { side: 'bottom', x: 760 } },
      { x: 670, y: 230, w: 180, h: 90, label: 'ROOM C214-X', code: 'C214-X', door: { side: 'bottom', x: 740 }, note: 'NO OPENING SHOWN ON ISSUE 03' },
      { x: 870, y: 230, w: 180, h: 90, label: 'PLANT C208', code: 'C208', door: { side: 'bottom', x: 940 } },
      { x: 90, y: 350, w: 300, h: 210, label: 'PLANT / SUB-BASEMENT', code: 'S01', door: { side: 'top', x: 200 }, hatch: true },
      { x: 410, y: 350, w: 240, h: 210, label: 'EQUIPMENT ROOM', code: 'C305', door: { side: 'top', x: 500 } },
      { x: 670, y: 350, w: 380, h: 210, label: 'N. STAIRWELL', code: 'C118', door: { side: 'top', x: 800 }, window: true },
    ],
    cameras: [{ x: 800, y: 140, label: 'CAM-07' }],
    marked: true,
    markX: 670, markY: 230, markW: 180, markH: 90,
    markLabel: 'ROOM PRESENT ON ISSUE 02 ONLY',
    relationships: [
      { to: 'NX-037-M-01', kind: 'CONTRADICTION', note: 'The current issue omits C214-X.' },
      { to: 'NX-037-F-09', kind: 'REFERENCE', note: 'The fragment is cut from this sheet.' },
    ],
  },
  {
    asset: 'map_science_lab_c202',
    code: 'NX-037-M-03',
    title: 'Science Wing, Laboratory Level — S-114',
    description: 'Bench layout for Labs 01 to 06, including the bench the case keeps returning to.',
    type: 'MAP',
    condition: 'NORMAL',
    state: 'REVIEWED',
    seed: 63,
    sheetTitle: 'SCIENCE WING — LABORATORY LEVEL',
    dwg: 'S-114',
    issue: '04',
    issueDate: 'JAN 93',
    control: 'DWG S-114 ISSUE 04',
    location: 'FACILITIES ENGINEERING',
    device: 'DRAWING / REPROGRAPH',
    capturedAt: 'JAN 93',
    acquiredAt: '19 OCT 94 12:10',
    integrity: 'VERIFIED',
    source: 'FACILITIES ENGINEERING',
    rooms: [
      { x: 90, y: 90, w: 260, h: 200, label: 'LAB 01', code: 'C201', door: { side: 'bottom', x: 190 } },
      { x: 370, y: 90, w: 260, h: 200, label: 'LAB 02', code: 'C202A', door: { side: 'bottom', x: 470 } },
      { x: 650, y: 90, w: 260, h: 200, label: 'LAB 04', code: 'C202', door: { side: 'bottom', x: 750 }, note: 'L.V.-0029' },
      { x: 90, y: 320, w: 260, h: 200, label: 'LAB 05', code: 'C203', door: { side: 'top', x: 190 } },
      { x: 370, y: 320, w: 260, h: 200, label: 'LECTURE 214', code: 'C214H', door: { side: 'top', x: 470 }, window: true },
      { x: 650, y: 320, w: 260, h: 200, label: 'FUME STORE', code: 'C207', door: { side: 'top', x: 750 }, hatch: true },
    ],
    cameras: [{ x: 750, y: 150, label: 'CAM-05' }],
    marked: true,
    markX: 650, markY: 90, markW: 260, markH: 200,
    markLabel: 'BENCH 4 — ASSIGNED L.V.-0029',
    relationships: [{ to: 'NX-037-P-01', kind: 'PERSONNEL', note: 'Confirms the bench assignment.' }],
  },
  {
    asset: 'map_subbasement_s01',
    code: 'NX-037-M-04',
    title: 'Sub-Basement Plant Level — S-001',
    description: 'The service level under the east wing. The tape route runs through it.',
    type: 'MAP',
    condition: 'DAMAGED',
    state: 'FLAGGED',
    seed: 64,
    damageKind: 'STAIN',
    stainX: 0.2, stainY: 0.72,
    sheetTitle: 'ADMIN BUILDING — SUB-BASEMENT',
    dwg: 'S-001',
    issue: '02',
    issueDate: 'MAR 78',
    control: 'DWG S-001 ISSUE 02',
    location: 'FACILITIES ENGINEERING',
    device: 'DRAWING / REPROGRAPH',
    capturedAt: 'MAR 78',
    acquiredAt: '19 OCT 94 12:14',
    integrity: 'DAMAGED',
    source: 'FACILITIES ENGINEERING',
    rooms: [
      { x: 90, y: 90, w: 420, h: 220, label: 'PLANT ROOM', code: 'S01', hatch: true, door: { side: 'bottom', x: 280 } },
      { x: 530, y: 90, w: 260, h: 220, label: 'VALVE TREE', code: 'S01-V', door: { side: 'bottom', x: 640 } },
      { x: 810, y: 90, w: 240, h: 220, label: 'TAPE ROUTE', code: 'S01-T', note: 'ADDED ISSUE 02' },
      { x: 90, y: 340, w: 560, h: 190, label: 'DUCT RUN', code: 'S01-D', hatch: true },
      { x: 670, y: 340, w: 380, h: 190, label: 'BRAZIER', code: 'S01-B', door: { side: 'top', x: 840 } },
    ],
    cameras: [{ x: 700, y: 160, label: 'CAM-06' }],
    marked: true,
    markX: 810, markY: 90, markW: 240, markH: 220,
    markLabel: 'TAPE ROUTE ENTERS AT THIS POINT',
    relationships: [
      { to: 'NX-037-F-05', kind: 'SPATIAL', note: 'The brazier is where the burnt fragment came from.' },
      { to: 'NX-037-D-04', kind: 'REFERENCE', note: 'The memo puts the tape route through here.' },
    ],
  },
  {
    asset: 'map_tower_section_t7',
    code: 'NX-037-M-05',
    title: 'Clock Tower, Vertical Section — T-7',
    description: "A section through the tower. The clock movement is annotated in a hand that is not the draughtsman's.",
    type: 'MAP',
    condition: 'NORMAL',
    state: 'REVIEWED',
    seed: 65,
    sheet: 'blueprint',
    sheetTitle: 'CLOCK TOWER — SECTION',
    dwg: 'T-7',
    issue: '01',
    issueDate: 'JUN 74',
    control: 'BLUEPRINT T-7',
    location: 'FACILITIES ENGINEERING',
    device: 'CYANOTYPE',
    capturedAt: 'JUN 74',
    acquiredAt: '19 OCT 94 12:18',
    integrity: 'VERIFIED',
    source: 'FACILITIES ENGINEERING',
    rooms: [
      { x: 300, y: 90, w: 260, h: 150, label: 'MOVEMENT', code: 'T7-04' },
      { x: 300, y: 260, w: 260, h: 120, label: 'FACE', code: 'T7-03' },
      { x: 300, y: 400, w: 260, h: 130, label: 'BASE / MECHANISM', code: 'T7-01' },
      { x: 90, y: 90, w: 180, h: 440, label: 'SHAFT', code: 'T7-S' },
      { x: 590, y: 90, w: 400, h: 440, label: 'VOID', code: 'T7-V', hatch: true, note: 'NO ACCESS SHOWN' },
    ],
    marked: true,
    markX: 590, markY: 90, markW: 400, markH: 440,
    markLabel: 'ACCESS NOT ON THIS ISSUE',
    relationships: [{ to: 'NX-037-D-09', kind: 'TEMPORAL', note: 'The clock is the case\'s other recurring time reference.' }],
  },
]

/* ───────────────────────────── personnel ───────────────────────────── */

export const PERSONNEL = [
  {
    asset: 'personnel_lv_0029',
    code: 'NX-037-P-01',
    title: 'Personnel Record — L.V.-0029',
    description: 'The file for the project lead. Every endorsement is in someone else\'s hand.',
    type: 'PERSONNEL',
    condition: 'NORMAL',
    state: 'REVIEWED',
    seed: 71,
    ...PERSONNEL_ROSTER['L.V.-0029'],
    name: 'VEY, LINA MARGARET',
    personnelId: 'L.V.-0029',
    role: 'PROJECT LEAD / MEMORY RESEARCH',
    location: 'LAB 04 / EAST WING ACCESS',
    device: 'FILED FORM P-1',
    capturedAt: '1994',
    acquiredAt: '19 OCT 94 12:44',
    integrity: 'VERIFIED',
    source: 'PERSONNEL FILE',
    history: [
      ['SEP 81', 'PRESENT', 'RESEARCH ASSISTANT', 'LAB 01'],
      ['MAR 86', 'NOV 89', 'RESEARCH OFFICER', 'LAB 02'],
      ['NOV 89', 'SEP 93', 'SENIOR RESEARCHER', 'LAB 04'],
      ['SEP 93', 'PRESENT', 'PROJECT LEAD / NEXUS', 'LAB 04'],
    ],
    endorsements: [
      ['M. Carter, Deputy Lead', 'ENDORSED 04 OCT 94'],
      ['N. Rahal, Observation', 'NO OBJECTION 06 OCT 94'],
      ['▮▮▮▮▮ (unsigned)', 'NO DATE — STAPLE TORN'],
    ],
    filed: 'FILE OPEN',
    relationships: [
      { to: 'NX-037-F-10', kind: 'REFERENCE', note: 'The torn endorsement page is hers.' },
      { to: 'NX-037-D-03', kind: 'PERSONNEL', note: 'Her credential is in the export.' },
    ],
  },
  {
    asset: 'personnel_mc_0114',
    code: 'NX-037-P-02',
    title: 'Personnel Record — M.C.-0114',
    description: 'The deputy lead. His file is the shortest of the four and the only one that is fully closed.',
    type: 'PERSONNEL',
    condition: 'NORMAL',
    state: 'REVIEWED',
    seed: 72,
    name: 'CARTER, MARCUS A.',
    personnelId: 'M.C.-0114',
    role: 'DEPUTY LEAD / SYSTEM THEORY',
    unit: 'SYSTEM THEORY',
    grade: 'RESEARCH GRADE 3',
    access: 'LEVEL 3 — LAB 02',
    appointed: '02 FEB 1986',
    dob: '30 APR 1949',
    location: 'LAB 02',
    device: 'FILED FORM P-1',
    capturedAt: '1994',
    acquiredAt: '19 OCT 94 12:48',
    integrity: 'VERIFIED',
    source: 'PERSONNEL FILE',
    history: [
      ['FEB 86', 'JUN 90', 'RESEARCHER', 'LAB 02'],
      ['JUN 90', 'PRESENT', 'DEPUTY LEAD / NEXUS', 'LAB 02'],
    ],
    endorsements: [
      ['L. Vey, Project Lead', 'ENDORSED 02 FEB 86'],
      ['Internal Operations', 'ENDORSED 04 OCT 94'],
    ],
    closedStamp: 'TRANSFERRED',
    filed: 'CLOSED 12 OCT 94',
    relationships: [
      { to: 'NX-037-D-04', kind: 'PERSONNEL', note: 'He signed the east wing memo.' },
      { to: 'NX-037-D-09', kind: 'PERSONNEL', note: 'The reshot frame was ordered by him.' },
    ],
  },
  {
    asset: 'personnel_nr_0471',
    code: 'NX-037-P-03',
    title: 'Personnel Record — N.R.-0471',
    description: 'The officer who opened the incident record. Her photograph was taken on a different day to her file.',
    type: 'PERSONNEL',
    condition: 'NORMAL',
    state: 'UNREVIEWED',
    seed: 73,
    name: 'RAHAL, NOOR',
    personnelId: 'N.R.-0471',
    role: 'FIELD OBSERVATION',
    unit: 'SECURITY / OBSERVATION',
    grade: 'OFFICER GRADE 2',
    access: 'ALL EXTERIOR — CAM READ',
    appointed: '19 MAY 1992',
    dob: '04 SEP 1968',
    location: 'OBSERVATION POST 3',
    device: 'FILED FORM P-1',
    capturedAt: '1994',
    acquiredAt: '19 OCT 94 12:52',
    integrity: 'VERIFIED',
    source: 'PERSONNEL FILE',
    history: [
      ['MAY 92', 'PRESENT', 'OBSERVATION OFFICER', 'POST 3'],
    ],
    endorsements: [
      ['M. Carter, Deputy Lead', 'ENDORSED 19 MAY 92'],
      ['A. R. (handwriting)', 'JOINT OPERATION 14 OCT 94'],
    ],
    filed: 'FILE OPEN',
    relationships: [{ to: 'NX-037-D-01', kind: 'PERSONNEL', note: 'She signed the incident record.' }],
  },
  {
    asset: 'personnel_ms_0388',
    code: 'NX-037-P-04',
    title: 'Personnel Record — M.S.-0388',
    description: 'The archivist. Her file carries an access endorsement for the east wing that was never signed by the holder.',
    type: 'PERSONNEL',
    condition: 'DAMAGED',
    state: 'FLAGGED',
    seed: 74,
    damageKind: 'MISSING',
    missingY: 0.52,
    missingH: 0.05,
    name: 'SELIM, MARA',
    personnelId: 'M.S.-0388',
    role: 'ARCHIVIST',
    unit: 'CENTRAL ARCHIVE',
    grade: 'ADMIN GRADE 3',
    access: 'LEVEL 1 — ARCHIVE',
    appointed: '08 JAN 1989',
    dob: '22 NOV 1961',
    location: 'CENTRAL ARCHIVE / DESK 04',
    device: 'FILED FORM P-1',
    capturedAt: '1994',
    acquiredAt: '19 OCT 94 12:56',
    integrity: 'PARTIAL',
    source: 'PERSONNEL FILE',
    history: [
      ['JAN 89', 'MAR 91', 'CLERK', 'ARCHIVE'],
      ['MAR 91', 'PRESENT', 'ARCHIVIST', 'ARCHIVE'],
    ],
    endorsements: [
      ['M.S.0388 (self)', 'EAST WING ACCESS — NOT COUNTERSIGNED'],
      ['▮▮▮▮', 'PAGE MISSING FROM FILE'],
    ],
    badgeHeight: true,
    filed: 'FILE OPEN',
    relationships: [{ to: 'NX-037-B-10', kind: 'SPATIAL', note: 'Desk 04 in the archive office.' }],
  },
  {
    asset: 'personnel_lv_0029_duplicate',
    code: 'NX-037-P-05',
    title: 'Personnel Record — L.V.-0029 (DUPLICATE)',
    description: 'A second file for the same number. Its control number appears inside its own contents, and its dates are impossible.',
    type: 'PERSONNEL',
    condition: 'ANOMALOUS',
    state: 'ANOMALOUS',
    seed: 75,
    name: 'VEY, LINA MARGARET',
    personnelId: 'L.V.-0029',
    role: 'PROJECT LEAD / MEMORY RESEARCH',
    unit: 'MEMORY RESEARCH',
    grade: 'RESEARCH GRADE 4',
    access: 'LEVEL 3 — LAB 04',
    appointed: '17 APR 98',
    dob: '11 JUN 1954',
    location: 'LAB 04',
    device: 'FILED FORM P-1',
    capturedAt: '17 APR 98',
    acquiredAt: '19 OCT 94 13:04',
    integrity: 'CONTRADICTED',
    source: 'PERSONNEL FILE / ANOMALOUS',
    stamp: 'DO NOT FILE',
    revision: 'REV 00',
    history: [
      ['APR 98', 'PRESENT', 'PROJECT LEAD / NEXUS', 'LAB 04'],
      ['APR 98', 'PRESENT', 'PROJECT LEAD / NEXUS', 'LAB 04'],
    ],
    endorsements: [
      ['L. Vey, Project Lead', 'ENDORSED 17 APR 98'],
      ['▮▮▮▮', 'CONTROL NX-037-P-05 — SELF-REFERENTIAL'],
    ],
    anomalous: true,
    filed: 'FILED 19 OCT 94 BY ORDER',
    relationships: [
      { to: 'NX-037-P-01', kind: 'CONTRADICTION', note: 'Same number, different appointment date.' },
      { to: 'NX-037-D-01', kind: 'TEMPORAL', note: '17 APR 98 is the case\'s other impossible date.' },
    ],
  },
  {
    asset: 'personnel_d_wright_unestablished',
    code: 'NX-037-P-06',
    title: 'Personnel Record — D. WRIGHT (NOT ON ESTABLISHMENT)',
    description: 'A file opened for a person the Institute has no record of employing. The surname is legible; everything that would identify the holder is not.',
    type: 'PERSONNEL',
    condition: 'INCOMPLETE',
    state: 'UNRESOLVED',
    seed: 76,
    damageKind: 'MISSING',
    missingY: 0.44,
    missingH: 0.16,
    name: 'WRIGHT, D.',
    personnelId: 'NO ID ASSIGNED',
    role: 'NOT ESTABLISHED',
    unit: 'FACILITIES ENGINEERING (UNVERIFIED)',
    grade: 'NOT ESTABLISHED',
    access: 'NOT ESTABLISHED',
    appointed: 'NOT ESTABLISHED',
    dob: 'NOT ESTABLISHED',
    location: 'SECTOR C / PLANT ROOM',
    device: 'FILED FORM P-1',
    capturedAt: '14 OCT 94',
    acquiredAt: '19 OCT 94 13:11',
    integrity: 'INCOMPLETE',
    source: 'UNASSIGNED FILE / FOUND IN SECTOR C',
    stamp: 'NO SUCH PERSON',
    revision: 'REV 00',
    history: [
      ['NOT ESTABLISHED', 'NOT ESTABLISHED', 'NOT ESTABLISHED', 'SECTOR C'],
    ],
    endorsements: [
      ['D. WRIGHT', 'ORDER GIVEN 03:17 — NOT COUNTERSIGNED'],
      ['▮▮▮▮', 'IDENTIFYING PAGE NOT IN FILE'],
    ],
    filed: 'FILE OPEN — NO HOLDER',
    relationships: [
      { to: 'NX-037-F-04', kind: 'REFERENCE', note: 'The name this file was opened for.' },
      { to: 'NX-037-A-05', kind: 'TEMPORAL', note: 'Named at the same minute on the same tape.' },
      { to: 'NX-037-D-02', kind: 'REFERENCE', note: 'Signed the sector C ledger by order.' },
    ],
  },
]

/* ─────────────────────────────── notes ─────────────────────────────── */

export const NOTES = [
  {
    asset: 'note_observer02_01',
    code: 'NX-037-N-01',
    title: 'Field Observation Sheet 1 — OBS-02',
    description: 'The observation team\'s own sheet, in order, with times that line up with everything else.',
    type: 'NOTE',
    condition: 'NORMAL',
    state: 'REVIEWED',
    seed: 81,
    header: 'FIELD OBSERVATION — SHEET 1',
    headerRef: 'OBS-02 / 037',
    timeLine: '14 OCT 94 — 01:30 TO 02:30',
    handSize: 15,
    location: 'SUB-BASEMENT / EAST WING',
    device: 'FIELD BOOK',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 02:36',
    integrity: 'VERIFIED',
    source: 'OBS-02',
    lines: [
      '01:30 down. Brazier is lit in the sub. Not',
      'on any schedule I have. Sheet in the ash,',
      'mostly gone.',
      '01:48 valve tree. One valve closed and',
      're-marked in grease pencil. Someone did',
      'this to be found.',
      '02:20 lab 4. Benches cleared. Whiteboard',
      'still has the sums from last week. Nobody',
      'wiped a board in this building for a year.',
    ],
    relationships: [{ to: 'NX-037-F-05', kind: 'SPATIAL', note: 'The burnt sheet is logged here.' }],
  },
  {
    asset: 'note_observer02_02',
    code: 'NX-037-N-02',
    title: 'Field Observation Sheet 2 — OBS-02',
    description: 'The sheet that stops in the middle of a line. The last entry is about the corridor.',
    type: 'NOTE',
    condition: 'NORMAL',
    state: 'FLAGGED',
    seed: 82,
    header: 'FIELD OBSERVATION — SHEET 2',
    headerRef: 'OBS-02 / 037',
    timeLine: '14 OCT 94 — 02:30 TO 03:41',
    location: 'EAST CORRIDOR',
    device: 'FIELD BOOK',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 03:46',
    integrity: 'VERIFIED',
    source: 'OBS-02',
    lines: [
      '02:41 archive. Aisle 2 pulled, boxes 1-3 out',
      'and stacked. Label still on the shelf.',
      '02:58 stair. Rail wiped. Damp on the wall is',
      'newer than the paint.',
      '03:12 corridor. Dark from the archive door to',
      'the north stair. I have the flash with me',
      'and I am not using it.',
      '03:17 —',
    ],
    sketch: () => `<g opacity="0.7" transform="translate(340 640)">
      <rect x="0" y="0" width="330" height="180" fill="none" stroke="#22293a" stroke-width="1.6"/>
      <line x1="0" y1="120" x2="330" y2="120" stroke="#22293a" stroke-width="1.2"/>
      <line x1="60" y1="120" x2="80" y2="0" stroke="#22293a" stroke-width="1.2"/>
      <line x1="230" y1="120" x2="212" y2="0" stroke="#22293a" stroke-width="1.2"/>
      <circle cx="150" cy="150" r="16" fill="none" stroke="#22293a" stroke-width="1.6"/>
      <text x="0" y="-8" font-family="'Segoe Print','Bradley Hand',cursive" font-size="13" fill="#22293a">C214 — after 03:17</text>
      <text x="150" y="112" text-anchor="middle" font-family="'Segoe Print','Bradley Hand',cursive" font-size="12" fill="#22293a">me</text>
    </g>`,
    relationships: [
      { to: 'NX-037-B-02', kind: 'TEMPORAL', note: 'The frame is taken at the line where the note stops.' },
      { to: 'NX-037-F-08', kind: 'REFERENCE', note: 'The torn note is the rest of this page.' },
    ],
  },
  {
    asset: 'note_observer02_03',
    code: 'NX-037-N-03',
    title: 'Field Observation Sheet 3 — OBS-02',
    description: 'Written after the corridor, back in the entrance. The handwriting changes.',
    type: 'NOTE',
    condition: 'DAMAGED',
    state: 'UNRESOLVED',
    seed: 83,
    damageKind: 'STAIN',
    stainX: 0.7, stainY: 0.35,
    header: 'FIELD OBSERVATION — SHEET 3',
    headerRef: 'OBS-02 / 037',
    timeLine: '14 OCT 94 — 03:41 TO 04:40',
    location: 'MAIN ENTRANCE',
    device: 'FIELD BOOK',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 04:38',
    integrity: 'DAMAGED',
    source: 'OBS-02',
    lines: [
      '03:41 out. Doors still chained from the',
      'inside. I did not chain them. I want that',
      'written while I still trust my hands.',
      '03:52 I have eleven prints and one of them',
      'is wet.',
      '03:55 asking Carter about the June survey.',
      'He was not on the establish in June. He has',
      'not been on the establish since February.',
      'I am going to write that down again so I',
      'cannot unwrite it.',
    ],
    relationships: [
      { to: 'NX-037-P-02', kind: 'PERSONNEL', note: 'The name the note could not resolve.' },
      { to: 'NX-037-F-01', kind: 'REFERENCE', note: 'The torn section mentions the same survey.' },
    ],
  },
  {
    asset: 'note_archivist_04',
    code: 'NX-037-N-04',
    title: 'Archivist Note — M.S.-0388',
    description: 'A note left inside a file, addressed to whoever reads the box next.',
    type: 'NOTE',
    condition: 'NORMAL',
    state: 'REVIEWED',
    seed: 84,
    ruled: true,
    header: 'ARCHIVE DESK 04',
    headerRef: 'M.S.-0388',
    timeLine: 'OCT 94 — UNDATED',
    handSize: 14,
    location: 'CENTRAL ARCHIVE',
    device: 'FILE NOTE',
    capturedAt: 'OCT 94',
    acquiredAt: '19 OCT 94 13:20',
    integrity: 'VERIFIED',
    source: 'M.S.-0388',
    lines: [
      'Whoever picks this box up: the operations',
      'files for the east wing are NOT in the',
      'register. They are in aisle 2, shelf 4, and',
      'they were signed out on 9 October and never',
      'came back.',
      'I have signed them out again myself. I am',
      'not going to explain that in writing.',
    ],
    relationships: [{ to: 'NX-037-F-07', kind: 'REFERENCE', note: 'Names the shelf label exactly.' }],
  },
  {
    asset: 'note_index_card_maintenance',
    code: 'NX-037-N-05',
    title: 'Index Card — Camera Schedule',
    description: 'A card-index card. The card below it in the drawer is blank and not marked as withdrawn.',
    type: 'NOTE',
    condition: 'NORMAL',
    state: 'UNREVIEWED',
    seed: 85,
    ruled: false,
    width: 620, height: 400,
    header: 'CARD INDEX — C',
    headerRef: 'CAM',
    timeLine: '',
    handSize: 15,
    location: 'CENTRAL ARCHIVE',
    device: 'INDEX CARD',
    capturedAt: '1994',
    acquiredAt: '19 OCT 94 13:24',
    integrity: 'VERIFIED',
    source: 'CENTRAL ARCHIVE',
    tone: '#e6e0cc',
    lines: [
      'CAM-07',
      '',
      'Location  C214 east corridor, north end',
      'Fitted   06 JUN 94',
      'Re-aimed 12 OCT 94  (no operator signed)',
      'Removed  —',
      '',
      'see also  C214-X',
    ],
    relationships: [
      { to: 'NX-037-F-02', kind: 'REFERENCE', note: 'The asset label carries the same re-aim date.' },
      { to: 'NX-037-M-02', kind: 'SPATIAL', note: 'C214-X exists only on issue 02.' },
    ],
  },
  {
    asset: 'note_marginalia_d01',
    code: 'NX-037-N-06',
    title: 'Marginalia — Incident Record 037',
    description: 'Written in the margin of a filed record, in a different hand from the record.',
    type: 'NOTE',
    condition: 'NORMAL',
    state: 'FLAGGED',
    seed: 86,
    ruled: true,
    header: 'MARGIN — IR-037-04',
    headerRef: 'HAND NOT ON FILE',
    timeLine: 'UNDATED',
    handSize: 13,
    location: 'CASE FILE NX-037',
    device: 'FILED DOCUMENT',
    capturedAt: 'OCT 94',
    acquiredAt: '19 OCT 94 13:28',
    integrity: 'VERIFIED',
    source: 'UNKNOWN HAND',
    lines: [
      '§2 lists four items. Only three were ever',
      'printed. The fourth is a person.',
      '',
      '— the surveyor is not missing. The surveyor',
      'was never appointed.',
    ],
    relationships: [{ to: 'NX-037-D-01', kind: 'REFERENCE', note: 'Written on the incident record.' }],
  },
  {
    asset: 'note_tape_route',
    code: 'NX-037-N-07',
    title: 'Maintenance Scrawl — Tape Route',
    description: 'A scrap of repair-room paper, in pencil, with a diagram that does not match any drawing on file.',
    type: 'NOTE',
    condition: 'DAMAGED',
    state: 'UNRESOLVED',
    seed: 87,
    damageKind: 'BURNED',
    burnX: 0.86, burnY: 0.9, burnR: 0.2,
    ruled: false,
    width: 640, height: 420,
    header: 'REPAIR ROOM — SCRAP',
    headerRef: 'TAPE 7',
    timeLine: '',
    handSize: 14,
    location: 'FACILITIES',
    device: 'SCRAP PAPER',
    capturedAt: 'OCT 94',
    acquiredAt: '19 OCT 94 13:32',
    integrity: 'DAMAGED',
    source: 'TECH-11',
    tone: '#d9d3c0',
    lines: [
      'tape 7 goes down the shaft, not the duct.',
      'if it goes down the duct it writes over',
      'tape 6 and node b-04 will not notice',
      'for four days.',
      '',
      '— nobody asked me to move it. I moved it',
      'because the duct was full.',
    ],
    sketch: () => `<g opacity="0.6" transform="translate(40 300)">
      <line x1="0" y1="0" x2="0" y2="70" stroke="#22293a" stroke-width="1.4"/>
      <line x1="0" y1="70" x2="520" y2="70" stroke="#22293a" stroke-width="1.4"/>
      <path d="M 0 8 C 60 8 80 60 140 66 L 380 66" fill="none" stroke="#a8322a" stroke-width="1.8" stroke-dasharray="6 4"/>
      <text x="150" y="56" font-family="'Segoe Print','Bradley Hand',cursive" font-size="12" fill="#a8322a">TAPE 7 (MOVED)</text>
      <path d="M 0 40 C 80 40 120 66 200 68 L 380 68" fill="none" stroke="#22293a" stroke-width="1.2"/>
      <text x="200" y="88" font-family="'Segoe Print','Bradley Hand',cursive" font-size="12" fill="#22293a">TAPE 6 (AS DRAWN)</text>
      <text x="0" y="-8" font-family="'Segoe Print','Bradley Hand',cursive" font-size="12" fill="#22293a">C214</text>
      <text x="480" y="88" font-family="'Segoe Print','Bradley Hand',cursive" font-size="12" fill="#22293a">S01</text>
      <circle cx="300" cy="40" r="3" fill="#22293a"/>
    </g>`,
    relationships: [
      { to: 'NX-037-M-04', kind: 'SPATIAL', note: 'The drawing does not match this diagram.' },
      { to: 'NX-CAM-07', kind: 'SOURCE', note: 'Explains the missing interval on tape 7.' },
    ],
  },
  {
    asset: 'note_roster_sheet',
    code: 'NX-037-N-08',
    title: 'Establish List, East Wing',
    description: 'A typed list of who is supposed to be in the wing after hours. Six names. One line is struck through and the ink has been gone over.',
    type: 'NOTE',
    condition: 'NORMAL',
    state: 'FLAGGED',
    seed: 88,
    ruled: true,
    header: 'EAST WING — AFTER HOURS',
    headerRef: 'OPS/EW 94',
    timeLine: 'OCT 94',
    handSize: 14,
    location: 'OPERATIONS',
    device: 'FILED LIST',
    capturedAt: 'OCT 94',
    acquiredAt: '19 OCT 94 13:36',
    integrity: 'QUESTIONED',
    source: 'INTERNAL OPERATIONS',
    lines: [
      ' 1  L. VEY ............ research / any night',
      ' 2  M. CARTER ......... by exception only',
      ' 3  M. SELIM .......... archive, no east wing',
      ' 4  N. RAHAL .......... observation, paired',
      ' 5  TECH-11 ........... plant room, call-out',
      ' 6  ▮▮▮▮▮▮▮▮▮▮ ...... ▮▮▮▮▮▮▮▮▮▮▮▮▮▮',
      '',
      'Item 3 endorsed by M.C.0114, 04 OCT 94,',
      'against the standing instruction of 22 AUG 94.',
      'The endorsement is in the file. The list in',
      'the wing has been amended to match.',
    ],
    relationships: [
      { to: 'NX-037-P-04', kind: 'PERSONNEL', note: 'Item 3 is the archivist.' },
      { to: 'NX-037-P-02', kind: 'PERSONNEL', note: 'Item 2 is the deputy lead.' },
    ],
  },
  {
    asset: 'note_burned_stub',
    code: 'NX-037-N-09',
    title: 'Ash Stub — Unreadable',
    description: 'A fragment of a sheet reduced to ash. The Bureau kept it because there was nothing else left of it.',
    type: 'NOTE',
    condition: 'BURNED',
    state: 'UNRESOLVED',
    seed: 89,
    damageKind: 'BURNED',
    burnX: 0.5, burnY: 0.55, burnR: 0.55,
    ruled: true,
    width: 560, height: 380,
    header: 'RECOVERED FROM ASH',
    headerRef: 'S01 / BRAZIER',
    timeLine: '',
    handSize: 14,
    location: 'SUB-BASEMENT',
    device: 'ASH',
    capturedAt: '14 OCT 94',
    acquiredAt: '14 OCT 94 01:26',
    integrity: 'DAMAGED',
    source: 'OBS-02',
    tone: '#d2ccb8',
    lines: [
      'the corridor is not',
      'a place that empties',
      'it is a place that is',
      'emptied and the',
      'difference is the',
      'whole of it',
    ],
    relationships: [{ to: 'NX-037-F-05', kind: 'REFERENCE', note: 'The scene log quotes the readable part.' }],
  },
]

/* ─────────────────────────────── audio ─────────────────────────────── */

export const AUDIO = [
  {
    asset: 'audio_rec16_reinterpretation',
    code: 'NX-037-A-01',
    title: 'Dictaphone REC-16 — Reinterpretation',
    description: 'A memo recorded to a machine that was not in the room. The recording is intact and the room it was not in is identifiable.',
    type: 'AUDIO',
    condition: 'NORMAL',
    state: 'REVIEWED',
    seed: 91,
    duration: '01:12',
    channel: 'CH 1',
    integrity: 'VERIFIED',
    location: 'NODE B-04 / TAPE 2',
    device: 'DICTAPHONE / TAPE 2',
    capturedAt: '14 OCT 94 02:26',
    acquiredAt: '19 OCT 94 13:44',
    source: 'CASE FILE NX-037',
    audio_url: '/audio/dictaphone-rec-16-reinterpretation.mp3',
    header: 'REC-16 · DICTAPHONE · TAPE 2',
    headerRight: 'CH 1 · NORMAL',
    segments: 11,
    missing: [],
    noiseFloor: true,
    transcript: 'They say the police bulletin has me leaving at seventeen thirty. I left at seventeen thirty. But the tape says the corridor and the tape is the only witness that does not get paid.',
    relationships: [
      { to: 'NX-037-B-05', kind: 'TEMPORAL', note: 'Recorded during the bench inspection.' },
      { to: 'NX-037-P-01', kind: 'PERSONNEL', note: 'The voice is not identified in the file.' },
    ],
  },
  {
    asset: 'audio_rec18_coherence',
    code: 'NX-037-A-02',
    title: 'Dictaphone REC-18 — Coherence',
    description: 'Clean, level, and made in a room with no windows. There is no such room in the east wing.',
    type: 'AUDIO',
    condition: 'NORMAL',
    state: 'FLAGGED',
    seed: 92,
    duration: '00:48',
    channel: 'CH 1',
    integrity: 'VERIFIED',
    location: 'UNKNOWN',
    device: 'DICTAPHONE / TAPE 2',
    capturedAt: '14 OCT 94 02:44',
    acquiredAt: '19 OCT 94 13:48',
    source: 'CASE FILE NX-037',
    audio_url: '/audio/dictaphone-rec-18-coherence.mp3',
    header: 'REC-18 · DICTAPHONE · TAPE 2',
    headerRight: 'CH 1 · NORMAL',
    segments: 7,
    missing: [],
    noiseFloor: false,
    transcript: 'The wing is coherent. I have walked it twice and every door is where the drawing puts it. I want that on the record before the third walk.',
    relationships: [
      { to: 'NX-037-M-02', kind: 'CONTRADICTION', note: 'The drawing disagrees.' },
      { to: 'NX-CAM-02', kind: 'TEMPORAL', note: 'Recorded three minutes after the archive frame.' },
    ],
  },
  {
    asset: 'audio_rec20_mirror',
    code: 'NX-037-A-03',
    title: 'Dictaphone REC-20 — The Mirror Entity',
    description: 'The longest intact take. The speaker is calm throughout, which is the part that stays with you.',
    type: 'AUDIO',
    condition: 'NORMAL',
    state: 'UNREVIEWED',
    seed: 93,
    duration: '02:34',
    channel: 'CH 1',
    integrity: 'VERIFIED',
    location: 'UNKNOWN',
    device: 'DICTAPHONE / TAPE 2',
    capturedAt: '14 OCT 94 03:02',
    acquiredAt: '19 OCT 94 13:52',
    source: 'CASE FILE NX-037',
    audio_url: '/audio/dictaphone-rec-20-mirror-entity.mp3',
    header: 'REC-20 · DICTAPHONE · TAPE 2',
    headerRight: 'CH 1 · NORMAL',
    segments: 16,
    missing: [],
    noiseFloor: true,
    transcript: 'They wanted an instrument they could aim. What they built answers. It has been answering the same question since April and the answer has not changed and neither have we.',
    relationships: [{ to: 'NX-037-P-05', kind: 'TEMPORAL', note: 'April. The anomalous date.' }],
  },
  {
    asset: 'audio_rec22_sync_degraded',
    code: 'NX-037-A-04',
    title: 'Dictaphone REC-22 — Synchronization (degraded)',
    description: 'The tape drops out in the middle. What is missing is the part where the speaker says who they are.',
    type: 'AUDIO',
    condition: 'DEGRADED',
    state: 'UNRESOLVED',
    seed: 94,
    duration: '01:26',
    channel: 'CH 1',
    integrity: 'DEGRADED',
    location: 'NODE B-04 / TAPE 2',
    device: 'DICTAPHONE / TAPE 2',
    capturedAt: '14 OCT 94 03:09',
    acquiredAt: '19 OCT 94 13:56',
    source: 'CASE FILE NX-037',
    audio_url: '/audio/dictaphone-rec-22-synchronization.mp3',
    header: 'REC-22 · DICTAPHONE · TAPE 2',
    headerRight: 'CH 1 · DEGRADED',
    headerColor: '#d8a05c',
    segments: 12,
    missing: [[0.38, 0.52]],
    noiseFloor: true,
    transcript: 'The array is [NO SIGNAL]. Three shards combined speak of unity. That is the whole of it, and it is not enough, and [NO SIGNAL] we were not the first to be told.',
    relationships: [
      { to: 'NX-037-D-08', kind: 'TEMPORAL', note: 'Falls inside the recorder\'s manual stop.' },
      { to: 'NX-CAM-07', kind: 'TEMPORAL', note: 'Eight minutes before the dropout.' },
    ],
  },
  {
    asset: 'audio_rec24_gmkey',
    code: 'NX-037-A-05',
    title: 'Dictaphone REC-24 — The GM Key',
    description: 'A short take with a long silence at the head of it. The silence is not blank tape; it is a room.',
    type: 'AUDIO',
    condition: 'NORMAL',
    state: 'UNREVIEWED',
    seed: 95,
    duration: '00:39',
    channel: 'CH 1',
    integrity: 'VERIFIED',
    location: 'UNKNOWN',
    device: 'DICTAPHONE / TAPE 2',
    capturedAt: '14 OCT 94 03:24',
    acquiredAt: '19 OCT 94 14:00',
    source: 'CASE FILE NX-037',
    audio_url: '/audio/dictaphone-rec-24-gm-key.mp3',
    header: 'REC-24 · DICTAPHONE · TAPE 2',
    headerRight: 'CH 1 · NORMAL',
    segments: 4,
    missing: [],
    noiseFloor: true,
    transcript: 'The key is not a key. It is an agreement. Everyone who has held it has agreed to the same thing and none of us can say what.',
    relationships: [{ to: 'NX-037-P-06', kind: 'PERSONNEL', note: 'A name appears in the ledger fragment at the same time.' }],
  },
  {
    asset: 'audio_rec26_entity',
    code: 'NX-037-A-06',
    title: 'Dictaphone REC-26 — The Entity',
    description: 'The last intact take before the sequence stops. The Bureau plays it once at a hearing and then files it.',
    type: 'AUDIO',
    condition: 'PARTIAL',
    state: 'CONTRADICTED',
    seed: 96,
    duration: '01:58',
    channel: 'CH 1',
    integrity: 'PARTIAL',
    location: 'UNKNOWN',
    device: 'DICTAPHONE / TAPE 2',
    capturedAt: '14 OCT 94 03:34',
    acquiredAt: '19 OCT 94 14:04',
    source: 'CASE FILE NX-037',
    audio_url: '/audio/dictaphone-rec-26-entity.mp3',
    header: 'REC-26 · DICTAPHONE · TAPE 2',
    headerRight: 'CH 1 · PARTIAL',
    headerColor: '#c8503c',
    segments: 14,
    missing: [[0.62, 0.71], [0.86, 0.92]],
    noiseFloor: true,
    transcript: 'Sequence complete. The entity is not a passenger. It is the corridor. [NO SIGNAL] It has been the corridor the whole time and we have been walking through it [NO SIGNAL] and calling it a building.',
    relationships: [
      { to: 'NX-037-M-01', kind: 'SPATIAL', note: 'The recording names the drawing\'s subject.' },
      { to: 'NX-CAM-07', kind: 'TEMPORAL', note: 'Seventeen minutes after the dropout.' },
    ],
  },
]

/* ──────────────────── artifacts for the anomalous record ──────────────────── */

export const ENVELOPES = [
  { asset: 'env_nx037_b_02', code: 'NX-037-E-01', title: 'EVIDENCE SLEEVE', type: 'PHOTOGRAPH', condition: 'PARTIAL', state: 'CONTRADICTED' },
  { asset: 'env_nx037_f_08', code: 'NX-037-E-02', title: 'EVIDENCE SLEEVE', type: 'FRAGMENT', condition: 'TORN', state: 'UNRESOLVED' },
  { asset: 'env_nx037_c_09', code: 'NX-037-E-03', title: 'EVIDENCE SLEEVE', type: 'MAP', condition: 'DAMAGED', state: 'FLAGGED' },
]

/** The full register: every generated artifact, in one list. */
export const ARTIFACT_REGISTRY = [
  ...PHOTOGRAPHS, ...SURVEILLANCE, ...DOCUMENTS, ...FRAGMENTS,
  ...MAPS, ...PERSONNEL, ...NOTES, ...AUDIO,
]
