/**
 * NEXUS — Player Logic Codes
 *
 * The one screen where a player Logic Code is ever readable. The database stores
 * a salted hash and an encrypted copy, so the plaintext is never persisted in the
 * clear: it exists only for an authenticated Bureau request. That is why this
 * panel must be impossible to reach by accident.
 *
 * Every code on this screen was generated by the single alphabet in
 * src/lib/auth/code-generation.ts and is the same value the player types on the
 * login screen — the panel is fed by the same server response that wrote the
 * hash, so what is shown here is what is stored.
 */

import { useCallback, useRef, useState } from 'react'
import { Check, Copy, Key } from 'lucide-react'
import { cn } from '@/lib/utils'
import { isValidLoginCode, isValidTeamCode } from '@/lib/auth'
import type { PlayerCredential } from '@/lib/admin'

interface PlayerCredentialsPanelProps {
  teamCode: string | null
  teamName?: string
  credentials: PlayerCredential[]
  /** Explains where these codes came from (just issued / re-issued). */
  notice?: string
  className?: string
}

const ROLE_ORDER: Record<string, number> = { OBSERVER: 0, ANALYST: 1, OPERATOR: 2 }

function byRole(a: PlayerCredential, b: PlayerCredential): number {
  return (ROLE_ORDER[a.role] ?? 9) - (ROLE_ORDER[b.role] ?? 9)
}

export function PlayerCredentialsPanel({
  teamCode,
  teamName,
  credentials,
  notice,
  className,
}: PlayerCredentialsPanelProps) {
  const [copiedKey, setCopiedKey] = useState<string | null>(null)
  const resetTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  const markCopied = useCallback((key: string) => {
    setCopiedKey(key)
    if (resetTimer.current) clearTimeout(resetTimer.current)
    resetTimer.current = setTimeout(() => setCopiedKey(null), 2500)
  }, [])

  const copy = useCallback(async (key: string, value: string) => {
    try {
      await navigator.clipboard.writeText(value)
      markCopied(key)
    } catch {
      // Clipboard access can be denied; the code is still on screen to read.
    }
  }, [markCopied])

  const copyAll = useCallback(() => {
    const lines = [
      teamCode ? `Team: ${teamCode}` : null,
      ...[...credentials].sort(byRole).map((c, i) => `Player ${i + 1} — ${c.loginCode}`),
    ].filter((line): line is string => line !== null).join('\n')
    void copy('all', lines)
  }, [copy, credentials, teamCode])

  const download = useCallback(() => {
    const lines = [
      'NEXUS — Player Logic Codes',
      teamName ? `Team: ${teamName} (${teamCode ?? '—'})` : `Team: ${teamCode ?? '—'}`,
      `Issued: ${new Date().toISOString()}`,
      '',
      ...[...credentials].sort(byRole).map((c, i) => {
        const line = `Player ${i + 1} — ${c.loginCode}`
        return c.displayName ? `${line}  (${c.displayName}, ${c.role})` : line
      }),
      '',
      'Each Logic Code is single-use and is consumed the first time that player',
      'logs in. Before they log in you can read the same codes again any time with',
      'Show codes on the Teams list — looking never changes a code.',
    ].join('\n')

    if (typeof URL.createObjectURL !== 'function') return
    const blob = new Blob([lines], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `nexus-team-${teamCode ?? 'codes'}-codes.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
    markCopied('download')
  }, [credentials, markCopied, teamCode, teamName])

  // A code that would not survive the login screen must never be handed out.
  const invalidTeamCode = Boolean(teamCode) && !isValidTeamCode(teamCode)
  const invalidCodes = credentials.filter(c => !isValidLoginCode(c.loginCode))

  return (
    <div className={cn('space-y-4 text-left', className)}>
      {notice && (
        <p className="text-xs text-nexus-textSubtle bg-nexus-bg border border-nexus-border rounded-xl px-3 py-2">
          {notice}
        </p>
      )}

      {(invalidTeamCode || invalidCodes.length > 0) && (
        <p
          className="text-sm text-nexus-danger bg-nexus-dangerBg border border-nexus-danger/30 rounded-xl px-3 py-2"
          role="alert"
        >
          {invalidTeamCode
            ? `Team code "${teamCode}" is not a valid code. Do not hand it out — re-issue the team codes.`
            : `${invalidCodes.length} player code(s) are not a valid Logic Code. Do not hand them out — re-issue the team codes.`}
        </p>
      )}

      {teamCode && (
        <div className="p-4 bg-nexus-bg rounded-xl border border-nexus-border">
          <div className="flex items-center justify-between gap-2">
            <span className="text-xs uppercase tracking-wider text-nexus-textSubtle">Team Code</span>
            <TextButton
              label={copiedKey === 'team' ? 'Copied' : 'Copy team code'}
              copied={copiedKey === 'team'}
              onCopy={() => void copy('team', teamCode)}
              iconOnly
            />
          </div>
          <code className="text-2xl font-mono font-bold text-nexus-danger mt-1 block tracking-widest">
            {teamCode}
          </code>
        </div>
      )}

      <div>
        <div className="flex items-center justify-between mb-2 gap-2 flex-wrap">
          <span className="text-sm font-medium text-nexus-text">
            Player Logic Codes ({credentials.length})
          </span>
          <div className="flex gap-2">
            <TextButton
              label={copiedKey === 'all' ? 'Copied' : 'Copy all codes'}
              copied={copiedKey === 'all'}
              onCopy={copyAll}
              disabled={credentials.length === 0}
            />
            <TextButton
              label={copiedKey === 'download' ? 'Saved' : 'Download'}
              copied={copiedKey === 'download'}
              onCopy={download}
              disabled={credentials.length === 0}
            />
          </div>
        </div>

        <div className="space-y-2">
          {[...credentials].sort(byRole).map((c, i) => {
            const key = c.playerId || c.loginCode
            const copied = copiedKey === key
            return (
              <div
                key={key}
                className="flex items-center justify-between gap-3 p-3 bg-nexus-bg rounded-xl border border-nexus-border"
              >
                <div className="min-w-0">
                  <span className="text-[10px] uppercase tracking-wider text-nexus-textSubtle">
                    Player {i + 1}
                  </span>
                  <span className="font-medium text-nexus-text block truncate">
                    {c.displayName || '—'}
                  </span>
                  <span className="text-[10px] uppercase tracking-wider text-nexus-textSubtle">
                    {c.role}
                  </span>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <div className="text-right">
                    <span className="block text-[10px] uppercase tracking-wider text-nexus-textSubtle">
                      Logic Code
                    </span>
                    <code className="text-nexus-accent font-mono text-lg tracking-widest">
                      {c.loginCode}
                    </code>
                  </div>
                  <TextButton
                    label={copied ? 'Copied' : 'Copy code'}
                    copied={copied}
                    onCopy={() => void copy(key, c.loginCode)}
                    describedAs={`Copy the Logic Code for ${c.displayName || `player ${i + 1}`}`}
                  />
                </div>
              </div>
            )
          })}
        </div>

        <p className="text-xs text-nexus-textSubtle mt-3 flex items-start gap-1.5">
          <Key className="w-3.5 h-3.5 mt-0.5 flex-shrink-0" />
          <span>
            Each Logic Code is single-use and is consumed the first time that player logs
            in. They are not shown again — copy or download them now, and re-issue from
            this team&apos;s page if one is lost.
          </span>
        </p>
      </div>
    </div>
  )
}

/**
 * A labelled action button rather than a bare icon: at a check-in desk the
 * label is the whole point, and it gives screen readers (and tests) a stable
 * name that changes to "Copied" as confirmation.
 */
function TextButton({
  label,
  copied,
  onCopy,
  disabled,
  describedAs,
  iconOnly,
}: {
  label: string
  copied: boolean
  onCopy: () => void
  disabled?: boolean
  /** Overrides the accessible name, e.g. "Copy the Logic Code for Ada". */
  describedAs?: string
  iconOnly?: boolean
}) {
  const accessibleName = copied ? `${describedAs ?? label} — copied` : (describedAs ?? label)
  const Icon = copied ? Check : Copy

  if (iconOnly) {
    return (
      <button
        onClick={onCopy}
        disabled={disabled}
        className="p-1 rounded text-nexus-textSubtle hover:text-nexus-text hover:bg-nexus-surfaceElevated transition-colors"
        aria-label={accessibleName}
        title={accessibleName}
      >
        <Icon className={cn('w-4 h-4', copied && 'text-nexus-accent')} />
      </button>
    )
  }

  return (
    <button
      onClick={onCopy}
      disabled={disabled}
      className="btn-secondary text-xs py-1.5 flex items-center gap-1.5"
      aria-label={accessibleName}
    >
      <Icon className={cn('w-4 h-4', copied && 'text-nexus-accent')} />
      {label}
    </button>
  )
}
