// GENERATED FILE — do not edit by hand.
// Rebuild with: node scripts/evidence-gen/build.mjs
//
// Every artifact below is rendered locally from scripts/evidence-gen/library.mjs
// and written to public/evidence/. The images are the artifact; this file is only
// the index the app uses to reach them.

export type AssetType =
  | 'PHOTOGRAPH'
  | 'SURVEILLANCE'
  | 'DOCUMENT'
  | 'FRAGMENT'
  | 'MAP'
  | 'PERSONNEL'
  | 'NOTE'
  | 'AUDIO'

export type AssetRelationshipKind =
  | 'REFERENCE'
  | 'PERSONNEL'
  | 'SOURCE'
  | 'TEMPORAL'
  | 'SPATIAL'
  | 'CONTRADICTION'
  | 'SUPPORTS'

export interface AssetRelationship {
  to: string
  kind: AssetRelationshipKind
  note: string
}

export interface GeneratedAsset {
  code: string
  asset: string
  type: AssetType
  condition: string
  state: string
  title: string
  description: string
  image: string
  thumb: string | null
  location: string | null
  device: string | null
  capturedAt: string | null
  acquiredAt: string | null
  integrity: string | null
  source: string | null
  duration: string | null
  seed: number
  relationships: AssetRelationship[]
}

export const GENERATED_ASSET_MANIFEST = {
  "case": "NX-037",
  "generatorVersion": "1.0.0",
  "counts": {
    "PHOTOGRAPH": 12,
    "SURVEILLANCE": 9,
    "DOCUMENT": 9,
    "FRAGMENT": 10,
    "MAP": 5,
    "PERSONNEL": 6,
    "NOTE": 9,
    "AUDIO": 6,
    "DAMAGED": 28,
    "TOTAL": 66
  }
}

export const GENERATED_ASSETS: GeneratedAsset[] = [
  {
    code: "NX-037-B-01",
    asset: "photo_nx037_b_01",
    type: "PHOTOGRAPH",
    condition: "NORMAL",
    state: "UNREVIEWED",
    title: "East Corridor, North Approach",
    description: "Handheld frame taken from the archive doorway. The corridor is empty. The second fixture is out.",
    image: "/evidence/photographs/photo_nx037_b_01.jpg",
    thumb: "/evidence/thumb/photo_nx037_b_01.jpg",
    location: "LOC-C214 / EAST CORRIDOR",
    device: "FIELD-CAM-02",
    capturedAt: "14 OCT 94 03:12:44",
    acquiredAt: "14 OCT 94 03:48",
    integrity: "VERIFIED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 13713,
    relationships: [
      { to: "NX-CAM-07", kind: "TEMPORAL", note: "CAM-07 covers the same segment two minutes later." },
      { to: "NX-037-D-01", kind: "SPATIAL", note: "Incident record names LOC-C214." },
    ],
  },
  {
    code: "NX-037-B-02",
    asset: "photo_nx037_b_02",
    type: "PHOTOGRAPH",
    condition: "NORMAL",
    state: "FLAGGED",
    title: "East Corridor, Disputed Segment",
    description: "Second frame. A figure stands at the corridor mouth. Development is uneven; the body is not resolvable.",
    image: "/evidence/photographs/photo_nx037_b_02.jpg",
    thumb: "/evidence/thumb/photo_nx037_b_02.jpg",
    location: "LOC-C214 / EAST CORRIDOR (NORTH)",
    device: "FIELD-CAM-02",
    capturedAt: "14 OCT 94 03:17:11",
    acquiredAt: "14 OCT 94 03:49",
    integrity: "QUESTIONED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 80856,
    relationships: [
      { to: "NX-CAM-07", kind: "TEMPORAL", note: "Clock reads the same second as the CAM-07 frame." },
      { to: "NX-037-P-01", kind: "PERSONNEL", note: "Build matches L.V.-0029; cannot be confirmed." },
    ],
  },
  {
    code: "NX-037-B-03",
    asset: "photo_nx037_b_03",
    type: "PHOTOGRAPH",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Central Archive, Aisle 2",
    description: "Records room after hours. A run of boxes has been pulled and not replaced.",
    image: "/evidence/photographs/photo_nx037_b_03.jpg",
    thumb: "/evidence/thumb/photo_nx037_b_03.jpg",
    location: "LOC-C101 / CENTRAL ARCHIVE",
    device: "FIELD-CAM-02",
    capturedAt: "14 OCT 94 02:41:09",
    acquiredAt: "14 OCT 94 04:02",
    integrity: "VERIFIED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 58475,
    relationships: [
      { to: "NX-037-P-05", kind: "PERSONNEL", note: "M.S.-0388 works this room." },
      { to: "NX-037-F-07", kind: "REFERENCE", note: "Torn shelf label recovered from the same aisle." },
    ],
  },
  {
    code: "NX-037-B-04",
    asset: "photo_nx037_b_04",
    type: "PHOTOGRAPH",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Stairwell 1, Half Landing",
    description: "The handrail has been wiped. The damp on the wall is newer than the paint.",
    image: "/evidence/photographs/photo_nx037_b_04.jpg",
    thumb: "/evidence/thumb/photo_nx037_b_04.jpg",
    location: "LOC-C118 / STAIRWELL 1",
    device: "FIELD-CAM-02",
    capturedAt: "14 OCT 94 02:58:30",
    acquiredAt: "14 OCT 94 04:05",
    integrity: "VERIFIED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 46570,
    relationships: [
      { to: "NX-CAM-03", kind: "SPATIAL", note: "CAM-03 covers this landing." },
    ],
  },
  {
    code: "NX-037-B-05",
    asset: "photo_nx037_b_05",
    type: "PHOTOGRAPH",
    condition: "NORMAL",
    state: "UNREVIEWED",
    title: "Science Wing, Lab 04",
    description: "The bench has been cleared. The whiteboard still carries the previous night's arithmetic.",
    image: "/evidence/photographs/photo_nx037_b_05.jpg",
    thumb: "/evidence/thumb/photo_nx037_b_05.jpg",
    location: "LOC-C202 / SCIENCE WING LAB",
    device: "FIELD-CAM-02",
    capturedAt: "14 OCT 94 02:20:15",
    acquiredAt: "14 OCT 94 04:11",
    integrity: "VERIFIED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 24189,
    relationships: [
      { to: "NX-037-P-01", kind: "PERSONNEL", note: "Lab 04 is L.V.-0029's assigned bench." },
    ],
  },
  {
    code: "NX-037-B-06",
    asset: "photo_nx037_b_06",
    type: "PHOTOGRAPH",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Main Entrance, Night Approach",
    description: "Sodium light over the canopy. The doors were chained from the inside at 22:00.",
    image: "/evidence/photographs/photo_nx037_b_06.jpg",
    thumb: "/evidence/thumb/photo_nx037_b_06.jpg",
    location: "LOC-C001 / MAIN ENTRANCE",
    device: "FIELD-CAM-01",
    capturedAt: "14 OCT 94 01:52:03",
    acquiredAt: "14 OCT 94 04:14",
    integrity: "VERIFIED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 91332,
    relationships: [
      { to: "NX-CAM-01", kind: "SPATIAL", note: "CAM-01 covers the entrance bay." },
    ],
  },
  {
    code: "NX-037-B-07",
    asset: "photo_nx037_b_07",
    type: "PHOTOGRAPH",
    condition: "DAMAGED",
    state: "UNRESOLVED",
    title: "East Corridor, Underside",
    description: "Flash was fired toward the ceiling. The print is unusable for detail, but the fixture spacing is legible.",
    image: "/evidence/photographs/photo_nx037_b_07.jpg",
    thumb: "/evidence/thumb/photo_nx037_b_07.jpg",
    location: "LOC-C214 / EAST CORRIDOR",
    device: "FIELD-CAM-01",
    capturedAt: "14 OCT 94 03:0_:__",
    acquiredAt: "14 OCT 94 04:18",
    integrity: "PARTIAL",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 68951,
    relationships: [
      { to: "NX-037-B-01", kind: "REFERENCE", note: "Same corridor, same camera body." },
    ],
  },
  {
    code: "NX-037-B-08",
    asset: "photo_nx037_b_08",
    type: "PHOTOGRAPH",
    condition: "NORMAL",
    state: "FLAGGED",
    title: "Sub-Basement Plant Room, Valve Tree",
    description: "Water on the floor. One valve has been closed and re-marked in grease pencil.",
    image: "/evidence/photographs/photo_nx037_b_08.jpg",
    thumb: "/evidence/thumb/photo_nx037_b_08.jpg",
    location: "LOC-S01 / SUB-BASEMENT PLANT",
    device: "FIELD-CAM-02",
    capturedAt: "14 OCT 94 01:31:47",
    acquiredAt: "14 OCT 94 04:21",
    integrity: "VERIFIED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 15142,
    relationships: [
      { to: "NX-037-F-04", kind: "REFERENCE", note: "Torn maintenance label names the same valve tree." },
    ],
  },
  {
    code: "NX-037-B-09",
    asset: "photo_nx037_b_09",
    type: "PHOTOGRAPH",
    condition: "NORMAL",
    state: "UNREVIEWED",
    title: "Equipment Room 305, Crates",
    description: "Storage was used as storage. Several crates are stencilled with a department that closed in 1991.",
    image: "/evidence/photographs/photo_nx037_b_09.jpg",
    thumb: "/evidence/thumb/photo_nx037_b_09.jpg",
    location: "LOC-C305 / EQUIPMENT ROOM",
    device: "FIELD-CAM-02",
    capturedAt: "14 OCT 94 02:05:52",
    acquiredAt: "14 OCT 94 04:24",
    integrity: "VERIFIED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 92761,
    relationships: [
      { to: "NX-037-D-05", kind: "REFERENCE", note: "Custody form lists crate 14 from this room." },
    ],
  },
  {
    code: "NX-037-B-10",
    asset: "photo_nx037_b_10",
    type: "PHOTOGRAPH",
    condition: "NORMAL",
    state: "FLAGGED",
    title: "Archive Office, Desk 04",
    description: "A terminal left running. The screen holds a directory listing that does not match the building.",
    image: "/evidence/photographs/photo_nx037_b_10.jpg",
    thumb: "/evidence/thumb/photo_nx037_b_10.jpg",
    location: "LOC-C101A / ARCHIVE OFFICE",
    device: "FIELD-CAM-02",
    capturedAt: "14 OCT 94 02:48:20",
    acquiredAt: "14 OCT 94 04:27",
    integrity: "VERIFIED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 48903,
    relationships: [
      { to: "NX-037-P-05", kind: "PERSONNEL", note: "Desk 04 is assigned to M.S.-0388." },
    ],
  },
  {
    code: "NX-037-B-11",
    asset: "photo_nx037_b_11",
    type: "PHOTOGRAPH",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Lecture Room 214, Empty",
    description: "Seating plan unchanged since 1993. Row B seat 7 carries a name written in pencil.",
    image: "/evidence/photographs/photo_nx037_b_11.jpg",
    thumb: "/evidence/thumb/photo_nx037_b_11.jpg",
    location: "LOC-C214H / LECTURE ROOM",
    device: "FIELD-CAM-02",
    capturedAt: "14 OCT 94 02:33:58",
    acquiredAt: "14 OCT 94 04:30",
    integrity: "VERIFIED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 71284,
    relationships: [
      { to: "NX-037-P-01", kind: "PERSONNEL", note: "L.V.-0029 taught this room." },
    ],
  },
  {
    code: "NX-037-B-12",
    asset: "photo_nx037_b_12",
    type: "PHOTOGRAPH",
    condition: "DAMAGED",
    state: "CONTRADICTED",
    title: "East Corridor, Water Damage",
    description: "A frame taken after the incident. The print has been wet and dried. The timestamp is gone.",
    image: "/evidence/photographs/photo_nx037_b_12.jpg",
    thumb: "/evidence/thumb/photo_nx037_b_12.jpg",
    location: "LOC-C214 / EAST CORRIDOR",
    device: "FIELD-CAM-02",
    capturedAt: "14 OCT 94 __:17:__",
    acquiredAt: "14 OCT 94 04:35",
    integrity: "DEGRADED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 4141,
    relationships: [
      { to: "NX-037-B-02", kind: "CONTRADICTION", note: "Both claim LOC-C214 at the same minute." },
      { to: "NX-CAM-07", kind: "TEMPORAL", note: "Only surviving seconds in this run." },
    ],
  },
  {
    code: "NX-CAM-07",
    asset: "surv_cam07_031711",
    type: "SURVEILLANCE",
    condition: "PARTIAL",
    state: "CONTRADICTED",
    title: "CAM-07 / East Corridor, 03:17:11",
    description: "Recorder frame. The corridor is empty. CAM-07 covers the same segment the field camera photographed at the same second.",
    image: "/evidence/surveillance/surv_cam07_031711.jpg",
    thumb: "/evidence/thumb/surv_cam07_031711.jpg",
    location: "LOC-C214 / EAST CORRIDOR",
    device: "CAM-07 / DVR NODE B-04",
    capturedAt: "14 OCT 94 03:17:11",
    acquiredAt: "19 OCT 94 11:20",
    integrity: "FRAME DROPOUT 03:17:05–03:17:18",
    source: "DVR NODE B-04 / TAPE 7",
    duration: null,
    seed: 72730,
    relationships: [
      { to: "NX-037-B-02", kind: "CONTRADICTION", note: "Same second. The frame shows no one." },
      { to: "NX-037-F-03", kind: "REFERENCE", note: "Torn label assigns CAM-07 to this corridor." },
    ],
  },
  {
    code: "NX-CAM-01",
    asset: "surv_cam01_015203",
    type: "SURVEILLANCE",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "CAM-01 / Main Entrance, 01:52:03",
    description: "Entrance bay. The doors are chained. No movement for the length of the tape.",
    image: "/evidence/surveillance/surv_cam01_015203.jpg",
    thumb: "/evidence/thumb/surv_cam01_015203.jpg",
    location: "LOC-C001 / MAIN ENTRANCE",
    device: "CAM-01 / DVR NODE B-04",
    capturedAt: "14 OCT 94 01:52:03",
    acquiredAt: "19 OCT 94 11:04",
    integrity: "RECORD INTACT",
    source: "DVR NODE B-04 / TAPE 1",
    duration: null,
    seed: 41954,
    relationships: [
      { to: "NX-037-B-06", kind: "TEMPORAL", note: "Field camera at the same minute." },
    ],
  },
  {
    code: "NX-CAM-03",
    asset: "surv_cam03_025830",
    type: "SURVEILLANCE",
    condition: "NORMAL",
    state: "UNREVIEWED",
    title: "CAM-03 / Stairwell 1, 02:58:30",
    description: "Landing. Low light. The camera has not been serviced since the wing closed.",
    image: "/evidence/surveillance/surv_cam03_025830.jpg",
    thumb: "/evidence/thumb/surv_cam03_025830.jpg",
    location: "LOC-C118 / STAIRWELL 1",
    device: "CAM-03 / DVR NODE B-04",
    capturedAt: "14 OCT 94 02:58:30",
    acquiredAt: "19 OCT 94 11:31",
    integrity: "LOW LIGHT / GAIN AT MAXIMUM",
    source: "DVR NODE B-04 / TAPE 3",
    duration: null,
    seed: 9305,
    relationships: [
      { to: "NX-037-B-04", kind: "SPATIAL", note: "Field photograph of the same landing." },
    ],
  },
  {
    code: "NX-CAM-02",
    asset: "surv_cam02_024120",
    type: "SURVEILLANCE",
    condition: "NORMAL",
    state: "FLAGGED",
    title: "CAM-02 / Central Archive, 02:41:20",
    description: "Records room. The aisle light cycles. A person is at the far shelving, back to camera.",
    image: "/evidence/surveillance/surv_cam02_024120.jpg",
    thumb: "/evidence/thumb/surv_cam02_024120.jpg",
    location: "LOC-C101 / CENTRAL ARCHIVE",
    device: "CAM-02 / DVR NODE B-04",
    capturedAt: "14 OCT 94 02:41:20",
    acquiredAt: "19 OCT 94 10:52",
    integrity: "RECORD INTACT",
    source: "DVR NODE B-04 / TAPE 2",
    duration: null,
    seed: 91003,
    relationships: [
      { to: "NX-037-B-03", kind: "TEMPORAL", note: "Field camera eleven seconds later." },
    ],
  },
  {
    code: "NX-CAM-05",
    asset: "surv_cam05_022015",
    type: "SURVEILLANCE",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "CAM-05 / Lab 04, 02:20:15",
    description: "Laboratory. Benches cleared. The whiteboard is legible in frame and was not legible in the field print.",
    image: "/evidence/surveillance/surv_cam05_022015.jpg",
    thumb: "/evidence/thumb/surv_cam05_022015.jpg",
    location: "LOC-C202 / SCIENCE WING LAB",
    device: "CAM-05 / DVR NODE B-04",
    capturedAt: "14 OCT 94 02:20:15",
    acquiredAt: "19 OCT 94 10:31",
    integrity: "RECORD INTACT",
    source: "DVR NODE B-04 / TAPE 5",
    duration: null,
    seed: 17229,
    relationships: [
      { to: "NX-037-B-05", kind: "SPATIAL", note: "Field photograph of the same bench." },
    ],
  },
  {
    code: "NX-CAM-04",
    asset: "surv_cam04_024820",
    type: "SURVEILLANCE",
    condition: "NORMAL",
    state: "FLAGGED",
    title: "CAM-04 / Archive Office, 02:48:20",
    description: "Terminal running. Directory listing on screen. No one at the desk for the length of the tape.",
    image: "/evidence/surveillance/surv_cam04_024820.jpg",
    thumb: "/evidence/thumb/surv_cam04_024820.jpg",
    location: "LOC-C101A / ARCHIVE OFFICE",
    device: "CAM-04 / DVR NODE B-04",
    capturedAt: "14 OCT 94 02:48:20",
    acquiredAt: "19 OCT 94 10:44",
    integrity: "RECORD INTACT",
    source: "DVR NODE B-04 / TAPE 4",
    duration: null,
    seed: 11222,
    relationships: [
      { to: "NX-037-B-10", kind: "TEMPORAL", note: "Field camera at the same second." },
    ],
  },
  {
    code: "NX-CAM-06",
    asset: "surv_cam06_0316_offline",
    type: "SURVEILLANCE",
    condition: "INCOMPLETE",
    state: "UNRESOLVED",
    title: "CAM-06 / Sub-Basement, 03:16:00",
    description: "The camera is not transmitting. The recorder kept the last frame it ever received and kept trying.",
    image: "/evidence/surveillance/surv_cam06_0316_offline.jpg",
    thumb: "/evidence/thumb/surv_cam06_0316_offline.jpg",
    location: "LOC-S01 / SUB-BASEMENT PLANT",
    device: "CAM-06 / DVR NODE B-04",
    capturedAt: "14 OCT 94 03:16:00",
    acquiredAt: "19 OCT 94 12:02",
    integrity: "NO SIGNAL — LAST FRAME RETAINED",
    source: "DVR NODE B-04 / TAPE 6",
    duration: null,
    seed: 94158,
    relationships: [
      { to: "NX-037-B-08", kind: "SPATIAL", note: "Field photograph of the same room." },
    ],
  },
  {
    code: "NX-CAM-08",
    asset: "surv_cam08_0305_partial",
    type: "SURVEILLANCE",
    condition: "DAMAGED",
    state: "UNRESOLVED",
    title: "CAM-08 / Equipment Room, 03:05:41",
    description: "Storage. A recording interval is missing between 03:04:12 and 03:07:30. The recorder does not log why.",
    image: "/evidence/surveillance/surv_cam08_0305_partial.jpg",
    thumb: "/evidence/thumb/surv_cam08_0305_partial.jpg",
    location: "LOC-C305 / EQUIPMENT ROOM",
    device: "CAM-08 / DVR NODE B-04",
    capturedAt: "14 OCT 94 03:05:41",
    acquiredAt: "19 OCT 94 12:14",
    integrity: "INTERVAL MISSING 03:04:12–03:07:30",
    source: "DVR NODE B-04 / TAPE 8",
    duration: null,
    seed: 61602,
    relationships: [
      { to: "NX-037-B-09", kind: "SPATIAL", note: "Field photograph of the same room." },
    ],
  },
  {
    code: "NX-CAM-09",
    asset: "surv_cam09_0225_lecture",
    type: "SURVEILLANCE",
    condition: "NORMAL",
    state: "FLAGGED",
    title: "CAM-09 / Lecture Room 214, 02:25:07",
    description: "Lecture room. A single seat is occupied. The tape holds eleven minutes of nothing else happening.",
    image: "/evidence/surveillance/surv_cam09_0225_lecture.jpg",
    thumb: "/evidence/thumb/surv_cam09_0225_lecture.jpg",
    location: "LOC-C214H / LECTURE ROOM",
    device: "CAM-09 / DVR NODE B-04",
    capturedAt: "14 OCT 94 02:25:07",
    acquiredAt: "19 OCT 94 12:40",
    integrity: "RECORD INTACT",
    source: "DVR NODE B-04 / TAPE 9",
    duration: null,
    seed: 14125,
    relationships: [
      { to: "NX-037-B-11", kind: "SPATIAL", note: "Field photograph of the same room." },
    ],
  },
  {
    code: "NX-037-D-01",
    asset: "doc_nx037_incident_rev03",
    type: "DOCUMENT",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Incident Record 037, Section 4 — East Wing",
    description: "The typed record that opened the case. Section 2 lists four recovered items; only three arrived intact.",
    image: "/evidence/documents/doc_nx037_incident_rev03.jpg",
    thumb: "/evidence/thumb/doc_nx037_incident_rev03.jpg",
    location: "BUREAU OF CONTINUITY RECORDS",
    device: "TYPEWRITER / REMINGTON 42",
    capturedAt: "19 OCT 94",
    acquiredAt: "19 OCT 94 09:10",
    integrity: "VERIFIED",
    source: "CASE FILE NX-037",
    duration: null,
    seed: 69522,
    relationships: [
      { to: "NX-037-B-02", kind: "REFERENCE", note: "Item A is the disputed corridor frame." },
      { to: "NX-037-F-02", kind: "REFERENCE", note: "Item C is the wet torn label." },
    ],
  },
  {
    code: "NX-037-D-02",
    asset: "doc_nx037_ledger_sectorc",
    type: "DOCUMENT",
    condition: "NORMAL",
    state: "FLAGGED",
    title: "Maintenance Ledger, Sector C, Vol. 3",
    description: "Bound repair log. The 12 October entry describes a camera relocation that no other record mentions.",
    image: "/evidence/documents/doc_nx037_ledger_sectorc.jpg",
    thumb: "/evidence/thumb/doc_nx037_ledger_sectorc.jpg",
    location: "FACILITIES ENGINEERING",
    device: "BOUND LEDGER",
    capturedAt: "1994",
    acquiredAt: "19 OCT 94 09:40",
    integrity: "VERIFIED",
    source: "FACILITIES ENGINEERING / VOL 3",
    duration: null,
    seed: 41,
    relationships: [
      { to: "NX-CAM-07", kind: "SOURCE", note: "The ledger is the only record of the relocation." },
      { to: "NX-037-F-04", kind: "REFERENCE", note: "Torn label continues this ledger." },
    ],
  },
  {
    code: "NX-037-D-03",
    asset: "doc_nx037_access_export",
    type: "DOCUMENT",
    condition: "NORMAL",
    state: "UNREVIEWED",
    title: "Access Control Export, 14 October",
    description: "Continuous-form printout from the registry. One credential reads at 03:17:11 and does not exist.",
    image: "/evidence/documents/doc_nx037_access_export.jpg",
    thumb: "/evidence/thumb/doc_nx037_access_export.jpg",
    location: "NEXUS NODE B-04 / TERMINAL 07",
    device: "REGISTRY PRINTER / DOT MATRIX",
    capturedAt: "14 OCT 94 04:40",
    acquiredAt: "19 OCT 94 10:02",
    integrity: "VERIFIED",
    source: "NODE B-04",
    duration: null,
    seed: 42,
    relationships: [
      { to: "NX-037-B-02", kind: "TEMPORAL", note: "The unassigned reads at the photograph's timestamp." },
      { to: "NX-037-P-01", kind: "PERSONNEL", note: "L.V.-0029 is the nearest real holder." },
    ],
  },
  {
    code: "NX-037-D-04",
    asset: "doc_nx037_memo_operations",
    type: "DOCUMENT",
    condition: "PARTIAL",
    state: "UNREVIEWED",
    title: "Memorandum — East Wing Operations",
    description: "Internal memo on continuing the east wing after the archive move. The carbon copy is the only one that survived.",
    image: "/evidence/documents/doc_nx037_memo_operations.jpg",
    thumb: "/evidence/thumb/doc_nx037_memo_operations.jpg",
    location: "INTERNAL OPERATIONS",
    device: "CARBON SET / DUPLICATED",
    capturedAt: "04 OCT 94",
    acquiredAt: "19 OCT 94 10:20",
    integrity: "PARTIAL",
    source: "OPERATIONS FILE",
    duration: null,
    seed: 43,
    relationships: [
      { to: "NX-037-D-02", kind: "REFERENCE", note: "The ledger entry that follows this memo." },
      { to: "NX-CAM-07", kind: "SOURCE", note: "Names the re-aim directly." },
    ],
  },
  {
    code: "NX-037-D-05",
    asset: "doc_nx037_accesscard_ley",
    type: "DOCUMENT",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Access Card, Level 3 — L.V.-0029",
    description: "The card itself, photographed on a light table. The laminate is lifted at one corner.",
    image: "/evidence/documents/doc_nx037_accesscard_ley.jpg",
    thumb: "/evidence/thumb/doc_nx037_accesscard_ley.jpg",
    location: "RECOVERED — LOC-C214",
    device: "LIGHT TABLE / FIELD-CAM-02",
    capturedAt: "14 OCT 94 04:10",
    acquiredAt: "14 OCT 94 04:12",
    integrity: "VERIFIED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 44,
    relationships: [
      { to: "NX-037-P-01", kind: "PERSONNEL", note: "Confirms the holder is L.V.-0029." },
    ],
  },
  {
    code: "NX-037-D-06",
    asset: "doc_nx037_custody_sheet",
    type: "DOCUMENT",
    condition: "DAMAGED",
    state: "UNRESOLVED",
    title: "Chain of Custody, Item NX-037-B-02",
    description: "Custody transfers for the disputed frame. The last transfer has no receiving signature.",
    image: "/evidence/documents/doc_nx037_custody_sheet.jpg",
    thumb: "/evidence/thumb/doc_nx037_custody_sheet.jpg",
    location: "BUREAU OF CONTINUITY RECORDS",
    device: "FILED FORM 2-A",
    capturedAt: "14 OCT 94",
    acquiredAt: "19 OCT 94 10:44",
    integrity: "PARTIAL",
    source: "CASE FILE NX-037",
    duration: null,
    seed: 45,
    relationships: [
      { to: "NX-037-B-02", kind: "REFERENCE", note: "This is the custody record for the disputed frame." },
      { to: "NX-CAM-07", kind: "CONTRADICTION", note: "Registry and recorder disagree." },
    ],
  },
  {
    code: "NX-037-D-07",
    asset: "doc_nx037_requisition",
    type: "DOCUMENT",
    condition: "NORMAL",
    state: "FLAGGED",
    title: "Facilities Requisition 2214 — Sub-Basement",
    description: "Work order for the valve tree. The sign-off time is earlier than the call-out it answers.",
    image: "/evidence/documents/doc_nx037_requisition.jpg",
    thumb: "/evidence/thumb/doc_nx037_requisition.jpg",
    location: "FACILITIES ENGINEERING",
    device: "FILED FORM 2-A",
    capturedAt: "11 OCT 94",
    acquiredAt: "19 OCT 94 11:12",
    integrity: "VERIFIED",
    source: "FACILITIES ENGINEERING",
    duration: null,
    seed: 46,
    relationships: [
      { to: "NX-037-B-08", kind: "SPATIAL", note: "The same valve tree, photographed." },
    ],
  },
  {
    code: "NX-037-D-08",
    asset: "doc_nx037_surveillance_log",
    type: "DOCUMENT",
    condition: "PARTIAL",
    state: "UNRESOLVED",
    title: "Recorder Log Sheet, Node B-04",
    description: "The operator's own log of the night. It records a manual stop on Tape 7 that no system log shows.",
    image: "/evidence/documents/doc_nx037_surveillance_log.jpg",
    thumb: "/evidence/thumb/doc_nx037_surveillance_log.jpg",
    location: "NEXUS NODE B-04",
    device: "BOUND LOG",
    capturedAt: "14 OCT 94",
    acquiredAt: "19 OCT 94 11:26",
    integrity: "PARTIAL",
    source: "NODE B-04",
    duration: null,
    seed: 47,
    relationships: [
      { to: "NX-CAM-07", kind: "TEMPORAL", note: "The manual stop falls inside the dropout window." },
      { to: "NX-037-D-01", kind: "REFERENCE", note: "Incident record cites this log as item D." },
    ],
  },
  {
    code: "NX-037-D-09",
    asset: "doc_nx037_damaged_photo_log",
    type: "DOCUMENT",
    condition: "DAMAGED",
    state: "CONTRADICTED",
    title: "Photographic Processing Log, 14 October",
    description: "Lab log for the field rolls. One frame is marked as rejected before it was printed, and the reason is not the exposure.",
    image: "/evidence/documents/doc_nx037_damaged_photo_log.jpg",
    thumb: "/evidence/thumb/doc_nx037_damaged_photo_log.jpg",
    location: "BUREAU LAB 3",
    device: "LAB PRINTER / DOT MATRIX",
    capturedAt: "15 OCT 94",
    acquiredAt: "19 OCT 94 11:40",
    integrity: "PARTIAL",
    source: "BUREAU LAB 3",
    duration: null,
    seed: 48,
    relationships: [
      { to: "NX-037-B-07", kind: "REFERENCE", note: "The rejected frame." },
      { to: "NX-037-B-02", kind: "CONTRADICTION", note: "The log says this frame was reshot." },
    ],
  },
  {
    code: "NX-037-F-01",
    asset: "frag_nx037_c_01",
    type: "FRAGMENT",
    condition: "TORN",
    state: "UNRESOLVED",
    title: "Torn Section — Incident Record",
    description: "The middle of a typed report, torn from the file. Both ends of the sentence are gone.",
    image: "/evidence/fragments/frag_nx037_c_01.jpg",
    thumb: "/evidence/thumb/frag_nx037_c_01.jpg",
    location: "RECOVERED — LOC-C214",
    device: "FILED PAPER",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 03:52",
    integrity: "PARTIAL",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 51,
    relationships: [
      { to: "NX-037-D-01", kind: "REFERENCE", note: "A page of the incident record." },
    ],
  },
  {
    code: "NX-037-F-02",
    asset: "frag_nx037_c_02",
    type: "FRAGMENT",
    condition: "STAIN",
    state: "FLAGGED",
    title: "Torn Maintenance Label",
    description: "A stencilled equipment label, wet and torn. It names a camera the building has no record of.",
    image: "/evidence/fragments/frag_nx037_c_02.jpg",
    thumb: "/evidence/thumb/frag_nx037_c_02.jpg",
    location: "RECOVERED — LOC-C214",
    device: "ADHESIVE LABEL",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 03:56",
    integrity: "DAMAGED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 52,
    relationships: [
      { to: "NX-CAM-07", kind: "REFERENCE", note: "Names the camera the incident record omits." },
    ],
  },
  {
    code: "NX-037-F-03",
    asset: "frag_nx037_c_03",
    type: "FRAGMENT",
    condition: "DAMAGED",
    state: "UNRESOLVED",
    title: "Ripped Print Corner",
    description: "A corner of a photographic print, recovered separately from the frame. The emulsion is scratched through.",
    image: "/evidence/fragments/frag_nx037_c_03.jpg",
    thumb: "/evidence/thumb/frag_nx037_c_03.jpg",
    location: "RECOVERED — LOC-C214",
    device: "PRINT",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 04:00",
    integrity: "DAMAGED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 53,
    relationships: [
      { to: "NX-037-B-12", kind: "REFERENCE", note: "Same emulsion batch." },
    ],
  },
  {
    code: "NX-037-F-04",
    asset: "frag_nx037_c_04",
    type: "FRAGMENT",
    condition: "TORN",
    state: "UNREVIEWED",
    title: "Ledger Continuation, Torn",
    description: "The bottom of a ledger page, separated at the binding. The last written line stops mid-word.",
    image: "/evidence/fragments/frag_nx037_c_04.jpg",
    thumb: "/evidence/thumb/frag_nx037_c_04.jpg",
    location: "RECOVERED — LOC-C214",
    device: "LEDGER PAGE",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 04:04",
    integrity: "PARTIAL",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 54,
    relationships: [
      { to: "NX-037-D-02", kind: "REFERENCE", note: "Continues the sector C ledger." },
      { to: "NX-037-P-06", kind: "PERSONNEL", note: "The name is cut off before it can be read." },
    ],
  },
  {
    code: "NX-037-F-05",
    asset: "frag_nx037_c_05",
    type: "FRAGMENT",
    condition: "BURNED",
    state: "UNRESOLVED",
    title: "Burnt Paper Fragment",
    description: "Recovered from a brazier in the sub-basement. Most of the sheet is gone.",
    image: "/evidence/fragments/frag_nx037_c_05.jpg",
    thumb: "/evidence/thumb/frag_nx037_c_05.jpg",
    location: "RECOVERED — LOC-S01",
    device: "PAPER",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 01:40",
    integrity: "DAMAGED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 55,
    relationships: [
      { to: "NX-037-B-08", kind: "SPATIAL", note: "Found beside the valve tree." },
    ],
  },
  {
    code: "NX-037-F-06",
    asset: "frag_nx037_c_06",
    type: "FRAGMENT",
    condition: "TORN",
    state: "FLAGGED",
    title: "Access Card, Cut",
    description: "A card cut through the laminate. The photograph and half the number are gone.",
    image: "/evidence/fragments/frag_nx037_c_06.jpg",
    thumb: "/evidence/thumb/frag_nx037_c_06.jpg",
    location: "RECOVERED — LOC-C214",
    device: "LAMINATE",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 03:58",
    integrity: "PARTIAL",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 56,
    relationships: [
      { to: "NX-037-D-05", kind: "REFERENCE", note: "Same card number prefix." },
    ],
  },
  {
    code: "NX-037-F-07",
    asset: "frag_nx037_c_07",
    type: "FRAGMENT",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Archive Shelf Label, Detached",
    description: "A shelf label in the archive aisle, adhesive still wet on the reverse.",
    image: "/evidence/fragments/frag_nx037_c_07.jpg",
    thumb: "/evidence/thumb/frag_nx037_c_07.jpg",
    location: "RECOVERED — LOC-C101",
    device: "SHELF LABEL",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 02:50",
    integrity: "VERIFIED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 57,
    relationships: [
      { to: "NX-037-B-03", kind: "SPATIAL", note: "Taken from the aisle in this frame." },
    ],
  },
  {
    code: "NX-037-F-08",
    asset: "frag_nx037_c_08",
    type: "FRAGMENT",
    condition: "TORN",
    state: "UNRESOLVED",
    title: "Handwritten Note, Partial",
    description: "A field note recovered folded in a pocket. Only the lower half survived.",
    image: "/evidence/fragments/frag_nx037_c_08.jpg",
    thumb: "/evidence/thumb/frag_nx037_c_08.jpg",
    location: "RECOVERED — LOC-C214",
    device: "FIELD NOTE",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 03:59",
    integrity: "PARTIAL",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 58,
    relationships: [
      { to: "NX-037-F-01", kind: "REFERENCE", note: "Both mention the June survey." },
    ],
  },
  {
    code: "NX-037-F-09",
    asset: "frag_nx037_c_09",
    type: "FRAGMENT",
    condition: "DAMAGED",
    state: "FLAGGED",
    title: "Floor Plan Fragment, East Wing",
    description: "A corner of a drawing, cut rather than torn. The room it belongs to is labelled with a code nobody uses.",
    image: "/evidence/fragments/frag_nx037_c_09.jpg",
    thumb: "/evidence/thumb/frag_nx037_c_09.jpg",
    location: "RECOVERED — LOC-C214",
    device: "DRAWING",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 04:08",
    integrity: "DAMAGED",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 59,
    relationships: [
      { to: "NX-037-M-02", kind: "REFERENCE", note: "The current drawing has no C214-X." },
      { to: "NX-CAM-07", kind: "SPATIAL", note: "The marked room contains the CAM-07 mount point." },
    ],
  },
  {
    code: "NX-037-F-10",
    asset: "frag_nx037_c_10",
    type: "FRAGMENT",
    condition: "TORN",
    state: "UNRESOLVED",
    title: "Personnel Record, Detached Page",
    description: "The endorsement page of a personnel file, torn out at the staple.",
    image: "/evidence/fragments/frag_nx037_c_10.jpg",
    thumb: "/evidence/thumb/frag_nx037_c_10.jpg",
    location: "RECOVERED — LOC-C101",
    device: "FILE PAGE",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 04:10",
    integrity: "PARTIAL",
    source: "OBS-02 FIELD RECOVERY",
    duration: null,
    seed: 60,
    relationships: [
      { to: "NX-037-P-01", kind: "PERSONNEL", note: "The same personnel number." },
      { to: "NX-037-F-04", kind: "CONTRADICTION", note: "Dated the day the camera was re-aimed." },
    ],
  },
  {
    code: "NX-037-M-01",
    asset: "map_admin_ground_a201g",
    type: "MAP",
    condition: "NORMAL",
    state: "VERIFIED",
    title: "Admin Building, Ground Floor — A-201-G",
    description: "The drawing of record. Issue 03. Everything in the case sits on this sheet.",
    image: "/evidence/maps/map_admin_ground_a201g.jpg",
    thumb: "/evidence/thumb/map_admin_ground_a201g.jpg",
    location: "FACILITIES ENGINEERING",
    device: "DRAWING / REPROGRAPH",
    capturedAt: "MAR 94",
    acquiredAt: "19 OCT 94 12:02",
    integrity: "VERIFIED",
    source: "FACILITIES ENGINEERING",
    duration: null,
    seed: 61,
    relationships: [
      { to: "NX-CAM-07", kind: "SPATIAL", note: "CAM-07 shown at the north end of C214." },
      { to: "NX-037-F-09", kind: "CONTRADICTION", note: "Issue 03 has no room C214-X." },
    ],
  },
  {
    code: "NX-037-M-02",
    asset: "map_east_wing_issue02",
    type: "MAP",
    condition: "FADED",
    state: "CONTRADICTED",
    title: "Admin Building, Ground Floor — A-201-G ISSUE 02",
    description: "The superseded issue. It contains a room that the current drawing no longer has.",
    image: "/evidence/maps/map_east_wing_issue02.jpg",
    thumb: "/evidence/thumb/map_east_wing_issue02.jpg",
    location: "FACILITIES ENGINEERING",
    device: "DRAWING / REPROGRAPH",
    capturedAt: "AUG 91",
    acquiredAt: "19 OCT 94 12:06",
    integrity: "PARTIAL",
    source: "FACILITIES ENGINEERING",
    duration: null,
    seed: 62,
    relationships: [
      { to: "NX-037-M-01", kind: "CONTRADICTION", note: "The current issue omits C214-X." },
      { to: "NX-037-F-09", kind: "REFERENCE", note: "The fragment is cut from this sheet." },
    ],
  },
  {
    code: "NX-037-M-03",
    asset: "map_science_lab_c202",
    type: "MAP",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Science Wing, Laboratory Level — S-114",
    description: "Bench layout for Labs 01 to 06, including the bench the case keeps returning to.",
    image: "/evidence/maps/map_science_lab_c202.jpg",
    thumb: "/evidence/thumb/map_science_lab_c202.jpg",
    location: "FACILITIES ENGINEERING",
    device: "DRAWING / REPROGRAPH",
    capturedAt: "JAN 93",
    acquiredAt: "19 OCT 94 12:10",
    integrity: "VERIFIED",
    source: "FACILITIES ENGINEERING",
    duration: null,
    seed: 63,
    relationships: [
      { to: "NX-037-P-01", kind: "PERSONNEL", note: "Confirms the bench assignment." },
    ],
  },
  {
    code: "NX-037-M-04",
    asset: "map_subbasement_s01",
    type: "MAP",
    condition: "DAMAGED",
    state: "FLAGGED",
    title: "Sub-Basement Plant Level — S-001",
    description: "The service level under the east wing. The tape route runs through it.",
    image: "/evidence/maps/map_subbasement_s01.jpg",
    thumb: "/evidence/thumb/map_subbasement_s01.jpg",
    location: "FACILITIES ENGINEERING",
    device: "DRAWING / REPROGRAPH",
    capturedAt: "MAR 78",
    acquiredAt: "19 OCT 94 12:14",
    integrity: "DAMAGED",
    source: "FACILITIES ENGINEERING",
    duration: null,
    seed: 64,
    relationships: [
      { to: "NX-037-F-05", kind: "SPATIAL", note: "The brazier is where the burnt fragment came from." },
      { to: "NX-037-D-04", kind: "REFERENCE", note: "The memo puts the tape route through here." },
    ],
  },
  {
    code: "NX-037-M-05",
    asset: "map_tower_section_t7",
    type: "MAP",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Clock Tower, Vertical Section — T-7",
    description: "A section through the tower. The clock movement is annotated in a hand that is not the draughtsman's.",
    image: "/evidence/maps/map_tower_section_t7.jpg",
    thumb: "/evidence/thumb/map_tower_section_t7.jpg",
    location: "FACILITIES ENGINEERING",
    device: "CYANOTYPE",
    capturedAt: "JUN 74",
    acquiredAt: "19 OCT 94 12:18",
    integrity: "VERIFIED",
    source: "FACILITIES ENGINEERING",
    duration: null,
    seed: 65,
    relationships: [
      { to: "NX-037-D-09", kind: "TEMPORAL", note: "The clock is the case's other recurring time reference." },
    ],
  },
  {
    code: "NX-037-P-01",
    asset: "personnel_lv_0029",
    type: "PERSONNEL",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Personnel Record — L.V.-0029",
    description: "The file for the project lead. Every endorsement is in someone else's hand.",
    image: "/evidence/personnel/personnel_lv_0029.jpg",
    thumb: "/evidence/thumb/personnel_lv_0029.jpg",
    location: "LAB 04 / EAST WING ACCESS",
    device: "FILED FORM P-1",
    capturedAt: "1994",
    acquiredAt: "19 OCT 94 12:44",
    integrity: "VERIFIED",
    source: "PERSONNEL FILE",
    duration: null,
    seed: 71,
    relationships: [
      { to: "NX-037-F-10", kind: "REFERENCE", note: "The torn endorsement page is hers." },
      { to: "NX-037-D-03", kind: "PERSONNEL", note: "Her credential is in the export." },
    ],
  },
  {
    code: "NX-037-P-02",
    asset: "personnel_mc_0114",
    type: "PERSONNEL",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Personnel Record — M.C.-0114",
    description: "The deputy lead. His file is the shortest of the four and the only one that is fully closed.",
    image: "/evidence/personnel/personnel_mc_0114.jpg",
    thumb: "/evidence/thumb/personnel_mc_0114.jpg",
    location: "LAB 02",
    device: "FILED FORM P-1",
    capturedAt: "1994",
    acquiredAt: "19 OCT 94 12:48",
    integrity: "VERIFIED",
    source: "PERSONNEL FILE",
    duration: null,
    seed: 72,
    relationships: [
      { to: "NX-037-D-04", kind: "PERSONNEL", note: "He signed the east wing memo." },
      { to: "NX-037-D-09", kind: "PERSONNEL", note: "The reshot frame was ordered by him." },
    ],
  },
  {
    code: "NX-037-P-03",
    asset: "personnel_nr_0471",
    type: "PERSONNEL",
    condition: "NORMAL",
    state: "UNREVIEWED",
    title: "Personnel Record — N.R.-0471",
    description: "The officer who opened the incident record. Her photograph was taken on a different day to her file.",
    image: "/evidence/personnel/personnel_nr_0471.jpg",
    thumb: "/evidence/thumb/personnel_nr_0471.jpg",
    location: "OBSERVATION POST 3",
    device: "FILED FORM P-1",
    capturedAt: "1994",
    acquiredAt: "19 OCT 94 12:52",
    integrity: "VERIFIED",
    source: "PERSONNEL FILE",
    duration: null,
    seed: 73,
    relationships: [
      { to: "NX-037-D-01", kind: "PERSONNEL", note: "She signed the incident record." },
    ],
  },
  {
    code: "NX-037-P-04",
    asset: "personnel_ms_0388",
    type: "PERSONNEL",
    condition: "DAMAGED",
    state: "FLAGGED",
    title: "Personnel Record — M.S.-0388",
    description: "The archivist. Her file carries an access endorsement for the east wing that was never signed by the holder.",
    image: "/evidence/personnel/personnel_ms_0388.jpg",
    thumb: "/evidence/thumb/personnel_ms_0388.jpg",
    location: "CENTRAL ARCHIVE / DESK 04",
    device: "FILED FORM P-1",
    capturedAt: "1994",
    acquiredAt: "19 OCT 94 12:56",
    integrity: "PARTIAL",
    source: "PERSONNEL FILE",
    duration: null,
    seed: 74,
    relationships: [
      { to: "NX-037-B-10", kind: "SPATIAL", note: "Desk 04 in the archive office." },
    ],
  },
  {
    code: "NX-037-P-05",
    asset: "personnel_lv_0029_duplicate",
    type: "PERSONNEL",
    condition: "ANOMALOUS",
    state: "ANOMALOUS",
    title: "Personnel Record — L.V.-0029 (DUPLICATE)",
    description: "A second file for the same number. Its control number appears inside its own contents, and its dates are impossible.",
    image: "/evidence/personnel/personnel_lv_0029_duplicate.jpg",
    thumb: "/evidence/thumb/personnel_lv_0029_duplicate.jpg",
    location: "LAB 04",
    device: "FILED FORM P-1",
    capturedAt: "17 APR 98",
    acquiredAt: "19 OCT 94 13:04",
    integrity: "CONTRADICTED",
    source: "PERSONNEL FILE / ANOMALOUS",
    duration: null,
    seed: 75,
    relationships: [
      { to: "NX-037-P-01", kind: "CONTRADICTION", note: "Same number, different appointment date." },
      { to: "NX-037-D-01", kind: "TEMPORAL", note: "17 APR 98 is the case's other impossible date." },
    ],
  },
  {
    code: "NX-037-P-06",
    asset: "personnel_d_wright_unestablished",
    type: "PERSONNEL",
    condition: "INCOMPLETE",
    state: "UNRESOLVED",
    title: "Personnel Record — D. WRIGHT (NOT ON ESTABLISHMENT)",
    description: "A file opened for a person the Institute has no record of employing. The surname is legible; everything that would identify the holder is not.",
    image: "/evidence/personnel/personnel_d_wright_unestablished.jpg",
    thumb: "/evidence/thumb/personnel_d_wright_unestablished.jpg",
    location: "SECTOR C / PLANT ROOM",
    device: "FILED FORM P-1",
    capturedAt: "14 OCT 94",
    acquiredAt: "19 OCT 94 13:11",
    integrity: "INCOMPLETE",
    source: "UNASSIGNED FILE / FOUND IN SECTOR C",
    duration: null,
    seed: 76,
    relationships: [
      { to: "NX-037-F-04", kind: "REFERENCE", note: "The name this file was opened for." },
      { to: "NX-037-A-05", kind: "TEMPORAL", note: "Named at the same minute on the same tape." },
      { to: "NX-037-D-02", kind: "REFERENCE", note: "Signed the sector C ledger by order." },
    ],
  },
  {
    code: "NX-037-N-01",
    asset: "note_observer02_01",
    type: "NOTE",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Field Observation Sheet 1 — OBS-02",
    description: "The observation team's own sheet, in order, with times that line up with everything else.",
    image: "/evidence/notes/note_observer02_01.jpg",
    thumb: "/evidence/thumb/note_observer02_01.jpg",
    location: "SUB-BASEMENT / EAST WING",
    device: "FIELD BOOK",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 02:36",
    integrity: "VERIFIED",
    source: "OBS-02",
    duration: null,
    seed: 81,
    relationships: [
      { to: "NX-037-F-05", kind: "SPATIAL", note: "The burnt sheet is logged here." },
    ],
  },
  {
    code: "NX-037-N-02",
    asset: "note_observer02_02",
    type: "NOTE",
    condition: "NORMAL",
    state: "FLAGGED",
    title: "Field Observation Sheet 2 — OBS-02",
    description: "The sheet that stops in the middle of a line. The last entry is about the corridor.",
    image: "/evidence/notes/note_observer02_02.jpg",
    thumb: "/evidence/thumb/note_observer02_02.jpg",
    location: "EAST CORRIDOR",
    device: "FIELD BOOK",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 03:46",
    integrity: "VERIFIED",
    source: "OBS-02",
    duration: null,
    seed: 82,
    relationships: [
      { to: "NX-037-B-02", kind: "TEMPORAL", note: "The frame is taken at the line where the note stops." },
      { to: "NX-037-F-08", kind: "REFERENCE", note: "The torn note is the rest of this page." },
    ],
  },
  {
    code: "NX-037-N-03",
    asset: "note_observer02_03",
    type: "NOTE",
    condition: "DAMAGED",
    state: "UNRESOLVED",
    title: "Field Observation Sheet 3 — OBS-02",
    description: "Written after the corridor, back in the entrance. The handwriting changes.",
    image: "/evidence/notes/note_observer02_03.jpg",
    thumb: "/evidence/thumb/note_observer02_03.jpg",
    location: "MAIN ENTRANCE",
    device: "FIELD BOOK",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 04:38",
    integrity: "DAMAGED",
    source: "OBS-02",
    duration: null,
    seed: 83,
    relationships: [
      { to: "NX-037-P-02", kind: "PERSONNEL", note: "The name the note could not resolve." },
      { to: "NX-037-F-01", kind: "REFERENCE", note: "The torn section mentions the same survey." },
    ],
  },
  {
    code: "NX-037-N-04",
    asset: "note_archivist_04",
    type: "NOTE",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Archivist Note — M.S.-0388",
    description: "A note left inside a file, addressed to whoever reads the box next.",
    image: "/evidence/notes/note_archivist_04.jpg",
    thumb: "/evidence/thumb/note_archivist_04.jpg",
    location: "CENTRAL ARCHIVE",
    device: "FILE NOTE",
    capturedAt: "OCT 94",
    acquiredAt: "19 OCT 94 13:20",
    integrity: "VERIFIED",
    source: "M.S.-0388",
    duration: null,
    seed: 84,
    relationships: [
      { to: "NX-037-F-07", kind: "REFERENCE", note: "Names the shelf label exactly." },
    ],
  },
  {
    code: "NX-037-N-05",
    asset: "note_index_card_maintenance",
    type: "NOTE",
    condition: "NORMAL",
    state: "UNREVIEWED",
    title: "Index Card — Camera Schedule",
    description: "A card-index card. The card below it in the drawer is blank and not marked as withdrawn.",
    image: "/evidence/notes/note_index_card_maintenance.jpg",
    thumb: "/evidence/thumb/note_index_card_maintenance.jpg",
    location: "CENTRAL ARCHIVE",
    device: "INDEX CARD",
    capturedAt: "1994",
    acquiredAt: "19 OCT 94 13:24",
    integrity: "VERIFIED",
    source: "CENTRAL ARCHIVE",
    duration: null,
    seed: 85,
    relationships: [
      { to: "NX-037-F-02", kind: "REFERENCE", note: "The asset label carries the same re-aim date." },
      { to: "NX-037-M-02", kind: "SPATIAL", note: "C214-X exists only on issue 02." },
    ],
  },
  {
    code: "NX-037-N-06",
    asset: "note_marginalia_d01",
    type: "NOTE",
    condition: "NORMAL",
    state: "FLAGGED",
    title: "Marginalia — Incident Record 037",
    description: "Written in the margin of a filed record, in a different hand from the record.",
    image: "/evidence/notes/note_marginalia_d01.jpg",
    thumb: "/evidence/thumb/note_marginalia_d01.jpg",
    location: "CASE FILE NX-037",
    device: "FILED DOCUMENT",
    capturedAt: "OCT 94",
    acquiredAt: "19 OCT 94 13:28",
    integrity: "VERIFIED",
    source: "UNKNOWN HAND",
    duration: null,
    seed: 86,
    relationships: [
      { to: "NX-037-D-01", kind: "REFERENCE", note: "Written on the incident record." },
    ],
  },
  {
    code: "NX-037-N-07",
    asset: "note_tape_route",
    type: "NOTE",
    condition: "DAMAGED",
    state: "UNRESOLVED",
    title: "Maintenance Scrawl — Tape Route",
    description: "A scrap of repair-room paper, in pencil, with a diagram that does not match any drawing on file.",
    image: "/evidence/notes/note_tape_route.jpg",
    thumb: "/evidence/thumb/note_tape_route.jpg",
    location: "FACILITIES",
    device: "SCRAP PAPER",
    capturedAt: "OCT 94",
    acquiredAt: "19 OCT 94 13:32",
    integrity: "DAMAGED",
    source: "TECH-11",
    duration: null,
    seed: 87,
    relationships: [
      { to: "NX-037-M-04", kind: "SPATIAL", note: "The drawing does not match this diagram." },
      { to: "NX-CAM-07", kind: "SOURCE", note: "Explains the missing interval on tape 7." },
    ],
  },
  {
    code: "NX-037-N-08",
    asset: "note_roster_sheet",
    type: "NOTE",
    condition: "NORMAL",
    state: "FLAGGED",
    title: "Establish List, East Wing",
    description: "A typed list of who is supposed to be in the wing after hours. Six names. One line is struck through and the ink has been gone over.",
    image: "/evidence/notes/note_roster_sheet.jpg",
    thumb: "/evidence/thumb/note_roster_sheet.jpg",
    location: "OPERATIONS",
    device: "FILED LIST",
    capturedAt: "OCT 94",
    acquiredAt: "19 OCT 94 13:36",
    integrity: "QUESTIONED",
    source: "INTERNAL OPERATIONS",
    duration: null,
    seed: 88,
    relationships: [
      { to: "NX-037-P-04", kind: "PERSONNEL", note: "Item 3 is the archivist." },
      { to: "NX-037-P-02", kind: "PERSONNEL", note: "Item 2 is the deputy lead." },
    ],
  },
  {
    code: "NX-037-N-09",
    asset: "note_burned_stub",
    type: "NOTE",
    condition: "BURNED",
    state: "UNRESOLVED",
    title: "Ash Stub — Unreadable",
    description: "A fragment of a sheet reduced to ash. The Bureau kept it because there was nothing else left of it.",
    image: "/evidence/notes/note_burned_stub.jpg",
    thumb: "/evidence/thumb/note_burned_stub.jpg",
    location: "SUB-BASEMENT",
    device: "ASH",
    capturedAt: "14 OCT 94",
    acquiredAt: "14 OCT 94 01:26",
    integrity: "DAMAGED",
    source: "OBS-02",
    duration: null,
    seed: 89,
    relationships: [
      { to: "NX-037-F-05", kind: "REFERENCE", note: "The scene log quotes the readable part." },
    ],
  },
  {
    code: "NX-037-A-01",
    asset: "audio_rec16_reinterpretation",
    type: "AUDIO",
    condition: "NORMAL",
    state: "REVIEWED",
    title: "Dictaphone REC-16 — Reinterpretation",
    description: "A memo recorded to a machine that was not in the room. The recording is intact and the room it was not in is identifiable.",
    image: "/evidence/audio/audio_rec16_reinterpretation.jpg",
    thumb: "/evidence/thumb/audio_rec16_reinterpretation.jpg",
    location: "NODE B-04 / TAPE 2",
    device: "DICTAPHONE / TAPE 2",
    capturedAt: "14 OCT 94 02:26",
    acquiredAt: "19 OCT 94 13:44",
    integrity: "VERIFIED",
    source: "CASE FILE NX-037",
    duration: "01:12",
    seed: 91,
    relationships: [
      { to: "NX-037-B-05", kind: "TEMPORAL", note: "Recorded during the bench inspection." },
      { to: "NX-037-P-01", kind: "PERSONNEL", note: "The voice is not identified in the file." },
    ],
  },
  {
    code: "NX-037-A-02",
    asset: "audio_rec18_coherence",
    type: "AUDIO",
    condition: "NORMAL",
    state: "FLAGGED",
    title: "Dictaphone REC-18 — Coherence",
    description: "Clean, level, and made in a room with no windows. There is no such room in the east wing.",
    image: "/evidence/audio/audio_rec18_coherence.jpg",
    thumb: "/evidence/thumb/audio_rec18_coherence.jpg",
    location: "UNKNOWN",
    device: "DICTAPHONE / TAPE 2",
    capturedAt: "14 OCT 94 02:44",
    acquiredAt: "19 OCT 94 13:48",
    integrity: "VERIFIED",
    source: "CASE FILE NX-037",
    duration: "00:48",
    seed: 92,
    relationships: [
      { to: "NX-037-M-02", kind: "CONTRADICTION", note: "The drawing disagrees." },
      { to: "NX-CAM-02", kind: "TEMPORAL", note: "Recorded three minutes after the archive frame." },
    ],
  },
  {
    code: "NX-037-A-03",
    asset: "audio_rec20_mirror",
    type: "AUDIO",
    condition: "NORMAL",
    state: "UNREVIEWED",
    title: "Dictaphone REC-20 — The Mirror Entity",
    description: "The longest intact take. The speaker is calm throughout, which is the part that stays with you.",
    image: "/evidence/audio/audio_rec20_mirror.jpg",
    thumb: "/evidence/thumb/audio_rec20_mirror.jpg",
    location: "UNKNOWN",
    device: "DICTAPHONE / TAPE 2",
    capturedAt: "14 OCT 94 03:02",
    acquiredAt: "19 OCT 94 13:52",
    integrity: "VERIFIED",
    source: "CASE FILE NX-037",
    duration: "02:34",
    seed: 93,
    relationships: [
      { to: "NX-037-P-05", kind: "TEMPORAL", note: "April. The anomalous date." },
    ],
  },
  {
    code: "NX-037-A-04",
    asset: "audio_rec22_sync_degraded",
    type: "AUDIO",
    condition: "DEGRADED",
    state: "UNRESOLVED",
    title: "Dictaphone REC-22 — Synchronization (degraded)",
    description: "The tape drops out in the middle. What is missing is the part where the speaker says who they are.",
    image: "/evidence/audio/audio_rec22_sync_degraded.jpg",
    thumb: "/evidence/thumb/audio_rec22_sync_degraded.jpg",
    location: "NODE B-04 / TAPE 2",
    device: "DICTAPHONE / TAPE 2",
    capturedAt: "14 OCT 94 03:09",
    acquiredAt: "19 OCT 94 13:56",
    integrity: "DEGRADED",
    source: "CASE FILE NX-037",
    duration: "01:26",
    seed: 94,
    relationships: [
      { to: "NX-037-D-08", kind: "TEMPORAL", note: "Falls inside the recorder's manual stop." },
      { to: "NX-CAM-07", kind: "TEMPORAL", note: "Eight minutes before the dropout." },
    ],
  },
  {
    code: "NX-037-A-05",
    asset: "audio_rec24_gmkey",
    type: "AUDIO",
    condition: "NORMAL",
    state: "UNREVIEWED",
    title: "Dictaphone REC-24 — The GM Key",
    description: "A short take with a long silence at the head of it. The silence is not blank tape; it is a room.",
    image: "/evidence/audio/audio_rec24_gmkey.jpg",
    thumb: "/evidence/thumb/audio_rec24_gmkey.jpg",
    location: "UNKNOWN",
    device: "DICTAPHONE / TAPE 2",
    capturedAt: "14 OCT 94 03:24",
    acquiredAt: "19 OCT 94 14:00",
    integrity: "VERIFIED",
    source: "CASE FILE NX-037",
    duration: "00:39",
    seed: 95,
    relationships: [
      { to: "NX-037-P-06", kind: "PERSONNEL", note: "A name appears in the ledger fragment at the same time." },
    ],
  },
  {
    code: "NX-037-A-06",
    asset: "audio_rec26_entity",
    type: "AUDIO",
    condition: "PARTIAL",
    state: "CONTRADICTED",
    title: "Dictaphone REC-26 — The Entity",
    description: "The last intact take before the sequence stops. The Bureau plays it once at a hearing and then files it.",
    image: "/evidence/audio/audio_rec26_entity.jpg",
    thumb: "/evidence/thumb/audio_rec26_entity.jpg",
    location: "UNKNOWN",
    device: "DICTAPHONE / TAPE 2",
    capturedAt: "14 OCT 94 03:34",
    acquiredAt: "19 OCT 94 14:04",
    integrity: "PARTIAL",
    source: "CASE FILE NX-037",
    duration: "01:58",
    seed: 96,
    relationships: [
      { to: "NX-037-M-01", kind: "SPATIAL", note: "The recording names the drawing's subject." },
      { to: "NX-CAM-07", kind: "TEMPORAL", note: "Seventeen minutes after the dropout." },
    ],
  },
]

const BY_CODE = new Map(GENERATED_ASSETS.map((a) => [a.code, a]))

export function generatedAsset(code: string): GeneratedAsset | undefined {
  return BY_CODE.get(code)
}

export function generatedAssetsOfType(type: AssetType): GeneratedAsset[] {
  return GENERATED_ASSETS.filter((a) => a.type === type)
}

export function generatedAssetCounts(): Record<string, number> {
  return GENERATED_ASSETS.reduce<Record<string, number>>((acc, a) => {
    acc[a.type] = (acc[a.type] ?? 0) + 1
    return acc
  }, {})
}
