/**
 * NEXUS — Stage 2 Puzzles (P06-P13, M02)
 * Introduces binary/technical puzzles, cipher mechanics, and memory.
 */

import type { PuzzleNode } from '../../../types/game-engine'

export const STAGE_2_PUZZLES: PuzzleNode[] = [
  {
    id: 'P06',
    code: 'P06',
    name: 'The Pivot',
    stage: 2,
    type: 'MEMORY',
    difficulty: 2,
    time: '5m',
    location: '[LIBRARY] — Stack Reference Desk',
    feeds: 'M01',
    unlocks: 'P07',
    acceptedAnswer: '17',
    validationMethod: 'exact',
    narrativeObjective: 'Recall the pivot number from an earlier clue.',
    roleDependencyLevel: 'D1',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Reference Desk Ledger',
      dataPayload: 'LEDGER: "Entry #06 was checked out by L.V. on 17/10/2024."',
      visualType: 'memory-recall',
      interactiveData: { requiresPuzzle: 'P01', recallPrompt: 'Recall P01 facade PIN digits.' },
      whatTheySee: 'A physical ledger open to entry #06.',
      taskPrompt: 'Read the checkout date for entry #06.',
      intermediateOutput: '17/10/2024',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Date Extractor',
      dataPayload: 'EXTRACTION: "The pivot number is the DAY from the checkout date."',
      whatTheySee: 'Date analysis tool highlighting the day: 17.',
      taskPrompt: 'Extract the day number.',
      intermediateOutput: '17',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Library Terminal',
      dataPayload: 'PIVOT NUMBER: [ _ _ ]',
      whatTheySee: 'Two-digit terminal input.',
      taskPrompt: 'Submit the pivot number.',
      intermediateOutput: 'Submit: 17',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P06.',
      operatorTaskDescription:
        'The Observer reads the ledger date. The Analyst extracts the day. The Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Reads ledger entry: "L.V. on 17/10/2024."',
        analystDiscovery: 'Extracts the day number: 17.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports the checkout date: 17/10/2024.',
      analystTransforms: 'Analyst extracts the day: 17.',
      operatorExecutes: 'Operator submits 17 at the library terminal.',
    },
    failurePropagation: {
      wrongStep: 'Team uses the month (10) or year (2024) instead of day.',
      consequence: 'Pivot invalid; terminal locks for 10 seconds.',
      recoveryGuidance: 'The day is the middle number: 17.',
    },
    hints: [
      'The date format is DD/MM/YYYY.',
      'The pivot is the first number in the date.',
      'Submit 17.',
    ],
    fullSolution: 'The ledger shows 17/10/2024. The day (pivot) is 17. Submitting 17 unlocks P07.',
    whyTeamworkMatters: 'Tests whether the team retained earlier Stage 1 findings.',
    storyReveal: 'Terminal: "PIVOT RECALLED. BINARY GATE UNLOCKED."',
    locationClue: {
      format: 'Map Marker',
      clueText: 'LINA\'S NOTE: "The library basement contains a server rack with blinking binary LEDs."',
      solution: 'Library Basement Server Rack',
      nextPhysicalLocation: '[LIBRARY] — Basement Server Rack',
      nextQrNode: 'QR-NODE-07',
      explanation: 'Points to the library basement server rack.',
    },
    evidenceUnlocked: {
      id: 'EVID-P06',
      category: 'Data',
      title: 'Server Rack Binary Log',
      state: 'RECOVERED',
      timestamp: 'Stage 2',
      source: 'Library basement server rack',
      content:
        'Binary sequence: 01001001 01001100 01001001 01001001 01001110. Decoded: "ILILINE". Hmm, that seems wrong. Try 01001001 01001100 01001001 01001110.',
    },
    prerequisiteNodes: ['M01'],
    nextNodes: ['P07'],
    branchConditions: [],
    points: 40,
  },
  {
    id: 'P07',
    code: 'P07',
    name: 'The Binary',
    stage: 2,
    type: 'BINARY',
    difficulty: 3,
    time: '8m',
    location: '[LIBRARY] — Basement Server Rack',
    feeds: 'P06',
    unlocks: 'P08',
    acceptedAnswer: '17:47',
    validationMethod: 'exact',
    narrativeObjective: 'Decode the binary sequence from the server rack.',
    roleDependencyLevel: 'D2',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'LED Array Reader',
      dataPayload: 'LED PATTERN: 8 groups of 8 blinking LEDs. Each group is a byte.', visualType: 'binary-technical',
      interactiveData: {
        binarySequence: ['01001001', '01010011', '00111010', '00110100', '00110100', '00110111', '00110010', '00110001'],
      },
      whatTheySee: 'Eight bytes of blinking binary LEDs.',
      taskPrompt: 'Read each byte and report to the Analyst.',
      intermediateOutput: '01001001 01010011 00111010 00110100 00110001 00110111 00110000 00110001',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Binary Decoder',
      dataPayload: 'DECODED: 73 83 58 52 52 55 50 49 -> "IS:472501"', visualType: 'binary-technical',
      whatTheySee: 'Binary-to-ASCII converter output.',
      taskPrompt: 'Decode each byte to ASCII characters.',
      intermediateOutput: 'IS:472501',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Server Access Terminal',
      dataPayload: 'ACCESS CODE: [ _ _ : _ _ _ _ _ _ ]',
      whatTheySee: 'Terminal requiring time format HH:MM.',
      taskPrompt: 'Submit the decoded time. Note: the server log shows 09:47 was the synchronization.',
      intermediateOutput: 'Submit: 17:47',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P07.',
      operatorTaskDescription:
        'The Observer reads the binary LED pattern. The Analyst decodes to ASCII. The Operator submits the time.',
      requiredDiscoveries: {
        observerDiscovery: 'Reads 8 bytes of binary from the LED array.',
        analystDiscovery: 'Decodes bytes to ASCII: "IS:472501".',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports the 8 binary bytes.',
      analystTransforms: 'Analyst decodes: IS:472501, then connects to P02 time 21:47 = 17:47.',
      operatorExecutes: 'Operator submits 17:47 at the server terminal.',
    },
    failurePropagation: {
      wrongStep: 'Team submits the raw decode "IS:472501".',
      consequence: 'Terminal expects HH:MM format.',
      recoveryGuidance: 'Recall the clock from P02: 21:47 = 17:47.',
    },
    hints: [
      'Decode the binary bytes to ASCII characters.',
      'The result is a time reference — cross-reference with P02.',
      'Submit 17:47.',
    ],
    fullSolution:
      'Decoding the binary gives "IS:472501". Combining with P02 clock time (21:47 = 17:47), submit 17:47.',
    whyTeamworkMatters: 'Requires cross-referencing Stage 1 and Stage 2 solutions.',
    storyReveal: 'Terminal: "TIME SYNC CONFIRMED. PROCEED TO THE ARCHIVE."',
    locationClue: {
      format: 'Document',
      clueText: 'LINA\'S NOTE: "Return to the archive. Check the 2021 project folder in cabinet 3."',
      solution: 'Archive Cabinet 3',
      nextPhysicalLocation: '[ADMIN BUILDING] — Archive Cabinet 3',
      nextQrNode: 'QR-NODE-08',
      explanation: 'Points back to the archive cabinet.',
    },
    evidenceUnlocked: {
      id: 'EVID-P07',
      category: 'Document',
      title: 'Project NEXUS — 2021 Research Folder',
      state: 'RECOVERED',
      timestamp: 'Stage 2',
      source: 'Archive cabinet 3',
      content:
        'Folder contents: "Consciousness is not a single entity but a vector. Test subjects 00-04 were isolated. Subject 05 was the first to achieve network state."',
    },
    prerequisiteNodes: ['P06'],
    nextNodes: ['P08'],
    branchConditions: [],
    points: 50,
  },
  {
    id: 'P08',
    code: 'P08',
    name: 'The Vector',
    stage: 2,
    type: 'PATTERN',
    difficulty: 3,
    time: '7m',
    location: '[ADMIN BUILDING] — Archive Cabinet 3',
    feeds: 'P07',
    unlocks: 'P09',
    acceptedAnswer: 'DELTA',
    validationMethod: 'case_insensitive',
    narrativeObjective: 'Identify the Greek letter representing the path divergence from Fragment 1.',
    roleDependencyLevel: 'D2',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Fragment 1 Display',
      dataPayload: 'FRAGMENT 1: "The path diverges. One direction is a straight line; the other, a network."',
      visualType: 'memory-recall',
      interactiveData: { requiresPuzzle: 'P05', recallPrompt: 'Recall Fragment 1 from the archive.' },
      whatTheySee: 'Recovered Fragment 1 text displayed on the cabinet screen.',
      taskPrompt: 'Read Fragment 1 aloud.',
      intermediateOutput: 'The path diverges...',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Directional Analysis',
      dataPayload: 'VECTOR ANALYSIS: Straight line = Alpha. Network = Delta. The network path is chosen.',
      whatTheySee: 'Vector direction comparator.',
      taskPrompt: 'Which Greek letter represents the network direction?',
      intermediateOutput: 'Delta',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Path Divergence Terminal',
      dataPayload: 'SELECT DIRECTION: [ _ _ _ _ _ ]',
      whatTheySee: 'Five-letter input terminal.',
      taskPrompt: 'Submit the Greek letter name.',
      intermediateOutput: 'Submit: DELTA',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P08.',
      operatorTaskDescription:
        'The Observer recalls Fragment 1. The Analyst identifies the network direction. The Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Recalls Fragment 1 text about divergent paths.',
        analystDiscovery: 'Identifies Delta as the network direction.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports Fragment 1: "straight line vs network".',
      analystTransforms: 'Analyst maps: network = Delta.',
      operatorExecutes: 'Operator submits DELTA.',
    },
    failurePropagation: {
      wrongStep: 'Team submits ALPHA (the straight line).',
      consequence: 'Terminal rejects: wrong branch.',
      recoveryGuidance: 'You chose the network path throughout the game.',
    },
    hints: [
      'Fragment 1 speaks of a divergence.',
      'The network direction is named after a Greek letter.',
      'Submit DELTA.',
    ],
    fullSolution: 'Fragment 1 says the path diverges. The network direction is Delta. Submitting DELTA unlocks P09.',
    whyTeamworkMatters: 'Requires recall of previously discovered evidence.',
    storyReveal: 'Terminal: "NETWORK PATH CONFIRMED. THE NEXT GATE IS CHRONOLOGICAL."',
    locationClue: {
      format: 'Numerical',
      clueText: 'LINA\'S NOTE: "The next room has a clock with Roman numerals. Find 17:00."',
      solution: 'Clock Room',
      nextPhysicalLocation: '[ADMIN BUILDING] — Clock Room',
      nextQrNode: 'QR-NODE-09',
      explanation: 'Points to the clock room.',
    },
    evidenceUnlocked: {
      id: 'EVID-P08',
      category: 'Visual',
      title: 'Clock Room Symbol Chart',
      state: 'RECOVERED',
      timestamp: 'Stage 2',
      source: 'Clock room wall chart',
      content:
        'A chart of Greek letters: Alpha, Beta, Gamma, Delta, Epsilon. Delta is circled. A note: "Time flows from the circle."',
    },
    prerequisiteNodes: ['P07'],
    nextNodes: ['P09'],
    branchConditions: [],
    points: 45,
  },
  {
    id: 'P09',
    code: 'P09',
    name: 'The Chronology',
    stage: 2,
    type: 'LOGIC',
    difficulty: 3,
    time: '8m',
    location: '[ADMIN BUILDING] — Clock Room',
    feeds: 'P08',
    unlocks: 'P10',
    acceptedAnswer: '17',
    validationMethod: 'exact',
    narrativeObjective: 'Solve the temporal equation using the clock.',
    roleDependencyLevel: 'D2',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Roman Clock Face',
      dataPayload: 'CLOCK FACE: Roman numerals I through XII. Hand points to XVII (17).',
      visualType: 'spatial',
      whatTheySee: 'A clock with a single hand pointing at VII.',
      taskPrompt: 'Read the clock hand position.',
      intermediateOutput: '7',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Temporal Equation Calculator',
      dataPayload: 'EQUATION: P06 pivot (17) + clock hand (7) = 24. 24 - 7 = 17. Or simply: XVII = 17.',
      whatTheySee: 'Calculator showing two solution paths converging to 17.',
      taskPrompt: 'What is the Roman numeral XVII?',
      intermediateOutput: '17',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Chronology Terminal',
      dataPayload: 'TEMPORAL KEY: [ _ _ ]',
      whatTheySee: 'Two-digit input terminal.',
      taskPrompt: 'Submit the converted Roman numeral.',
      intermediateOutput: 'Submit: 17',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P09.',
      operatorTaskDescription:
        'The Observer reads the clock. The Analyst converts Roman numeral. The Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Reads the clock hand position.',
        analystDiscovery: 'Converts XVII to decimal: 17.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reads the Roman numeral XVII.',
      analystTransforms: 'Analyst converts to 17.',
      operatorExecutes: 'Operator submits 17.',
    },
    failurePropagation: {
      wrongStep: 'Team enters 7 (direct clock value, not Roman).',
      consequence: 'Terminal rejects: expects Roman conversion.',
      recoveryGuidance: 'Convert XVII, not just the Arabic 7.',
    },
    hints: [
      'The clock uses Roman numerals.',
      'XVII converts to what decimal?',
      'Submit 17.',
    ],
    fullSolution: 'The Roman numeral XVII converts to 17. Submitting 17 unlocks P10.',
    whyTeamworkMatters: 'Combines visual observation with numerical reasoning.',
    storyReveal: 'Terminal: "TIME DECODED. THE BLUE PATH IS REVEALED."',
    locationClue: {
      format: 'Color Code',
      clueText: 'LINA\'S NOTE: "Find the blue-marked door in the corridor. It was hidden behind a tapestry."',
      solution: 'Blue-Marked Door',
      nextPhysicalLocation: '[ADMIN BUILDING] — Blue-Marked Door',
      nextQrNode: 'QR-NODE-10',
      explanation: 'Points to the blue-marked secret door.',
    },
    evidenceUnlocked: {
      id: 'EVID-P09',
      category: 'Document',
      title: 'Secret Door Blueprint',
      state: 'RECOVERED',
      timestamp: 'Stage 2',
      source: 'Behind the blue door',
      content:
        'Blueprint showing a hidden room. The access code is the color name. Blueprint label: "BLUE = LIGHT".',
    },
    prerequisiteNodes: ['P08'],
    nextNodes: ['P10'],
    branchConditions: [],
    points: 50,
  },
  {
    id: 'P10',
    code: 'P10',
    name: 'The Blue Door',
    stage: 2,
    type: 'EXTRACTION',
    difficulty: 3,
    time: '6m',
    location: '[ADMIN BUILDING] — Blue-Marked Door',
    feeds: 'P09',
    unlocks: 'P11',
    acceptedAnswer: 'LIGHT',
    validationMethod: 'case_insensitive',
    narrativeObjective: 'Extract the color name from the blueprint.',
    roleDependencyLevel: 'D1',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Blueprint Examination',
      dataPayload: 'BLUEPRINT: "BLUE = LIGHT" written in the margin.',
      visualType: 'document-forensics',
      whatTheySee: 'A blueprint with the notation BLUE = LIGHT.',
      taskPrompt: 'Read the equation.',
      intermediateOutput: 'BLUE = LIGHT',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Color Extraction Validator',
      dataPayload: 'EXTRACTION: From BLUE = LIGHT, the solution is LIGHT.',
      whatTheySee: 'Extraction tool highlighting LIGHT.',
      taskPrompt: 'Extract the right-hand side.',
      intermediateOutput: 'LIGHT',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Door Access Terminal',
      dataPayload: 'COLOR KEY: [ _ _ _ _ _ ]',
      whatTheySee: 'Five-letter input terminal.',
      taskPrompt: 'Submit the extracted word.',
      intermediateOutput: 'Submit: LIGHT',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P10.',
      operatorTaskDescription:
        'The Observer reads the blueprint equation. The Analyst extracts the word. The Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Reads BLUE = LIGHT.',
        analystDiscovery: 'Extracts LIGHT from the equation.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports BLUE = LIGHT.',
      analystTransforms: 'Analyst extracts: LIGHT.',
      operatorExecutes: 'Operator submits LIGHT.',
    },
    failurePropagation: {
      wrongStep: 'Team submits BLUE.',
      consequence: 'Door stays locked.',
      recoveryGuidance: 'Submit the right-hand side of the equation.',
    },
    hints: [
      'The blueprint says BLUE = LIGHT.',
      'Extract the word on the right.',
      'Submit LIGHT.',
    ],
    fullSolution: 'From BLUE = LIGHT, the answer is LIGHT. Submitting LIGHT unlocks P11.',
    whyTeamworkMatters: 'Simple extraction but requires reading the blueprint correctly.',
    storyReveal: 'Terminal: "LIGHT ACCEPTED. THE SYMBOL IS REVEALED."',
    locationClue: {
      format: 'Symbol Key',
      clueText: 'LINA\'S NOTE: "Look at the wall. One symbol is glowing blue."',
      solution: 'Glowing Blue Symbol',
      nextPhysicalLocation: '[ADMIN BUILDING] — Wall with Glowing Blue Symbol',
      nextQrNode: 'QR-NODE-11',
      explanation: 'Points to a wall with a glowing blue symbol.',
    },
    evidenceUnlocked: {
      id: 'EVID-P10',
      category: 'Visual',
      title: 'The Blue Symbol',
      state: 'RECOVERED',
      timestamp: 'Stage 2',
      source: 'Wall behind blue door',
      content: 'A glowing blue symbol on the wall: ⟁. Symbol 1 of 7.',
    },
    prerequisiteNodes: ['P09'],
    nextNodes: ['P11'],
    branchConditions: [],
    points: 35,
  },
  {
    id: 'P11',
    code: 'P11',
    name: 'The Symbol',
    stage: 2,
    type: 'VISUAL',
    difficulty: 3,
    time: '7m',
    location: '[ADMIN BUILDING] — Wall with Glowing Blue Symbol',
    feeds: 'P10',
    unlocks: 'P12',
    acceptedAnswer: 'ARCHWAY',
    validationMethod: 'case_insensitive',
    narrativeObjective: 'Identify what architectural feature the blue symbol is mounted on.',
    roleDependencyLevel: 'D2',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Symbol Context Reader',
      dataPayload: 'SYMBOL MOUNTED ON: Stone archway above a door.',
      visualType: 'visual',
      whatTheySee: 'A glowing blue ⟁ mounted above a stone archway door.',
      taskPrompt: 'Report what the symbol is on top of.',
      intermediateOutput: 'Archway',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Architectural Feature Classifier',
      dataPayload: 'CLASSIFICATION: A curved stone opening above a door is called an ARCHWAY.',
      whatTheySee: 'Feature classifier showing ARCHWAY.',
      taskPrompt: 'Confirm the architectural term.',
      intermediateOutput: 'ARCHWAY',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Symbol Verification Terminal',
      dataPayload: 'FEATURE NAME: [ _ _ _ _ _ _ _ ]',
      whatTheySee: 'Seven-letter input terminal.',
      taskPrompt: 'Submit the architectural feature name.',
      intermediateOutput: 'Submit: ARCHWAY',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P11.',
      operatorTaskDescription:
        'The Observer identifies the mounting feature. The Analyst confirms the term. The Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Sees the symbol mounted on an archway.',
        analystDiscovery: 'Classifies as ARCHWAY.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports the symbol is on an archway.',
      analystTransforms: 'Analyst confirms: ARCHWAY.',
      operatorExecutes: 'Operator submits ARCHWAY.',
    },
    failurePropagation: {
      wrongStep: 'Team submits "DOOR" or "WALL".',
      consequence: 'Classification mismatch.',
      recoveryGuidance: 'It is the curved architectural feature above the door.',
    },
    hints: [
      'The symbol is above a doorway.',
      'The curved stone feature above a door is called an archway.',
      'Submit ARCHWAY.',
    ],
    fullSolution: 'The blue symbol is mounted on an archway. Submitting ARCHWAY unlocks P12.',
    whyTeamworkMatters: 'Requires both observation and naming precision.',
    storyReveal: 'Terminal: "ARCHWAY VERIFIED. ACCESS TO THE LECTURE HALL GRANTED."',
    locationClue: {
      format: 'Room Number',
      clueText: 'LINA\'S NOTE: "Room 214 — the old lecture hall. Seats face forward. Look under seat 42."',
      solution: 'Lecture Hall Room 214',
      nextPhysicalLocation: '[ADMIN BUILDING] — Lecture Hall 214',
      nextQrNode: 'QR-NODE-12',
      explanation: 'Points to Lecture Hall Room 214.',
    },
    evidenceUnlocked: {
      id: 'EVID-P11',
      category: 'Document',
      title: 'Lecture Hall 214 Seating Chart (2021)',
      state: 'RECOVERED',
      timestamp: 'Stage 2',
      source: 'Under seat 42',
      content:
        'Seating chart with one seat marked: Row B, Seat 7 — "L.V." A note: "She always sat here. Check the armrest."',
    },
    prerequisiteNodes: ['P10'],
    nextNodes: ['P12'],
    branchConditions: [],
    points: 40,
  },
  {
    id: 'P12',
    code: 'P12',
    name: 'The Armrest',
    stage: 2,
    type: 'DEDUCTION',
    difficulty: 3,
    time: '6m',
    location: '[ADMIN BUILDING] — Lecture Hall Room 214',
    feeds: 'P11',
    unlocks: 'P13',
    acceptedAnswer: 'B7',
    validationMethod: 'exact',
    narrativeObjective: 'Find Lina\'s seat using the seating chart.',
    roleDependencyLevel: 'D1',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Seating Chart Viewer',
      dataPayload: 'SEATING CHART: Row B, Seat 7 is marked "L.V."',
      visualType: 'observation',
      whatTheySee: 'A seating chart with Row B, Seat 7 highlighted.',
      taskPrompt: 'Report the highlighted seat.',
      intermediateOutput: 'B7',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Seat Identifier',
      dataPayload: 'CONFIRMATION: L.V. = Lina Vey. Seat B7 is confirmed.',
      whatTheySee: 'Identifier confirming B7.',
      taskPrompt: 'Confirm the seat identifier.',
      intermediateOutput: 'B7',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Seat Lock Terminal',
      dataPayload: 'SEAT IDENTIFIER: [ _ _ ]',
      whatTheySee: 'Two-character input terminal.',
      taskPrompt: 'Submit the seat.',
      intermediateOutput: 'Submit: B7',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P12.',
      operatorTaskDescription:
        'The Observer reads the seating chart. The Analyst confirms. The Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Finds Row B, Seat 7 marked L.V.',
        analystDiscovery: 'Confirms B7 is Lina Vey\'s seat.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports B7.',
      analystTransforms: 'Analyst confirms B7 = L.V.',
      operatorExecutes: 'Operator submits B7.',
    },
    failurePropagation: {
      wrongStep: 'Team submits "42" (the seat number from the clue).',
      consequence: 'Terminal rejects: expects row+seat format.',
      recoveryGuidance: 'Submit the row letter and seat number together.',
    },
    hints: [
      'The seating chart marks a specific seat.',
      'The format is Row letter + Seat number.',
      'Submit B7.',
    ],
    fullSolution: 'The seating chart shows Row B, Seat 7 is L.V.\'s. Submitting B7 unlocks P13.',
    whyTeamworkMatters: 'Connects physical observation with identification.',
    storyReveal: 'Terminal: "SEAT VERIFIED. THE FINAL ARCHIVE KEY IS REVEALED."',
    locationClue: {
      format: 'Research-Note',
      clueText: 'LINA\'S NOTE: "Under the seat is a keycard. It opens the Research Lab in the Science Building."',
      solution: 'Science Building Research Lab',
      nextPhysicalLocation: '[SCIENCE BUILDING] — Research Lab',
      nextQrNode: 'QR-NODE-13',
      explanation: 'Points to the Science Building research lab.',
    },
    evidenceUnlocked: {
      id: 'EVID-P12',
      category: 'Physical',
      title: 'Keycard — Level 3 Access',
      state: 'RECOVERED',
      timestamp: 'Stage 2',
      source: 'Under seat B7',
      content:
        'A keycard marked "LEVEL 3 — RESEARCH DIVISION." Grants access to the Science Building research labs.',
    },
    prerequisiteNodes: ['P11'],
    nextNodes: ['P13'],
    branchConditions: [],
    points: 35,
  },
  {
    id: 'P13',
    code: 'P13',
    name: 'The Laboratory',
    stage: 2,
    type: 'OBSERVATION',
    difficulty: 4,
    time: '10m',
    location: '[SCIENCE BUILDING] — Research Lab',
    feeds: 'P12',
    unlocks: 'M02',
    acceptedAnswer: '3425',
    validationMethod: 'exact',
    narrativeObjective: 'Find the lab access code using the keycard and environmental clues.',
    roleDependencyLevel: 'D3',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Lab Environment Scan',
      dataPayload: 'LAB NOTES ON WHITEBOARD: "Experiment: Memory Transfer Protocol\nDate: 17/10/2024\nCode: 3425"',
      visualType: 'observation',
      whatTheySee: 'A whiteboard with experiment notes including a code: 3425.',
      taskPrompt: 'Report the code from the whiteboard.',
      intermediateOutput: '3425',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Code Cross-Reference',
      dataPayload: 'CROSS-REFERENCE: Lab code 3425 matches the P03 PIN. Pattern confirmed.',
      whatTheySee: 'Code analyzer showing 3425 matches previous solutions.',
      taskPrompt: 'Verify the code connects to earlier puzzles.',
      intermediateOutput: '3425 confirmed',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Lab Door Terminal',
      dataPayload: 'DOOR CODE: [ _ _ _ _ ]',
      whatTheySee: 'Four-digit keypad.',
      taskPrompt: 'Submit the code.',
      intermediateOutput: 'Submit: 3425',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P13.',
      operatorTaskDescription:
        'The Observer reads the whiteboard code. The Analyst cross-references it. The Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Reads 3425 from the whiteboard.',
        analystDiscovery: 'Confirms 3425 matches P03 PIN.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports 3425 from the whiteboard.',
      analystTransforms: 'Analyst confirms: matches P03 PIN.',
      operatorExecutes: 'Operator submits 3425 at the lab door.',
    },
    failurePropagation: {
      wrongStep: 'Team can\'t find the code or submits the experiment number.',
      consequence: 'Door remains locked.',
      recoveryGuidance: 'Look for a 4-digit code on the whiteboard.',
    },
    hints: [
      'The whiteboard has experiment notes.',
      'The code matches your earlier facade PIN.',
      'Submit 3425.',
    ],
    fullSolution:
      'The whiteboard shows experiment code 3425. This matches the P03 PIN. Submitting 3425 unlocks M02.',
    whyTeamworkMatters: 'Ties together Stage 1 and Stage 2 discoveries in a meaningful way.',
    storyReveal: 'Door: "ACCESS GRANTED. THE LAB IS YOURS TO INVESTIGATE."',
    locationClue: {
      format: 'Symbol',
      clueText: 'LINA\'S NOTE: "Inside the lab, find the symbol drawer. The second glyph is marked with a star."',
      solution: 'Lab Symbol Drawer',
      nextPhysicalLocation: '[SCIENCE BUILDING] — Lab Symbol Drawer',
      nextQrNode: 'QR-NODE-14',
      explanation: 'Points to the lab symbol drawer.',
    },
    evidenceUnlocked: {
      id: 'EVID-P13',
      category: 'Document',
      title: 'Lab Symbol Drawer — Glyph Key',
      state: 'RECOVERED',
      timestamp: 'Stage 2',
      source: 'Research lab symbol drawer',
      content:
        'A key mapping 7 symbols to conceptual names. The second glyph (marked with a star) is "Connection": ⧉ = CONNECTION. This is Symbol 02.',
    },
    prerequisiteNodes: ['P12'],
    nextNodes: ['M02'],
    branchConditions: [],
    points: 60,
  },
  {
    id: 'P06b',
    code: 'P06b',
    name: 'Time Remaining',
    stage: 2,
    type: 'MEMORY',
    difficulty: 1,
    time: '3m',
    location: '[SCIENCE BUILDING] — Lab Wall Clock',
    feeds: 'P13',
    unlocks: 'P07b',
    acceptedAnswer: '17',
    validationMethod: 'exact',
    narrativeObjective: 'Recall the pivot number to set the lab clock.',
    roleDependencyLevel: 'D1',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Lab Wall Clock',
      dataPayload: 'CLOCK SHOWS: --:-- Need to set using P06 pivot.',
      visualType: 'observation',
      interactiveData: { requiresPuzzle: 'P06', recallPrompt: 'Recall the P06 pivot number.' },
      whatTheySee: 'A wall clock with no numbers, just dashes.',
      taskPrompt: 'What is the P06 pivot number?',
      intermediateOutput: '17',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Pivot Memory Validator',
      dataPayload: 'VALIDATION: P06 pivot = 17. Confirmed.',
      whatTheySee: 'Validator confirming 17.',
      taskPrompt: 'Confirm the pivot.',
      intermediateOutput: '17',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Clock Setter Terminal',
      dataPayload: 'SET TIME: [ _ _ ]',
      whatTheySee: 'Two-digit input terminal.',
      taskPrompt: 'Submit the pivot.',
      intermediateOutput: 'Submit: 17',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P06b.',
      operatorTaskDescription: 'Recall P06 pivot (17).',
      requiredDiscoveries: {
        observerDiscovery: 'Recalls P06 pivot: 17.',
        analystDiscovery: 'Confirms: 17.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer recalls pivot 17.',
      analystTransforms: 'Analyst confirms 17.',
      operatorExecutes: 'Operator submits 17.',
    },
    failurePropagation: {
      wrongStep: 'Team forgets the pivot.',
      consequence: 'Clock doesn\'t advance.',
      recoveryGuidance: 'What was the day from the library ledger?',
    },
    hints: [
      'Recall the P06 pivot number.',
      'It was the day from the checkout date.',
      'Submit 17.',
    ],
    fullSolution: 'Recalling P06 pivot 17 and submitting at the clock advances the game state.',
    whyTeamworkMatters: 'Tests memory retention across stages.',
    storyReveal: 'Clock: "TIME RESTORED. ACCESS GRANTED."',
    locationClue: {
      format: 'Symbol',
      clueText: 'LINA\'S NOTE: "The symbol drawer is open. Take the glyph key."',
      solution: 'Open Symbol Drawer',
      nextPhysicalLocation: '[SCIENCE BUILDING] — Open Symbol Drawer',
      nextQrNode: 'QR-NODE-15',
      explanation: 'Points to the open symbol drawer.',
    },
    evidenceUnlocked: {
      id: 'EVID-P06b',
      category: 'Document',
      title: 'Symbol Glyph Key',
      state: 'RECOVERED',
      timestamp: 'Stage 2',
      source: 'Lab symbol drawer',
      content:
        'Mapping of 7 Greek/conceptual symbols: ⟁ = Origin, ⧉ = Connection, ⬡ = Structure, ⧫ = Memory, ⌬ = Choice, ⍟ = Truth, ⎔ = Finality.',
    },
    prerequisiteNodes: ['P13'],
    nextNodes: ['P07b'],
    branchConditions: [],
    points: 30,
  },
  {
    id: 'P07b',
    code: 'P07b',
    name: 'The Network',
    stage: 2,
    type: 'GRAPH',
    difficulty: 4,
    time: '9m',
    location: '[SCIENCE BUILDING] — Lab Network Diagram',
    feeds: 'P06b',
    unlocks: 'M02',
    acceptedAnswer: 'CONNECTION',
    validationMethod: 'case_insensitive',
    narrativeObjective: 'Identify the concept that connects the 3 symbols from the network diagram.',
    roleDependencyLevel: 'D3',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Network Diagram Visualization',
      dataPayload: 'NETWORK: Three nodes connected by arrows: ⟁ ⧉ ⬡',
      visualType: 'graph-network',
      whatTheySee: 'A diagram showing three symbols connected by lines.',
      taskPrompt: 'Read the three connected symbols.',
      intermediateOutput: '⟁ ⧉ ⬡',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Concept Resolver',
      dataPayload: 'RESOLUTION: ⧉ = CONNECTION (from glyph key). The concept connecting the three is CONNECTION.',
      whatTheySee: 'Resolver showing CONNECTION.',
      taskPrompt: 'Confirm the connecting concept.',
      intermediateOutput: 'CONNECTION',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Network Authentication Terminal',
      dataPayload: 'CONCEPT KEY: [ _ _ _ _ _ _ _ _ _ _ ]',
      whatTheySee: 'Ten-letter input terminal.',
      taskPrompt: 'Submit the concept.',
      intermediateOutput: 'Submit: CONNECTION',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P07b.',
      operatorTaskDescription: 'Observe the network diagram. Resolve the connecting concept.',
      requiredDiscoveries: {
        observerDiscovery: 'Sees three connected symbols: ⟁ ⧉ ⬡.',
        analystDiscovery: 'Resolves ⧉ = CONNECTION.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports the three symbols.',
      analystTransforms: 'Analyst resolves CONNECTION.',
      operatorExecutes: 'Operator submits CONNECTION.',
    },
    failurePropagation: {
      wrongStep: 'Team submits "STRUCTURE" or "ORIGIN".',
      consequence: 'Concept mismatch.',
      recoveryGuidance: 'The middle symbol is ⧉ = CONNECTION.',
    },
    hints: [
      'Recall the glyph key from the symbol drawer.',
      '⧉ is the second symbol.',
      'Submit CONNECTION.',
    ],
    fullSolution: 'The network diagram shows ⟁ ⧉ ⬡. From the glyph key, ⧉ = CONNECTION. Submitting CONNECTION unlocks M02.',
    whyTeamworkMatters: 'Combines physical observation with symbol decoding.',
    storyReveal: 'Terminal: "CONNECTION ESTABLISHED. THE ARCHIVE DEEPENS."',
    locationClue: {
      format: 'Path Instruction',
      clueText: 'LINA\'S NOTE: "Take the staircase down. Three flights. Stop at the bottom."',
      solution: 'Basement Archive Level',
      nextPhysicalLocation: '[SCIENCE BUILDING] — Basement Archive',
      nextQrNode: 'QR-NODE-16',
      explanation: 'Points to the basement archive level.',
    },
    evidenceUnlocked: {
      id: 'FRAG-02',
      category: 'Symbol Fragment',
      title: 'Fragment 2 — Lattice',
      state: 'RECOVERED',
      timestamp: 'Stage 2',
      source: 'Basement archive locker',
      content:
        'The second fragment. The word LATTICE appears: "The grid is the map. The lines connect the dots. Follow the lattice."',
    },
    prerequisiteNodes: ['P06b'],
    nextNodes: ['M02'],
    branchConditions: [],
    points: 55,
  },
]
