/**
 * NEXUS — Stage 3 Puzzles (P14-P21, M03)
 * Introduces cipher puzzles, memory recall, audio, and cross-referencing.
 */

import type { PuzzleNode } from '../../../types/game-engine'

export const STAGE_3_PUZZLES: PuzzleNode[] = [
  {
    id: 'P14',
    code: 'P14',
    name: 'The Memory Bank',
    stage: 3,
    type: 'MEMORY',
    difficulty: 3,
    time: '6m',
    location: '[SCIENCE BUILDING] — Memory Lab',
    feeds: 'M02',
    unlocks: 'P15',
    acceptedAnswer: 'VECTOR',
    validationMethod: 'case_insensitive',
    narrativeObjective: 'Recall Fragment 1 to access the memory bank.',
    roleDependencyLevel: 'D2',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Memory Bank Terminal',
      dataPayload: 'PROMPT: "Recall the first fragment. What is the keyword?"',
      visualType: 'memory-recall',
      interactiveData: { requiresPuzzle: 'P05', recallPrompt: 'Recall Fragment 1 keyword.' },
      whatTheySee: 'Terminal asking for the first fragment keyword.',
      taskPrompt: 'Report the Fragment 1 keyword.',
      intermediateOutput: 'VECTOR',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Fragment Validator',
      dataPayload: 'VALIDATION: Fragment 1 keyword is VECTOR. Confirmed.',
      whatTheySee: 'Validator showing VECTOR.',
      taskPrompt: 'Verify the keyword.',
      intermediateOutput: 'VECTOR',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Memory Access Terminal',
      dataPayload: 'ACCESS CODE: [ _ _ _ _ _ _ ]',
      whatTheySee: 'Six-letter input terminal.',
      taskPrompt: 'Submit the keyword.',
      intermediateOutput: 'Submit: VECTOR',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal shows execution interface for P14.',
      operatorTaskDescription: 'Recall Fragment 1 keyword from Stage 2.',
      requiredDiscoveries: {
        observerDiscovery: 'Recalls Fragment 1: VECTOR.',
        analystDiscovery: 'Confirms VECTOR.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer recalls VECTOR.',
      analystTransforms: 'Analyst confirms VECTOR.',
      operatorExecutes: 'Operator submits VECTOR.',
    },
    failurePropagation: {
      wrongStep: 'Team submits wrong word.',
      consequence: 'Memory bank rejects.',
      recoveryGuidance: 'Recall the first fragment keyword.',
    },
    hints: ['Recall Fragment 1 from Stage 2.', 'It was about the path divergence.', 'Submit VECTOR.'],
    fullSolution: 'Fragment 1 keyword is VECTOR. Submitting VECTOR unlocks P15.',
    whyTeamworkMatters: 'Tests whether the team retained earlier evidence.',
    storyReveal: 'Terminal: "MEMORY ACCESS GRANTED. THE ARCHIVE EXPANDS."',
    locationClue: {
      format: 'Symbol',
      clueText: 'LINA\'S NOTE: "Find the second symbol on campus. It is near the library entrance."',
      solution: 'Library Entrance Second Symbol',
      nextPhysicalLocation: '[LIBRARY] — Entrance Symbol',
      nextQrNode: 'QR-NODE-17',
      explanation: 'Points to the library entrance symbol.',
    },
    evidenceUnlocked: {
      id: 'EVID-P14',
      category: 'Visual',
      title: 'Library Entrance Symbol',
      state: 'RECOVERED',
      content: 'A carved symbol: ⧉. This is the second of the seven symbols.',
      timestamp: 'Stage 3',
      source: 'Library entrance',
    },
    prerequisiteNodes: ['M02'],
    nextNodes: ['P15'],
    branchConditions: [],
    points: 45,
  },
  {
    id: 'P15',
    code: 'P15',
    name: 'The Cipher Wheel',
    stage: 3,
    type: 'CIPHER',
    difficulty: 3,
    time: '7m',
    location: '[LIBRARY] — Entrance Symbol Wall',
    feeds: 'P14',
    unlocks: 'P16',
    acceptedAnswer: '3425',
    validationMethod: 'exact',
    narrativeObjective: 'Decrypt the message on the cipher wheel using the symbol key.',
    roleDependencyLevel: 'D2',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Cipher Wheel Inspection',
      dataPayload: 'WHEEL SHOWS: 7 positions with symbols: ⟁ ⧉ ⬡ ⧫ ⌬ ⍟ ⎔',
      visualType: 'cipher',
      whatTheySee: 'A physical cipher wheel with 7 symbol positions.',
      taskPrompt: 'Read the symbols in order.',
      intermediateOutput: '⟁ ⧉ ⬡ ⧫ ⌬ ⍟ ⎔',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Symbol-to-Number Mapper',
      dataPayload: 'CONVERSION: Glyph positions map to numbers from glyph key. 17th position on the wheel is relevant.',
      whatTheySee: 'Mapper showing symbol positions.',
      taskPrompt: 'Map the central symbol to a number.',
      intermediateOutput: 'The 4th symbol ⧫ = Memory = position 4, but value from P03 is 3425',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Cipher Unlock Terminal',
      dataPayload: 'DECRYPTION KEY: [ _ _ _ _ ]',
      whatTheySee: 'Four-digit terminal.',
      taskPrompt: 'Submit the decrypted code.',
      intermediateOutput: 'Submit: 3425',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal shows execution interface for P15.',
      operatorTaskDescription:
        'Observer reads the cipher wheel. Analyst maps symbols. Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Reads the 7 symbols on the cipher wheel.',
        analystDiscovery: 'Maps symbols to the known code 3425.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports the cipher wheel symbols.',
      analystTransforms: 'Analyst maps to known code 3425.',
      operatorExecutes: 'Operator submits 3425.',
    },
    failurePropagation: {
      wrongStep: 'Team tries to derive the code from symbols alone.',
      consequence: 'Code mismatch.',
      recoveryGuidance: 'The code connects to P03.',
    },
    hints: [
      'The cipher wheel has 7 symbols in order.',
      'Recall the code from P03.',
      'Submit 3425.',
    ],
    fullSolution:
      'The cipher wheel confirms the symbol order. The code from P03 (3425) is the decryption key. Submitting 3425 unlocks P16.',
    whyTeamworkMatters: 'Reinforces cross-puzzle connections.',
    storyReveal: 'Terminal: "CIPHER VERIFIED. THE THIRD SYMBOL IS REVEALED."',
    locationClue: {
      format: 'Symbol',
      clueText: 'LINA\'S NOTE: "Find the ⧫ symbol on campus. Check the library book return area."',
      solution: 'Library Book Return Symbol',
      nextPhysicalLocation: '[LIBRARY] — Book Return Symbol',
      nextQrNode: 'QR-NODE-18',
      explanation: 'Points to the ⧫ symbol at library book return.',
    },
    evidenceUnlocked: {
      id: 'EVID-P15',
      category: 'Visual',
      title: 'Memory Symbol',
      state: 'RECOVERED',
      content: 'A carving of ⧫ with the word MEMORY below it.',
      timestamp: 'Stage 3',
      source: 'Library book return',
    },
    prerequisiteNodes: ['P14'],
    nextNodes: ['P16'],
    branchConditions: [],
    points: 40,
  },
  {
    id: 'P16',
    code: 'P16',
    name: 'The Auditorium',
    stage: 3,
    type: 'OBSERVATION',
    difficulty: 3,
    time: '6m',
    location: '[SCIENCE BUILDING] — Main Auditorium',
    feeds: 'P15',
    unlocks: 'P17',
    acceptedAnswer: '15',
    validationMethod: 'exact',
    narrativeObjective: 'Count the correct number of auditorium seats in Section B.',
    roleDependencyLevel: 'D1',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Auditorium Seating Plan',
      dataPayload: 'SECTION B: Rows 1-10, each with 15 seats. But only odd rows have occupied seats.',
      visualType: 'observation',
      whatTheySee: 'Auditorium seating with Section B visible.',
      taskPrompt: 'Count seats in Section B, Row 7.',
      intermediateOutput: '15',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Seat Counter',
      dataPayload: 'COUNT: Row 7 has 15 seats (same as all rows).',
      whatTheySee: 'Counter showing 15.',
      taskPrompt: 'Verify the count.',
      intermediateOutput: '15',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Seat Verification Terminal',
      dataPayload: 'SEAT COUNT: [ _ _ ]',
      whatTheySee: 'Two-digit terminal.',
      taskPrompt: 'Submit the count.',
      intermediateOutput: 'Submit: 15',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal shows execution interface for P16.',
      operatorTaskDescription: 'Observer counts seats. Analyst verifies. Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Counts 15 seats in Row 7.',
        analystDiscovery: 'Confirms 15.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer counts 15 seats.',
      analystTransforms: 'Analyst confirms: 15.',
      operatorExecutes: 'Operator submits 15.',
    },
    failurePropagation: {
      wrongStep: 'Team counts sections or rows instead of seats.',
      consequence: 'Wrong number.',
      recoveryGuidance: 'Count individual seats in one row.',
    },
    hints: ['Count seats in Row 7 of Section B.', 'All rows have the same seat count.', 'Submit 15.'],
    fullSolution: 'Counting seats in Row 7 shows 15. Submitting 15 unlocks P17.',
    whyTeamworkMatters: 'Simple but tests careful observation.',
    storyReveal: 'Terminal: "COUNT VERIFIED. THE FOURTH SYMBOL IS REVEALED."',
    locationClue: {
      format: 'Poetic',
      clueText: 'LINA\'S NOTE: "Behind the auditorium stage, find the fourth glyph carved in wood."',
      solution: 'Auditorium Stage Fourth Glyph',
      nextPhysicalLocation: '[SCIENCE BUILDING] — Stage Fourth Glyph',
      nextQrNode: 'QR-NODE-19',
      explanation: 'Points to the fourth glyph behind the stage.',
    },
    evidenceUnlocked: {
      id: 'EVID-P16',
      category: 'Visual',
      title: 'Fourth Symbol — Choice',
      state: 'RECOVERED',
      content: 'A wooden carving of ⌬ with the word CHOICE below it.',
      timestamp: 'Stage 3',
      source: 'Behind auditorium stage',
    },
    prerequisiteNodes: ['P15'],
    nextNodes: ['P17'],
    branchConditions: [],
    points: 35,
  },
  {
    id: 'P17',
    code: 'P17',
    name: 'The Audio Log',
    stage: 3,
    type: 'AUDIO',
    difficulty: 4,
    time: '8m',
    location: '[SCIENCE BUILDING] — Auditorium Stage',
    feeds: 'P16',
    unlocks: 'P18',
    acceptedAnswer: 'ECHO',
    validationMethod: 'case_insensitive',
    narrativeObjective: 'Decode the hidden message in the audio frequency spectrum.',
    roleDependencyLevel: 'D2',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Audio Spectrum Viewer',
      dataPayload: 'SPECTRUM: Frequency peaks at 1747 Hz, 2147 Hz. Ratio: 17/21.',
      visualType: 'audio',
      whatTheySee: 'Audio spectrum with two prominent frequency peaks.',
      taskPrompt: 'Report the peak frequencies.',
      intermediateOutput: '1747 Hz and 2147 Hz',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Frequency Decoder',
      dataPayload: 'DECODING: 17:47 (from P02/P07) reversed = ECHO. The frequencies are time-encoded.',
      whatTheySee: 'Decoder showing ECHO.',
      taskPrompt: 'Decode the time reference.',
      intermediateOutput: 'ECHO',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Audio Unlock Terminal',
      dataPayload: 'HIDDEN WORD: [ _ _ _ _ ]',
      whatTheySee: 'Four-letter terminal.',
      taskPrompt: 'Submit the decoded word.',
      intermediateOutput: 'Submit: ECHO',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal shows execution interface for P17.',
      operatorTaskDescription:
        'Observer reads audio spectrum. Analyst decodes frequency to word. Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Reads frequencies 1747 and 2147 Hz.',
        analystDiscovery: 'Decodes as ECHO from time reference 17:47.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports frequencies 1747, 2147.',
      analystTransforms: 'Analyst decodes: 17:47 reversed = ECHO.',
      operatorExecutes: 'Operator submits ECHO.',
    },
    failurePropagation: {
      wrongStep: 'Team submits "1747" or "TIME".',
      consequence: 'Word validation fails.',
      recoveryGuidance: 'Reverse the time 17:47.',
    },
    hints: ['The frequencies encode a time reference.', 'Recall 17:47 from Stage 2.', 'Reverse it: ECHO.'],
    fullSolution: 'Frequencies 1747/2147 encode 17:47, reversed gives ECHO. Submitting ECHO unlocks P18.',
    whyTeamworkMatters: 'Requires cross-referencing Stage 2 time puzzle.',
    storyReveal: 'Terminal: "ECHO CONFIRMED. THE FIFTH SYMBOL IS FOUND."',
    locationClue: {
      format: 'Symbol',
      clueText: 'LINA\'S NOTE: "Find the fifth glyph in the library reading room. It is ⍟."',
      solution: 'Library Reading Room Fifth Symbol',
      nextPhysicalLocation: '[LIBRARY] — Reading Room Fifth Symbol',
      nextQrNode: 'QR-NODE-20',
      explanation: 'Points to the fifth symbol in the reading room.',
    },
    evidenceUnlocked: {
      id: 'EVID-P17',
      category: 'Visual',
      title: 'Fifth Symbol — Truth',
      state: 'RECOVERED',
      content: 'A carved symbol: ⍟. Below it reads: TRUTH.',
      timestamp: 'Stage 3',
      source: 'Library reading room',
    },
    prerequisiteNodes: ['P16'],
    nextNodes: ['P18'],
    branchConditions: [],
    points: 50,
  },
  {
    id: 'P18',
    code: 'P18',
    name: 'The Pattern Lock',
    stage: 3,
    type: 'PATTERN',
    difficulty: 3,
    time: '6m',
    location: '[LIBRARY] — Reading Room Fifth Symbol',
    feeds: 'P17',
    unlocks: 'P19',
    acceptedAnswer: '3425',
    validationMethod: 'exact',
    narrativeObjective: 'Enter the pattern lock using the recurring code.',
    roleDependencyLevel: 'D1',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Pattern Lock Screen',
      dataPayload: 'LOCK: 4-digit pattern. Symbols around show: ⟁ ⧉ ⬡ ⧫ ⌬ ⍟ ⎔',
      visualType: 'pattern',
      whatTheySee: 'A 4-digit lock with symbol markers around it.',
      taskPrompt: 'The code is the recurring one from P03/P13/P15.',
      intermediateOutput: '3425',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Pattern Validator',
      dataPayload: 'VALIDATION: The recurring code across stages is 3425.',
      whatTheySee: 'Validator showing 3425.',
      taskPrompt: 'Confirm the code.',
      intermediateOutput: '3425',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Pattern Entry Terminal',
      dataPayload: 'ENTER CODE: [ _ _ _ _ ]',
      whatTheySee: '4-digit entry terminal.',
      taskPrompt: 'Submit the code.',
      intermediateOutput: 'Submit: 3425',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal shows execution interface for P18.',
      operatorTaskDescription: 'Recall the recurring code.',
      requiredDiscoveries: {
        observerDiscovery: 'Sees the 4-digit lock.',
        analystDiscovery: 'Confirms 3425.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer identifies the pattern lock.',
      analystTransforms: 'Analyst confirms: 3425.',
      operatorExecutes: 'Operator submits 3425.',
    },
    failurePropagation: {
      wrongStep: 'Team enters different recurring number.',
      consequence: 'Lock resets.',
      recoveryGuidance: 'Think P03, P13, P15.',
    },
    hints: ['This code appeared multiple times.', 'It was the P03 PIN.', 'Submit 3425.'],
    fullSolution: 'The pattern lock accepts the recurring code 3425 from earlier puzzles.',
    whyTeamworkMatters: 'Tests retention of recurring patterns.',
    storyReveal: 'Terminal: "PASSWORDS MATCH. THE SIXTH SYMBOL REMAINS."',
    locationClue: {
      format: 'Symbol',
      clueText: 'LINA\'S NOTE: "Check the campus sculpture garden for the final symbol."',
      solution: 'Campus Sculpture Garden',
      nextPhysicalLocation: '[CAMPUS] — Sculpture Garden',
      nextQrNode: 'QR-NODE-21',
      explanation: 'Points to the campus sculpture garden.',
    },
    evidenceUnlocked: {
      id: 'EVID-P18',
      category: 'Visual',
      title: 'Sixth Symbol',
      state: 'RECOVERED',
      content: 'No symbol found. Instead a note: "The seventh is not a glyph but a concept: FINALITY."',
      timestamp: 'Stage 3',
      source: 'Sculpture garden plaque',
    },
    prerequisiteNodes: ['P17'],
    nextNodes: ['P19'],
    branchConditions: [],
    points: 40,
  },
  {
    id: 'P19',
    code: 'P19',
    name: 'The Archive',
    stage: 3,
    type: 'DEDUCTION',
    difficulty: 4,
    time: '7m',
    location: '[CAMPUS] — Sculpture Garden',
    feeds: 'P18',
    unlocks: 'P20',
    acceptedAnswer: 'SUBMERGE',
    validationMethod: 'case_insensitive',
    narrativeObjective: 'Deduce what action the sculpture garden reveals.',
    roleDependencyLevel: 'D3',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Sculpture Garden Inspection',
      dataPayload: 'SCULPTURE: A bronze hand holding a sphere underwater, half-submerged.',
      visualType: 'observation',
      whatTheySee: 'A bronze sculpture of a hand holding a partially submerged sphere.',
      taskPrompt: 'Describe the sphere\'s position.',
      intermediateOutput: 'Half underwater',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Action Word Deriver',
      dataPayload: 'DERIVATION: What do you do to something partially underwater? SUBMERGE.',
      whatTheySee: 'Word deriver showing SUBMERGE.',
      taskPrompt: 'Derive the action word.',
      intermediateOutput: 'SUBMERGE',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Sculpture Activation Terminal',
      dataPayload: 'ACTION VERB: [ _ _ _ _ _ _ _ _ ]',
      whatTheySee: 'Eight-letter terminal.',
      taskPrompt: 'Submit the action verb.',
      intermediateOutput: 'Submit: SUBMERGE',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal shows execution interface for P19.',
      operatorTaskDescription:
        'Observer sees the sculpture. Analyst derives the action word. Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Sees half-submerged sphere.',
        analystDiscovery: 'Derives SUBMERGE.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer describes half-submerged sphere.',
      analystTransforms: 'Analyst derives: SUBMERGE.',
      operatorExecutes: 'Operator submits SUBMERGE.',
    },
    failurePropagation: {
      wrongStep: 'Team submits "UNDERWATER" or "WATER".',
      consequence: 'Not an action verb.',
      recoveryGuidance: 'What do you DO to something? SUBMERGE.',
    },
    hints: ['The sphere is partially underwater.', 'What verb describes that action?', 'Submit SUBMERGE.'],
    fullSolution: 'The sculpture shows a half-submerged sphere. The action is SUBMERGE. Submitting SUBMERGE unlocks P20.',
    whyTeamworkMatters: 'Requires interpretation of physical form into language.',
    storyReveal: 'Terminal: "ACTION VERIFIED. THE SEVENTH SYMBOL IS REVEALED."',
    locationClue: {
      format: 'Symbol',
      clueText: 'LINA\'S NOTE: "The seventh and final symbol is ⎔ — FINALITY. It rests atop the Admin Building dome."',
      solution: 'Admin Building Dome',
      nextPhysicalLocation: '[ADMIN BUILDING] — Building Dome',
      nextQrNode: 'QR-NODE-22',
      explanation: 'Points to the Admin Building dome for the seventh symbol.',
    },
    evidenceUnlocked: {
      id: 'EVID-P19',
      category: 'Visual',
      title: 'Seventh Symbol — Finality',
      state: 'RECOVERED',
      content: 'A weathervane on the dome: ⎔. Below it reads: FINALITY. All seven symbols collected: ⟁ ⧉ ⬡ ⧫ ⌬ ⍟ ⎔.',
      timestamp: 'Stage 3',
      source: 'Admin Building dome',
    },
    prerequisiteNodes: ['P18'],
    nextNodes: ['P20'],
    branchConditions: [],
    points: 50,
  },
  {
    id: 'P20',
    code: 'P20',
    name: 'The Symbol Sequence',
    stage: 3,
    type: 'PATTERN',
    difficulty: 5,
    time: '10m',
    location: '[ADMIN BUILDING] — Building Dome',
    feeds: 'P19',
    unlocks: 'P21',
    acceptedAnswer: '2147',
    validationMethod: 'exact',
    narrativeObjective: 'Arrange all seven symbols in the correct order using all clues collected.',
    roleDependencyLevel: 'D4',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Symbol Arrangement Panel',
      dataPayload: 'PANEL: Seven slots for symbols. Clue: "The sequence follows the order of discovery."',
      visualType: 'puzzle',
      interactiveData: {
        symbols: ['⟁', '⧉', '⬡', '⧫', '⌬', '⍟', '⎔'],
        hint: 'Order of discovery: Origin, Connection, Structure, Memory, Choice, Truth, Finality.',
      },
      whatTheySee: 'A panel with 7 symbol slots and the collected symbols.',
      taskPrompt: 'Arrange symbols by discovery order.',
      intermediateOutput: '⟁ ⧉ ⬡ ⧫ ⌬ ⍟ ⎔',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Position Cipher Calculator',
      dataPayload: 'CALCULATION: ⧉ is position 2. ⍟ is position 6. The key is 2147: 2-1-4-7 (positions of Connection, Origin, Structure, Finality).',
      whatTheySee: 'Calculator showing position extraction: 2,1,4,7 = 2147.',
      taskPrompt: 'Extract the position numbers.',
      intermediateOutput: '2147',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Sequence Unlock Terminal',
      dataPayload: 'SEQUENCE CODE: [ _ _ _ _ ]',
      whatTheySee: 'Four-digit terminal.',
      taskPrompt: 'Submit the sequence.',
      intermediateOutput: 'Submit: 2147',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal shows the execution interface for P20.',
      operatorTaskDescription:
        'The Observer arranges symbols by discovery order. The Analyst extracts position numbers. The Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Arranges symbols in discovery order.',
        analystDiscovery: 'Extracts position numbers to form 2147.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer arranges all 7 symbols in discovery order.',
      analystTransforms: 'Analyst extracts key positions: 2-1-4-7 = 2147.',
      operatorExecutes: 'Operator submits 2147.',
    },
    failurePropagation: {
      wrongStep: 'Team uses wrong order or extracts wrong positions.',
      consequence: 'Sequence rejected.',
      recoveryGuidance: 'Positions: ⧉=2, ⟁=1, ⬡=4, ⎔=7.',
    },
    hints: [
      'Arrange symbols by when you first discovered them.',
      'Extract the position numbers of key symbols.',
      'Connection=2, Origin=1, Structure=4, Finality=7. Submit 2147.',
    ],
    fullSolution:
      'Arranging symbols by discovery order and extracting key positions yields 2147. Submitting 2147 unlocks P21.',
    whyTeamworkMatters: 'Synthesizes all seven symbols collected across Stage 3.',
    storyReveal: 'Terminal: "SYMBOLS UNIFIED. THE FINAL STAGE AWAITS."',
    locationClue: {
      format: 'Path Instruction',
      clueText: 'LINA\'S NOTE: "Return to the Admin Building main doors. The fourth floor window has a view."',
      solution: 'Admin Building Fourth Floor Window',
      nextPhysicalLocation: '[ADMIN BUILDING] — Fourth Floor Window',
      nextQrNode: 'QR-NODE-23',
      explanation: 'Points to the fourth floor window.',
    },
    evidenceUnlocked: {
      id: 'EVID-P20',
      category: 'Visual',
      title: 'Stage 2→3 Transition Clue',
      state: 'RECOVERED',
      content:
        'A note: "The answer 2147 is not just a number — it is also 17:47 in a different base. Keep this in mind for the rooftop."',
      timestamp: 'Stage 3',
      source: 'Dome base',
    },
    prerequisiteNodes: ['P19'],
    nextNodes: ['P21'],
    branchConditions: [],
    points: 70,
  },
  {
    id: 'P21',
    code: 'P21',
    name: 'The Final Clue',
    stage: 3,
    type: 'NARRATIVE_INVESTIGATION',
    difficulty: 5,
    time: '8m',
    location: '[ADMIN BUILDING] — Fourth Floor Window',
    feeds: 'P20',
    unlocks: 'M03',
    acceptedAnswer: 'ARCHIVE',
    validationMethod: 'case_insensitive',
    narrativeObjective: 'Read Lina\'s final message for Stage 3.',
    roleDependencyLevel: 'D3',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Window Message',
      dataPayload: 'MESSAGE: "The archive holds what the symbols cannot say."',
      visualType: 'observation',
      whatTheySee: 'A note taped to the window.',
      taskPrompt: 'Report the message.',
      intermediateOutput: 'The archive holds what the symbols cannot say.',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Message Interpreter',
      dataPayload: 'INTERPRETATION: Archive = storage. The concept is ARCHIVE.',
      whatTheySee: 'Interpreter highlighting ARCHIVE.',
      taskPrompt: 'Extract the key concept.',
      intermediateOutput: 'ARCHIVE',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Final Stage Terminal',
      dataPayload: 'STORAGE CONCEPT: [ _ _ _ _ _ _ _ ]',
      whatTheySee: 'Seven-letter terminal.',
      taskPrompt: 'Submit the concept.',
      intermediateOutput: 'Submit: ARCHIVE',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal shows the execution interface for P21.',
      operatorTaskDescription: 'Read the window message. Extract concept.',
      requiredDiscoveries: {
        observerDiscovery: 'Reads the window message.',
        analystDiscovery: 'Extracts ARCHIVE.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reads the message.',
      analystTransforms: 'Analyst extracts: ARCHIVE.',
      operatorExecutes: 'Operator submits ARCHIVE.',
    },
    failurePropagation: {
      wrongStep: 'Team submits "SYMBOLS" or "WINDOW".',
      consequence: 'Concept mismatch.',
      recoveryGuidance: 'The message is about where things are stored.',
    },
    hints: ['The message speaks of storage.', 'What is another word for archive?', 'Submit ARCHIVE.'],
    fullSolution: 'The window message speaks of the archive. Submitting ARCHIVE unlocks M03.',
    whyTeamworkMatters: 'Final Stage 3 node that ties all symbols together narratively.',
    storyReveal: 'Terminal: "ARCHIVE ACCESSIBLE. STAGE 3 COMPLETE."',
    locationClue: {
      format: 'Symbol',
      clueText: 'LINA\'S NOTE: "The rooftop spire awaits your return for Stage 5."',
      solution: 'Rooftop Spire Access',
      nextPhysicalLocation: '[ROOFTOP] — Spire Access',
      nextQrNode: 'QR-NODE-24',
      explanation: 'Points toward Stage 5 start at the rooftop.',
    },
    evidenceUnlocked: {
      id: 'FRAG-03',
      category: 'Symbol Fragment',
      title: 'Fragment 3 — Mirror',
      state: 'RECOVERED',
      content:
        'The third fragment. The word MIRROR appears: "The path you took reflects the path you avoided. Both are true."',
      timestamp: 'Stage 3',
      source: 'Window ledge',
    },
    prerequisiteNodes: ['P20'],
    nextNodes: ['M03'],
    branchConditions: [],
    points: 65,
  },
]

// P22-P29 and M04 are defined in stage-4.ts
// The following are the continuation of the progression chain from P21
export const STAGE_3_CONTINUATION: Partial<Record<string, string>> = {
  P21: 'M03',
  M03: 'M03_unlocks_P22',
}
