/**
 * NEXUS — Stage 1 Puzzles (P01-P05, M01)
 * Introductory puzzles that establish core mechanics and symbols.
 */

import type { PuzzleNode } from '../../../types/game-engine'

export const STAGE_1_PUZZLES: PuzzleNode[] = [
  {
    id: 'P01',
    code: 'P01',
    name: 'The Facade',
    stage: 1,
    type: 'OBSERVATION',
    difficulty: 2,
    time: '6m',
    location: '[ADMIN BUILDING] — Main Entrance Facade',
    feeds: 'M01',
    unlocks: 'P02',
    acceptedAnswer: 'CDFDEFF',
    validationMethod: 'exact',
    narrativeObjective: 'Decode the architectural symbols carved into the Main Entrance facade.',
    roleDependencyLevel: 'D2',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Facade Observation Log',
      dataPayload: 'FACADE SYMBOL GRID: 8 columns of carved stone symbols visible on the Main Entrance.',
      visualType: 'visual',
      whatTheySee: 'A row of stone glyphs above the entrance. Each glyph appears multiple times.',
      taskPrompt: 'Read the facade from left to right and report the glyph sequence.',
      intermediateOutput: 'Column 1 glyph, Column 2 glyph, ... etc.',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Glyph Decomposition Terminal',
      dataPayload: 'DECODING INSTRUCTIONS: Convert each glyph to a single letter using the substitution key.',
      whatTheySee: 'A cipher wheel mapping 8 glyph shapes to letters.',
      taskPrompt: 'Apply the substitution to each glyph.',
      intermediateOutput: 'C D F D E F F',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Facade Authentication Terminal',
      dataPayload: 'ENTRANCE CODE: [ _ _ _ _ _ _ _ ]',
      whatTheySee: 'Terminal at the base of the facade requiring a 7-character code.',
      taskPrompt: 'Submit the decoded glyph sequence.',
      intermediateOutput: 'Submit: CDFDEFF',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P01.',
      operatorTaskDescription:
        'The Observer reports glyph shapes from the physical facade. The Analyst applies the substitution cipher. The Operator submits the combined result. No single role holds the complete answer.',
      requiredDiscoveries: {
        observerDiscovery: 'Reads the 8 facade glyphs left to right.',
        analystDiscovery: 'Applies the substitution key to convert glyphs to letters.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reads: glyph glyph glyph glyph glyph glyph glyph glyph.',
      analystTransforms: 'Analyst converts each glyph to its letter: C D F D E F F.',
      operatorExecutes: 'Operator enters CDFDEFF at the facade terminal.',
    },
    failurePropagation: {
      wrongStep: 'Analyst misreads the glyph order.',
      consequence: 'Entry rejected — no access granted to P02.',
      recoveryGuidance: 'Check the substitution key again, starting from the leftmost column.',
    },
    hints: [
      'The facade above the entrance has 7 visible glyph positions.',
      'Use the cipher key on your device to map each glyph to a letter.',
      'The first two letters are C and D.',
    ],
    fullSolution:
      'Reading the facade glyphs left to right and applying the substitution cipher yields C-D-F-D-E-F-F. Submitting CDFDEFF unlocks the path to P02.',
    whyTeamworkMatters:
      'Physical observation and cryptographic decoding must be combined — the Analyst cannot solve without the Observer, and the Operator cannot act without both.',
    storyReveal:
      'Facade terminal: "ACCESS GRANTED. PROCEED TO ARCHIVE WING."',
    locationClue: {
      format: 'Map Marker',
      clueText: 'LINA\'S NOTE: "From the facade, walk through the main doors into the Lobby. The first archive alcove is on your left."',
      solution: 'Main Building Lobby Archive Alcove',
      nextPhysicalLocation: '[ADMIN BUILDING] — Lobby Archive Alcove',
      nextQrNode: 'QR-NODE-02',
      explanation: 'Directs teams from the entrance facade into the archive alcove.',
    },
    evidenceUnlocked: {
      id: 'EVID-P01',
      category: 'Document',
      title: 'Archive Building Floor Plan (1974)',
      state: 'RECOVERED',
      timestamp: 'Stage 1',
      source: 'Archive alcove',
      content:
        'A hand-drawn floor plan showing a route to the "Decommissioned Security Office" in the basement. The path goes through the library basement.',
    },
    prerequisiteNodes: [],
    nextNodes: ['P02'],
    branchConditions: [],
    points: 50,
  },
  {
    id: 'P02',
    code: 'P02',
    name: 'The Clock',
    stage: 1,
    type: 'SPATIAL',
    difficulty: 2,
    time: '5m',
    location: '[ADMIN BUILDING] — Lobby Clock Tower',
    feeds: 'P01',
    unlocks: 'P03',
    acceptedAnswer: '21:47',
    validationMethod: 'exact',
    narrativeObjective: 'Determine the time shown on the lobby clock tower when viewed from a specific angle.',
    roleDependencyLevel: 'D2',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Clock Tower Viewing Angle',
      dataPayload: 'OBSERVATION: The clock face shows 9:47 when viewed from the east side.',
      visualType: 'observation',
      whatTheySee: 'A vintage clock face with Roman numerals. One hand points at IX, the other at VII.',
      taskPrompt: 'Read the clock face from the east-side viewing angle.',
      intermediateOutput: '9:47',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Time Conversion Calculator',
      dataPayload: 'FORMULA: East view time + 12 hours = military time.',
      whatTheySee: 'Conversion calculator showing 9:47 + 12:00 = 21:47.',
      taskPrompt: 'Convert the observed time to 24-hour format.',
      intermediateOutput: '21:47',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Clock Authentication Terminal',
      dataPayload: 'TIME LOCK: [ _ _ : _ _ ]',
      whatTheySee: 'Terminal with a digital time entry pad.',
      taskPrompt: 'Submit the converted time.',
      intermediateOutput: 'Submit: 21:47',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P02.',
      operatorTaskDescription:
        'The Observer reads the clock from a specific angle. The Analyst converts to 24-hour format. The Operator enters the result.',
      requiredDiscoveries: {
        observerDiscovery: 'Reads the clock face as 9:47 from the east side.',
        analystDiscovery: 'Converts 9:47 + 12 hours to military time: 21:47.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reads 9:47 from the east side.',
      analystTransforms: 'Analyst converts to 21:47.',
      operatorExecutes: 'Operator submits 21:47 at the clock terminal.',
    },
    failurePropagation: {
      wrongStep: 'Team reads the clock from the default angle (front: 21:47).',
      consequence: 'Terminal accepts but does not advance — angle-specific.',
      recoveryGuidance: 'The clock shows different times from different angles.',
    },
    hints: [
      'The clock in the lobby shows different numbers depending on your viewing angle.',
      'View from the east side. Apply the 12-hour offset.',
      'Submit 21:47.',
    ],
    fullSolution:
      'Reading the clock from the east side shows 9:47. Converting to 24-hour format gives 21:47. Submitting 21:47 unlocks P03.',
    whyTeamworkMatters: 'The spatial observation determines the raw data; the analyst transforms it; the operator executes.',
    storyReveal: 'Clock terminal: "TIME IS VERIFIED. THE PAST IS UNLOCKED."',
    locationClue: {
      format: 'Map Marker',
      clueText: 'LINA\'S NOTE: "Proceed to the Main Hall. The central staircase awaits."',
      solution: 'Main Hall Central Staircase',
      nextPhysicalLocation: '[MAIN HALL] — Central Staircase',
      nextQrNode: 'QR-NODE-03',
      explanation: 'Directs teams from the clock tower to the Main Hall.',
    },
    evidenceUnlocked: {
      id: 'EVID-P02',
      category: 'Document',
      title: 'Clock Maintenance Log — October 14, 2024',
      state: 'RECOVERED',
      timestamp: 'Stage 1',
      source: 'Behind the clock face',
      content:
        'Maintenance log entry: "22:45 — Clock manually set to 21:47 for synchronization event." The time 21:47 appears significant.',
    },
    prerequisiteNodes: ['P01'],
    nextNodes: ['P03'],
    branchConditions: [],
    points: 40,
  },
  {
    id: 'P03',
    code: 'P03',
    name: 'The Facade Pin',
    stage: 1,
    type: 'CIPHER',
    difficulty: 2,
    time: '4m',
    location: '[ADMIN BUILDING] — Facade Base Terminal',
    feeds: 'P02',
    unlocks: 'P04',
    acceptedAnswer: '3425',
    validationMethod: 'exact',
    narrativeObjective: 'Find the 4-digit PIN hidden in the facade symbols.',
    roleDependencyLevel: 'D2',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Facade Base Inspection',
      dataPayload: 'BASE DETAILS: Four worn brass plates near the facade steps each show a single digit.',
      visualType: 'visual',
      whatTheySee: 'Four brass plates embedded in the steps: 3, 4, 2, 5.',
      taskPrompt: 'Read the digits from left to right.',
      intermediateOutput: '3, 4, 2, 5',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'PIN Order Validator',
      dataPayload: 'ORDERING RULE: Digits are ordered by the facade glyph positions from P01.',
      whatTheySee: 'Position mapping: P01 glyphs C(3), D(4), F(2), E(5) map to positions.',
      taskPrompt: 'Verify the PIN ordering.',
      intermediateOutput: '3425',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Facade PIN Terminal',
      dataPayload: 'SECURITY CODE: [ _ _ _ _ ]',
      whatTheySee: 'Four-digit keypad terminal.',
      taskPrompt: 'Submit the 4-digit PIN.',
      intermediateOutput: 'Submit: 3425',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P03.',
      operatorTaskDescription:
        'The Observer reads the brass plate digits. The Analyst verifies ordering. The Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Reads four brass plates: 3, 4, 2, 5.',
        analystDiscovery: 'Verifies ordering matches P01 glyph positions.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports 3, 4, 2, 5 from the brass plates.',
      analystTransforms: 'Analyst confirms the PIN is 3425.',
      operatorExecutes: 'Operator submits 3425 at the facade terminal.',
    },
    failurePropagation: {
      wrongStep: 'PIN entered in wrong order.',
      consequence: 'Access denied.',
      recoveryGuidance: 'The order follows the P01 glyph sequence.',
    },
    hints: [
      'Look at the brass plates near the facade steps.',
      'The PIN is connected to your P01 solution.',
      'Submit 3425.',
    ],
    fullSolution:
      'Reading the four brass plates gives 3-4-2-5. Submitting 3425 unlocks P04.',
    whyTeamworkMatters: 'Connects back to P01, requiring the team to maintain cross-puzzle context.',
    storyReveal: 'Terminal: "PIN ACCEPTED. ARCHIVE ACCESS GRANTED."',
    locationClue: {
      format: 'Document',
      clueText: 'LINA\'S NOTE: "The archive contains a poster about a 2021 student project. Look at the dates."',
      solution: 'Archive Poster Examination',
      nextPhysicalLocation: '[ADMIN BUILDING] — Archive Poster Wall',
      nextQrNode: 'QR-NODE-04',
      explanation: 'Points to the archive poster wall.',
    },
    evidenceUnlocked: {
      id: 'EVID-P03',
      category: 'Document',
      title: 'Archive Poster: NEXUS Project Initiation (2021)',
      state: 'RECOVERED',
      timestamp: 'Stage 1',
      source: 'Archive poster wall',
      content:
        'The poster shows 3 key figures: Dr. Vey, Prof. Carter, and a third figure marked TBA. A note reads: "The key to the future is the 6th letter."',
    },
    prerequisiteNodes: ['P02'],
    nextNodes: ['P04'],
    branchConditions: [],
    points: 35,
  },
  {
    id: 'P04',
    code: 'P04',
    name: 'The Poster Dates',
    stage: 1,
    type: 'PATTERN',
    difficulty: 3,
    time: '7m',
    location: '[ADMIN BUILDING] — Archive Poster Wall',
    feeds: 'P03',
    unlocks: 'P05',
    acceptedAnswer: 'F',
    validationMethod: 'exact',
    narrativeObjective: 'Find the hidden letter in the dates on the NEXUS project poster.',
    roleDependencyLevel: 'D2',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Poster Date Investigation',
      dataPayload: 'POSTER DATES: 2021-03-15, 2021-06-22, 2021-09-08, 2021-12-01',
      visualType: 'document-forensics',
      whatTheySee: 'Four dates arranged in a vertical list on the poster.',
      taskPrompt: 'Report the four dates to the Analyst.',
      intermediateOutput: '2021-03-15, 2021-06-22, 2021-09-08, 2021-12-01',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Date Pattern Analyzer',
      dataPayload: 'ANALYSIS: Day-of-month sequence: 15, 22, 08, 01. Difference pattern: +7, -14, -7. Next would be -14: 01-14 = -13 (mod 31 = 18). But the poster text says "6th letter".',
      whatTheySee: 'Pattern analyzer highlighting the note "the 6th letter".',
      taskPrompt: 'What is the 6th letter of the alphabet?',
      intermediateOutput: 'F',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Archive Access Terminal',
      dataPayload: 'HIDDEN VARIABLE: [ _ ]',
      whatTheySee: 'Single-character terminal.',
      taskPrompt: 'Submit the single letter.',
      intermediateOutput: 'Submit: F',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P04.',
      operatorTaskDescription:
        'The Observer reads the poster dates. The Analyst finds the hidden note about the "6th letter". The Operator submits the letter.',
      requiredDiscoveries: {
        observerDiscovery: 'Reads the four dates on the poster.',
        analystDiscovery: 'Finds the note "the 6th letter" and counts: A-B-C-D-E-F.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports the four dates.',
      analystTransforms: 'Analyst finds the hidden note and calculates the 6th letter: F.',
      operatorExecutes: 'Operator submits F at the archive terminal.',
    },
    failurePropagation: {
      wrongStep: 'Team counts from 0 instead of 1 (gives E).',
      consequence: 'Archive access denied.',
      recoveryGuidance: 'Alphabet: A=1, B=2, C=3, D=4, E=5, F=6.',
    },
    hints: [
      'The poster text says "the 6th letter". Count the alphabet.',
      'A=1, B=2, C=3, D=4, E=5, F=6.',
      'Submit F.',
    ],
    fullSolution:
      'The poster note says "the 6th letter". Counting A(1), B(2), C(3), D(4), E(5), F(6) gives F. Submitting F unlocks P05.',
    whyTeamworkMatters: 'Requires combining physical observation (dates) with cryptographic reasoning (letter count).',
    storyReveal: 'Terminal: "LETTER VERIFIED. THE THIRD FIGURE IS REVEALED."',
    locationClue: {
      format: 'Riddle',
      clueText: 'LINA\'S NOTE: "Look for the person who is not shown but whose initial completes the name."',
      solution: 'Hidden Third Figure Identification',
      nextPhysicalLocation: '[ADMIN BUILDING] — Archive Figure Display',
      nextQrNode: 'QR-NODE-05',
      explanation: 'Points to the archive figure display.',
    },
    evidenceUnlocked: {
      id: 'EVID-P04',
      category: 'Document',
      title: 'Project NEXUS — Team Roster',
      state: 'RECOVERED',
      timestamp: 'Stage 1',
      source: 'Behind the poster',
      content:
        'Roster: Dr. Lina Vey (Project Lead), Prof. Marcus Carter (Advisor). Third member: [REDACTED]. Initial: V.',
    },
    prerequisiteNodes: ['P03'],
    nextNodes: ['P05'],
    branchConditions: [],
    points: 30,
  },
  {
    id: 'P05',
    code: 'P05',
    name: 'The Third Figure',
    stage: 1,
    type: 'DEDUCTION',
    difficulty: 3,
    time: '6m',
    location: '[ADMIN BUILDING] — Archive Figure Display',
    feeds: 'P04',
    unlocks: 'M01',
    acceptedAnswer: 'VEY',
    validationMethod: 'case_insensitive',
    narrativeObjective: 'Deduce the full last name of the redacted third project member.',
    roleDependencyLevel: 'D2',
    observer: {
      role: 'OBSERVER',
      screenTitle: 'Figure Display Inspection',
      dataPayload: 'DISPLAY: Two photos visible. Third photo frame is empty but has an etched initial: V.',
      visualType: 'observation',
      whatTheySee: 'A display with three frames. The third frame is empty, showing only the letter V.',
      taskPrompt: 'Report the visible initial.',
      intermediateOutput: 'V',
    },
    analyst: {
      role: 'ANALYST',
      screenTitle: 'Name Reconstruction Engine',
      dataPayload: 'REASONING: Dr. Vey is the project lead. The roster says "Dr. Lina Vey". The third figure shares the last name Vey.',
      whatTheySee: 'Reconstruction showing "Lina Vey" from the lead role.',
      taskPrompt: 'What is the full last name?',
      intermediateOutput: 'VEY',
    },
    operator: {
      role: 'OPERATOR',
      screenTitle: 'Archive Identity Terminal',
      dataPayload: 'IDENTIFY REDACTED: [ _ _ _ ]',
      whatTheySee: 'Three-letter input terminal.',
      taskPrompt: 'Submit the last name.',
      intermediateOutput: 'Submit: VEY',
    },
    operatorInvestigation: {
      operatorOwnEvidence: 'Terminal screen shows the execution interface for P05.',
      operatorTaskDescription:
        'The Observer reads the etched initial V. The Analyst reconstructs the full name from the lead role. The Operator submits.',
      requiredDiscoveries: {
        observerDiscovery: 'Sees the initial V on the empty frame.',
        analystDiscovery: 'Deduces the last name from Dr. Lina Vey: VEY.',
      },
    },
    coordinationChain: {
      observerProduces: 'Observer reports the initial V.',
      analystTransforms: 'Analyst deduces the full name: VEY.',
      operatorExecutes: 'Operator submits VEY at the identity terminal.',
    },
    failurePropagation: {
      wrongStep: 'Team submits just "V" or "LINA".',
      consequence: 'Identity validation fails.',
      recoveryGuidance: 'Submit the full LAST NAME.',
    },
    hints: [
      'The redacted person is Dr. Lina Vey.',
      'The last name is 3 letters starting with V.',
      'Submit VEY.',
    ],
    fullSolution:
      'The empty frame shows V. The redacted member is Dr. Lina Vey. The last name is VEY. Submitting VEY unlocks Meta M01.',
    whyTeamworkMatters: 'Deduction requires both observation and reasoning to reconstruct hidden information.',
    storyReveal: 'Terminal: "IDENTITY RECONSTRUCTED. THE FIRST FRAGMENT AWAITS."',
    locationClue: {
      format: 'Symbol Key',
      clueText: 'LINA\'S NOTE: "The archive has a hidden compartment behind the third frame. Inside is your first fragment."',
      solution: 'Archive Hidden Compartment',
      nextPhysicalLocation: '[ADMIN BUILDING] — Archive Hidden Compartment',
      nextQrNode: 'QR-NODE-06',
      explanation: 'Points to the hidden compartment behind the third frame.',
    },
    evidenceUnlocked: {
      id: 'FRAG-01',
      category: 'Symbol Fragment',
      title: 'Fragment 1 — Vector',
      state: 'RECOVERED',
      timestamp: 'Stage 1',
      source: 'Archive hidden compartment',
      content:
        'The first of five narrative fragments. The word VECTOR appears: "The path diverges. One direction is a straight line; the other, a network. Choose the network."',
    },
    prerequisiteNodes: ['P04'],
    nextNodes: ['M01'],
    branchConditions: [],
    points: 45,
  },
]
