/**
 * NEXUS - Node Index (client)
 *
 * This is the ONLY puzzle data shipped to the browser, and it deliberately
 * contains no playable content: no role blocks, no coordination chain, no
 * hints, no location clues, no story text, and no answers.
 *
 * Everything a player actually sees comes from get_player_node_detail(),
 * which returns only the requesting role's own block and redacts the accepted
 * answer out of every player-visible string. Hints come one at a time from
 * request_hint(), which records the usage and charges the time penalty.
 * Answer validation happens entirely inside submit_puzzle_answer().
 *
 * What remains here is the skeleton needed to draw the node map before a node
 * is unlocked: which nodes exist, what they are called, where they are, and
 * what they depend on. A locked node's title and location are map furniture,
 * not a spoiler.
 */

export interface NodeIndexEntry {
  id: string
  code: string
  name: string
  stage: number
  type: string
  difficulty: number
  time: string
  location: string
  points: number
  prerequisiteNodes: string[]
  nextNodes: string[] | null
}

export const ALL_PUZZLES: NodeIndexEntry[] = [
  {
    id: 'P01',
    code: 'P01',
    name: 'The Facade',
    stage: 1,
    type: 'OBSERVATION',
    difficulty: 2,
    time: '6m',
    location: '[ADMIN BUILDING] — Main Entrance Facade',
    points: 50,
    prerequisiteNodes: [],
    nextNodes: ["P02"],
  },
  {
    id: 'P02',
    code: 'P02',
    name: 'The Clock',
    stage: 1,
    type: 'SPATIAL',
    difficulty: 2,
    time: '5m',
    location: '[ADMIN BUILDING] — Lobby Clock Tower',
    points: 40,
    prerequisiteNodes: ["P01"],
    nextNodes: ["P03"],
  },
  {
    id: 'P03',
    code: 'P03',
    name: 'The Facade Pin',
    stage: 1,
    type: 'CIPHER',
    difficulty: 2,
    time: '4m',
    location: '[ADMIN BUILDING] — Facade Base Terminal',
    points: 35,
    prerequisiteNodes: ["P02"],
    nextNodes: ["P04"],
  },
  {
    id: 'P04',
    code: 'P04',
    name: 'The Poster Dates',
    stage: 1,
    type: 'PATTERN',
    difficulty: 3,
    time: '7m',
    location: '[ADMIN BUILDING] — Archive Poster Wall',
    points: 30,
    prerequisiteNodes: ["P03"],
    nextNodes: ["P05"],
  },
  {
    id: 'P05',
    code: 'P05',
    name: 'The Third Figure',
    stage: 1,
    type: 'DEDUCTION',
    difficulty: 3,
    time: '6m',
    location: '[ADMIN BUILDING] — Archive Figure Display',
    points: 45,
    prerequisiteNodes: ["P04"],
    nextNodes: ["M01"],
  },
  {
    id: 'P06',
    code: 'P06',
    name: 'The Pivot',
    stage: 2,
    type: 'MEMORY',
    difficulty: 2,
    time: '5m',
    location: '[LIBRARY] — Stack Reference Desk',
    points: 40,
    prerequisiteNodes: ["M01"],
    nextNodes: ["P07"],
  },
  {
    id: 'P07',
    code: 'P07',
    name: 'The Binary',
    stage: 2,
    type: 'BINARY',
    difficulty: 3,
    time: '8m',
    location: '[LIBRARY] — Basement Server Rack',
    points: 50,
    prerequisiteNodes: ["P06"],
    nextNodes: ["P08"],
  },
  {
    id: 'P08',
    code: 'P08',
    name: 'The Vector',
    stage: 2,
    type: 'PATTERN',
    difficulty: 3,
    time: '7m',
    location: '[ADMIN BUILDING] — Archive Cabinet 3',
    points: 45,
    prerequisiteNodes: ["P07"],
    nextNodes: ["P09"],
  },
  {
    id: 'P09',
    code: 'P09',
    name: 'The Chronology',
    stage: 2,
    type: 'LOGIC',
    difficulty: 3,
    time: '8m',
    location: '[ADMIN BUILDING] — Clock Room',
    points: 50,
    prerequisiteNodes: ["P08"],
    nextNodes: ["P10"],
  },
  {
    id: 'P10',
    code: 'P10',
    name: 'The Blue Door',
    stage: 2,
    type: 'EXTRACTION',
    difficulty: 3,
    time: '6m',
    location: '[ADMIN BUILDING] — Blue-Marked Door',
    points: 35,
    prerequisiteNodes: ["P09"],
    nextNodes: ["P11"],
  },
  {
    id: 'P11',
    code: 'P11',
    name: 'The Symbol',
    stage: 2,
    type: 'VISUAL',
    difficulty: 3,
    time: '7m',
    location: '[ADMIN BUILDING] — Wall with Glowing Blue Symbol',
    points: 40,
    prerequisiteNodes: ["P10"],
    nextNodes: ["P12"],
  },
  {
    id: 'P12',
    code: 'P12',
    name: 'The Armrest',
    stage: 2,
    type: 'DEDUCTION',
    difficulty: 3,
    time: '6m',
    location: '[ADMIN BUILDING] — Lecture Hall Room 214',
    points: 35,
    prerequisiteNodes: ["P11"],
    nextNodes: ["P13"],
  },
  {
    id: 'P13',
    code: 'P13',
    name: 'The Laboratory',
    stage: 2,
    type: 'OBSERVATION',
    difficulty: 4,
    time: '10m',
    location: '[SCIENCE BUILDING] — Research Lab',
    points: 60,
    prerequisiteNodes: ["P12"],
    nextNodes: ["M02"],
  },
  {
    id: 'P06b',
    code: 'P06b',
    name: 'Time Remaining',
    stage: 2,
    type: 'MEMORY',
    difficulty: 1,
    time: '3m',
    location: '[SCIENCE BUILDING] — Lab Wall Clock',
    points: 30,
    prerequisiteNodes: ["P13"],
    nextNodes: ["P07b"],
  },
  {
    id: 'P07b',
    code: 'P07b',
    name: 'The Network',
    stage: 2,
    type: 'GRAPH',
    difficulty: 4,
    time: '9m',
    location: '[SCIENCE BUILDING] — Lab Network Diagram',
    points: 55,
    prerequisiteNodes: ["P06b"],
    nextNodes: ["M02"],
  },
  {
    id: 'P14',
    code: 'P14',
    name: 'The Memory Bank',
    stage: 3,
    type: 'MEMORY',
    difficulty: 3,
    time: '6m',
    location: '[SCIENCE BUILDING] — Memory Lab',
    points: 45,
    prerequisiteNodes: ["M02"],
    nextNodes: ["P15"],
  },
  {
    id: 'P15',
    code: 'P15',
    name: 'The Cipher Wheel',
    stage: 3,
    type: 'CIPHER',
    difficulty: 3,
    time: '7m',
    location: '[LIBRARY] — Entrance Symbol Wall',
    points: 40,
    prerequisiteNodes: ["P14"],
    nextNodes: ["P16"],
  },
  {
    id: 'P16',
    code: 'P16',
    name: 'The Auditorium',
    stage: 3,
    type: 'OBSERVATION',
    difficulty: 3,
    time: '6m',
    location: '[SCIENCE BUILDING] — Main Auditorium',
    points: 35,
    prerequisiteNodes: ["P15"],
    nextNodes: ["P17"],
  },
  {
    id: 'P17',
    code: 'P17',
    name: 'The Audio Log',
    stage: 3,
    type: 'AUDIO',
    difficulty: 4,
    time: '8m',
    location: '[SCIENCE BUILDING] — Auditorium Stage',
    points: 50,
    prerequisiteNodes: ["P16"],
    nextNodes: ["P18"],
  },
  {
    id: 'P18',
    code: 'P18',
    name: 'The Pattern Lock',
    stage: 3,
    type: 'PATTERN',
    difficulty: 3,
    time: '6m',
    location: '[LIBRARY] — Reading Room Fifth Symbol',
    points: 40,
    prerequisiteNodes: ["P17"],
    nextNodes: ["P19"],
  },
  {
    id: 'P19',
    code: 'P19',
    name: 'The Archive',
    stage: 3,
    type: 'DEDUCTION',
    difficulty: 4,
    time: '7m',
    location: '[CAMPUS] — Sculpture Garden',
    points: 50,
    prerequisiteNodes: ["P18"],
    nextNodes: ["P20"],
  },
  {
    id: 'P20',
    code: 'P20',
    name: 'The Symbol Sequence',
    stage: 3,
    type: 'PATTERN',
    difficulty: 5,
    time: '10m',
    location: '[ADMIN BUILDING] — Building Dome',
    points: 70,
    prerequisiteNodes: ["P19"],
    nextNodes: ["P21"],
  },
  {
    id: 'P21',
    code: 'P21',
    name: 'The Final Clue',
    stage: 3,
    type: 'NARRATIVE_INVESTIGATION',
    difficulty: 5,
    time: '8m',
    location: '[ADMIN BUILDING] — Fourth Floor Window',
    points: 65,
    prerequisiteNodes: ["P20"],
    nextNodes: ["M03"],
  },
  {
    id: 'M01',
    code: 'M01',
    name: 'The First Lock',
    stage: 1,
    type: 'META',
    difficulty: 4,
    time: '12m',
    location: '[ADMIN BUILDING] — Central Archive',
    points: 80,
    prerequisiteNodes: ["P05"],
    nextNodes: ["P06"],
  },
  {
    id: 'M02',
    code: 'M02',
    name: 'The Network Meta',
    stage: 2,
    type: 'META',
    difficulty: 4,
    time: '15m',
    location: '[SCIENCE BUILDING] — Memory Lab',
    points: 100,
    prerequisiteNodes: ["P13"],
    nextNodes: ["P14"],
  },
  {
    id: 'M03',
    code: 'M03',
    name: 'The Symbol Meta',
    stage: 3,
    type: 'META',
    difficulty: 5,
    time: '18m',
    location: '[ADMIN BUILDING] — Central Archive',
    points: 120,
    prerequisiteNodes: ["P21"],
    nextNodes: ["P22"],
  },
  {
    id: 'M04',
    code: 'M04',
    name: 'The Hidden Layer',
    stage: 4,
    type: 'META',
    difficulty: 5,
    time: '25m',
    location: '[ENGINEERING BLOCK] — Vault Delta Core',
    points: 150,
    prerequisiteNodes: ["P29"],
    nextNodes: ["P30"],
  },
  {
    id: 'P22',
    code: 'P22',
    name: 'The Hidden Layer',
    stage: 4,
    type: 'LOGIC',
    difficulty: 4.5,
    time: '12m',
    location: '[SCIENCE BUILDING] — Research Lab',
    points: 60,
    prerequisiteNodes: ["M03"],
    nextNodes: ["P23"],
  },
  {
    id: 'P23',
    code: 'P23',
    name: 'The Reinterpretation',
    stage: 4,
    type: 'DEDUCTION',
    difficulty: 4.5,
    time: '12m',
    location: '[ENGINEERING BLOCK] — Robotics Bay 1',
    points: 60,
    prerequisiteNodes: ["P22"],
    nextNodes: ["P24"],
  },
  {
    id: 'P24',
    code: 'P24',
    name: 'The Cross-Reference',
    stage: 4,
    type: 'CROSS_REFERENCE',
    difficulty: 4.5,
    time: '11m',
    location: '[ENGINEERING BLOCK] — Communications Antenna Deck',
    points: 60,
    prerequisiteNodes: ["P23"],
    nextNodes: ["P25"],
  },
  {
    id: 'P25',
    code: 'P25',
    name: 'The Overload',
    stage: 4,
    type: 'EXTRACTION',
    difficulty: 4.5,
    time: '10m',
    location: '[ENGINEERING BLOCK] — Server Room Cooling Corridor',
    points: 70,
    prerequisiteNodes: ["P24"],
    nextNodes: ["P26"],
  },
  {
    id: 'P26',
    code: 'P26',
    name: 'The Mirror II',
    stage: 4,
    type: 'THREE_PHONE',
    difficulty: 4.5,
    time: '12m',
    location: '[ENGINEERING BLOCK] — Holographic Prototyping Lab',
    points: 70,
    prerequisiteNodes: ["P25"],
    nextNodes: ["P27"],
  },
  {
    id: 'P27',
    code: 'P27',
    name: 'The Dependency',
    stage: 4,
    type: 'LOGIC',
    difficulty: 4.5,
    time: '11m',
    location: '[ENGINEERING BLOCK] — Computer Systems Architecture Lab',
    points: 70,
    prerequisiteNodes: ["P26"],
    nextNodes: ["P28"],
  },
  {
    id: 'P28',
    code: 'P28',
    name: 'The Fragment',
    stage: 4,
    type: 'EXTRACTION',
    difficulty: 4.5,
    time: '10m',
    location: '[ENGINEERING BLOCK] — Cyber-Physical Research Chamber',
    points: 65,
    prerequisiteNodes: ["P27"],
    nextNodes: ["P29"],
  },
  {
    id: 'P29',
    code: 'P29',
    name: 'The Revelation',
    stage: 4,
    type: 'NARRATIVE_INVESTIGATION',
    difficulty: 4,
    time: '8m',
    location: '[ENGINEERING BLOCK] — Core Declassification Vault',
    points: 60,
    prerequisiteNodes: ["P28"],
    nextNodes: ["M04"],
  },
  {
    id: 'P30',
    code: 'P30',
    name: 'The Transmitter Spire',
    stage: 5,
    type: 'MEMORY',
    difficulty: 4,
    time: '9m',
    location: '[NEXUS CORE] — Transmitter Spire',
    points: 65,
    prerequisiteNodes: ["M04"],
    nextNodes: ["P31"],
  },
  {
    id: 'P31',
    code: 'P31',
    name: 'The Memory Array',
    stage: 5,
    type: 'MEMORY',
    difficulty: 4,
    time: '9m',
    location: '[NEXUS CORE] — Memory Arrays',
    points: 65,
    prerequisiteNodes: ["P30"],
    nextNodes: ["P32"],
  },
  {
    id: 'P32',
    code: 'P32',
    name: 'The Three Phones II',
    stage: 5,
    type: 'THREE_PHONE',
    difficulty: 4,
    time: '9m',
    location: '[NEXUS CORE] — Final Vault',
    points: 65,
    prerequisiteNodes: ["P31"],
    nextNodes: ["P33"],
  },
  {
    id: 'P33',
    code: 'P33',
    name: 'The GM Key Protocol',
    stage: 5,
    type: 'DEDUCTION',
    difficulty: 4.5,
    time: '8m',
    location: '[NEXUS CORE] — GM Key Panel',
    points: 70,
    prerequisiteNodes: ["P32"],
    nextNodes: ["P34"],
  },
  {
    id: 'P34',
    code: 'P34',
    name: 'The Final Sequence',
    stage: 5,
    type: 'PATTERN',
    difficulty: 4.5,
    time: '8m',
    location: '[NEXUS CORE] — Central Hub',
    points: 70,
    prerequisiteNodes: ["P33"],
    nextNodes: ["P35"],
  },
  {
    id: 'P35',
    code: 'P35',
    name: 'The Final Choice',
    stage: 5,
    type: 'NARRATIVE_INVESTIGATION',
    difficulty: 4.5,
    time: '8m',
    location: '[NEXUS CORE] — Final Boss Chamber',
    points: 75,
    prerequisiteNodes: ["P34"],
    nextNodes: ["P36"],
  },
  {
    id: 'P36',
    code: 'P36',
    name: 'The GM Intervention',
    stage: 5,
    type: 'META',
    difficulty: 5,
    time: '7m',
    location: '[NEXUS CORE] — GM Observation Deck',
    points: 80,
    prerequisiteNodes: ["P35"],
    nextNodes: ["P37"],
  },
  {
    id: 'P37',
    code: 'P37',
    name: 'The Final Boss',
    stage: 5,
    type: 'FINAL_BOSS',
    difficulty: 5,
    time: '10m',
    location: '[NEXUS CORE] — Final Boss Arena',
    points: 200,
    prerequisiteNodes: ["P36"],
    nextNodes: null,
  },
]

export const PUZZLES_BY_CODE: Record<string, NodeIndexEntry> = ALL_PUZZLES.reduce(
  (acc, puzzle) => {
    acc[puzzle.code] = puzzle
    return acc
  },
  {} as Record<string, NodeIndexEntry>,
)

export const PUZZLES_BY_STAGE: Record<number, NodeIndexEntry[]> = ALL_PUZZLES.reduce(
  (acc, puzzle) => {
    if (!acc[puzzle.stage]) acc[puzzle.stage] = []
    acc[puzzle.stage].push(puzzle)
    return acc
  },
  {} as Record<number, NodeIndexEntry[]>,
)

export const PUZZLE_COUNT = ALL_PUZZLES.length
