-- ============================================================================
-- NEXUS — Retrieve an issued Logic Code without storing it in the clear
--
-- THE REQUIREMENT
-- The admin PC is the reference screen: players stand next to it, read their
-- own code off it, and type it into their phone. So the same code has to come
-- back every time it is looked at — on the first open, on a second open, after
-- a refresh, and for a player who asks "can you show my code again?" five
-- minutes later. Opening the display must never rotate a credential.
--
-- THE TENSION
-- players.login_code_hash is a salted hash, and the code is also that player's
-- Supabase Auth password. A hash cannot be displayed, and a code that is only
-- ever shown once is exactly the dead end this system already had.
--
-- THE ANSWER
-- players.login_code_cipher holds the code encrypted with AES-GCM, encrypted by
-- the bureau-operations edge function with a key derived from a server-only
-- secret. The database stores ciphertext; only an admin-authenticated call to
-- that function can decrypt, and the plaintext still never reaches the player
-- or any other client. The hash stays authoritative for login, so the security
-- properties of the existing flow are unchanged:
--
--   * a leaked database dump contains no usable code
--   * a leaked table dump cannot be replayed against Supabase Auth
--   * login still requires the hash to match, so a wrong code still fails
--
-- Two moments clear the cipher, both inside the same transaction that already
-- invalidates the code, so the display can never show a code that no longer
-- works:
--   * player_login_flow(), when a player logs in (the code is consumed)
--   * bureau_reset_team(), when the Bureau resets a team
--
-- No Logic Code is regenerated by this migration and no existing credential
-- changes. Teams created before it keep whatever state they were in; their
-- codes simply have no cipher yet, which the admin UI reports honestly as
-- "re-issue to display" instead of inventing a code.
-- ============================================================================

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS login_code_cipher TEXT;

-- Only this version's envelope may ever be stored, so a malformed or
-- hand-inserted value can never be mistaken for something decryptable.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'valid_login_code_cipher'
  ) THEN
    ALTER TABLE players
      ADD CONSTRAINT valid_login_code_cipher
      CHECK (login_code_cipher IS NULL OR login_code_cipher LIKE 'v1.%');
  END IF;
END;
$$;

-- ============================================================================
-- player_login_flow: consume the code and forget its ciphertext together
-- ============================================================================
CREATE OR REPLACE FUNCTION player_login_flow(
  input_code TEXT,
  input_device_fingerprint_hash TEXT,
  input_device_info JSONB
)
RETURNS TABLE (
  player_id UUID,
  team_id UUID,
  role player_role,
  display_name TEXT,
  team_name TEXT,
  team_status team_status,
  auth_user_id UUID,
  auth_user_email TEXT,
  login_result TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  p_id UUID;
  v_device_bound BOOLEAN;
  v_device_match BOOLEAN;
  v_attempts INTEGER;
  v_locked_until TIMESTAMPTZ;
  MAX_LOGIN_ATTEMPTS CONSTANT INTEGER := 5;
  LOCKOUT_DURATION CONSTANT INTERVAL := INTERVAL '15 minutes';
BEGIN
  -- Find and verify player by login code (active code + not locked)
  SELECT id, (device_session_token IS NOT NULL), (device_fingerprint_hash = input_device_fingerprint_hash),
         login_attempts, login_locked_until
  INTO p_id, v_device_bound, v_device_match, v_attempts, v_locked_until
  FROM players
  WHERE verify_login_code(input_code, login_code_hash)
    AND (login_locked_until IS NULL OR login_locked_until < now())
    AND (login_code_expires_at IS NULL OR login_code_expires_at > now())
  LIMIT 1;

  IF p_id IS NULL THEN
    RETURN QUERY SELECT NULL::UUID, NULL::UUID, NULL::player_role, ''::TEXT, ''::TEXT,
      NULL::team_status, NULL::UUID, NULL::TEXT, 'NOT_FOUND'::TEXT;
    RETURN;
  END IF;

  -- Check device binding. A bound device belongs to exactly one player, so a
  -- second player cannot claim a phone that is already someone's identity.
  IF v_device_bound AND NOT v_device_match THEN
    UPDATE players
    SET login_attempts = login_attempts + 1,
        login_locked_until = CASE
          WHEN login_attempts + 1 >= MAX_LOGIN_ATTEMPTS THEN now() + LOCKOUT_DURATION
          ELSE login_locked_until
        END
    WHERE id = p_id;

    RETURN QUERY
    SELECT p.id, p.team_id, p.role, p.display_name,
           t.name, t.status,
           p.auth_user_id, p.auth_user_email, 'DEVICE_MISMATCH'::TEXT
    FROM players p
    JOIN teams t ON t.id = p.team_id
    WHERE p.id = p_id;
    RETURN;
  END IF;

  -- Bind or re-confirm device, and consume the code. login_code_cipher is
  -- cleared in the same statement so the admin display can never show a code
  -- that has just been used.
  UPDATE players
  SET device_session_token = COALESCE(device_session_token, gen_random_uuid()::TEXT),
      device_fingerprint_hash = input_device_fingerprint_hash,
      device_info = input_device_info,
      login_attempts = 0,
      login_locked_until = NULL,
      login_code_hash = NULL,
      login_code_cipher = NULL,
      login_code_expires_at = NULL,
      last_login_at = now(),
      status = 'ACTIVE'
  WHERE id = p_id;

  RETURN QUERY
  SELECT p.id, p.team_id, p.role, p.display_name,
         t.name, t.status,
         p.auth_user_id, p.auth_user_email, 'SUCCESS'::TEXT
  FROM players p
  JOIN teams t ON t.id = p.team_id
  WHERE p.id = p_id;
END;
$$;

-- ============================================================================
-- bureau_reset_team: a reset kills every code, so it kills the ciphertext too
-- ============================================================================
CREATE OR REPLACE FUNCTION bureau_reset_team(p_team_id UUID, p_reason TEXT DEFAULT 'Reset by Bureau')
RETURNS TABLE (success BOOLEAN, team_id UUID)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_current_status TEXT;
BEGIN
  SELECT t.status INTO v_current_status FROM teams t WHERE t.id = p_team_id;

  IF v_current_status IS NULL THEN
    RAISE EXCEPTION 'Team not found';
  END IF;

  -- Clear gameplay state without destroying identity
  UPDATE team_progress AS tp
  SET solved_nodes = '{}'::jsonb,
      current_node_id = NULL,
      available_node_ids = '{}'::uuid[],
      evidence_owned = '{}'::uuid[],
      inventory_owned = '{}'::jsonb,
      fragments_owned = '{}'::uuid[],
      score = 0,
      hints_used = 0,
      hints_available = 3,
      time_elapsed_minutes = 0,
      time_remaining_minutes = 180,
      started_at = NULL,
      last_activity_at = now(),
      metadata = '{}'::jsonb
  WHERE tp.team_id = p_team_id;

  UPDATE teams AS t
  SET status = 'RESET',
      started_at = NULL,
      completed_at = NULL,
      current_node_id = NULL,
      score = 0,
      updated_at = now()
  WHERE t.id = p_team_id;

  -- Clear login codes and device bindings for all players on the team
  UPDATE players AS pl
  SET login_code_hash = NULL,
      login_code_cipher = NULL,
      login_code_expires_at = NULL,
      device_session_token = NULL,
      device_fingerprint_hash = NULL,
      device_info = NULL,
      login_attempts = 0,
      login_locked_until = NULL
  WHERE pl.team_id = p_team_id;

  INSERT INTO audit_log (admin_id, action_type, target_team_id, payload, reason, ip_address)
  VALUES (auth.uid()::text, 'TEAM_UPDATE', p_team_id, jsonb_build_object('action', 'RESET'), p_reason, NULL);

  INSERT INTO game_events (type, team_id, payload)
  VALUES ('TEAM_RESET', p_team_id, jsonb_build_object('reason', p_reason));

  RETURN QUERY SELECT TRUE, p_team_id;
END;
$$;
