/**
 * NEXUS ECHO — Bureau icon registry
 *
 * The name → component map, kept out of BureauIcons.tsx so that file exports
 * only components (React fast refresh requires it).
 */
import {
  BoardGlyph, CaseGlyph, CommsGlyph, EvidenceGlyph, LedgerGlyph, ScanGlyph,
} from '@/components/brand/glyphs'
import {
  AddIcon,
  AlertIcon,
  AlertTriangleIcon,
  BackIcon,
  BellIcon,
  BellOffIcon,
  BoxIcon,
  BrainIcon,
  CameraIcon,
  ChevronLeftIcon,
  CircleIcon,
  ClockIcon,
  CloseIcon,
  CloudOffIcon,
  ConfirmIcon,
  CopyIcon,
  DatabaseIcon,
  DownloadIcon,
  EditIcon,
  EraserIcon,
  ErrorIcon,
  EyeIcon,
  EyeOffIcon,
  FileIcon,
  FilterIcon,
  FlagIcon,
  ForwardIcon,
  HelpIcon,
  ImageIcon,
  InfoIcon,
  KeyIcon,
  KeyboardIcon,
  LayoutDashboardIcon,
  LightbulbIcon,
  LockIcon,
  LogOutIcon,
  MapPinIcon,
  MaximizeIcon,
  MicrophoneIcon,
  MinimizeIcon,
  MonitorIcon,
  PackageIcon,
  PauseIcon,
  PlayIcon,
  QrCodeIcon,
  RadioIcon,
  RefreshIcon,
  RotateCcwIcon,
  RotateIcon,
  SaveIcon,
  ScanLineIcon,
  SearchIcon,
  SendIcon,
  ServerCrashIcon,
  ServerIcon,
  ShareIcon,
  ShieldIcon,
  ShieldQuestionIcon,
  SkipForwardIcon,
  SmartphoneIcon,
  SpinnerIcon,
  SquareIcon,
  SuccessIcon,
  TabletIcon,
  TargetIcon,
  TrashIcon,
  UnlockIcon,
  UserIcon,
  UsersIcon,
  VideoIcon,
  WifiIcon,
  WifiOffIcon,
  WrenchIcon,
} from './BureauIcons'

/* ── Export registry ──────────────────────────────────── */

/* Field glyphs (brand/glyphs.tsx) are the icons of the five investigation
   spaces. Trophy is retired: a ranking is a ledger, not a prize. */
const TrophyIcon = LedgerGlyph

export const BureauIcons = {
  Case: CaseGlyph,
  Evidence: EvidenceGlyph,
  Board: BoardGlyph,
  Scan: ScanGlyph,
  Comms: CommsGlyph,
  Ledger: LedgerGlyph,
  Back: BackIcon,
  Forward: ForwardIcon,
  ChevronLeft: ChevronLeftIcon,
  Close: CloseIcon,
  Confirm: ConfirmIcon,
  Check: ConfirmIcon,
  Add: AddIcon,
  Send: SendIcon,
  Copy: CopyIcon,
  Download: DownloadIcon,
  Edit: EditIcon,
  Save: SaveIcon,
  Refresh: RefreshIcon,
  Share: ShareIcon,
  Eraser: EraserIcon,
  Alert: AlertIcon,
  AlertTriangle: AlertTriangleIcon,
  Spinner: SpinnerIcon,
  Success: SuccessIcon,
  Error: ErrorIcon,
  Circle: CircleIcon,
  Lock: LockIcon,
  Unlock: UnlockIcon,
  Shield: ShieldIcon,
  ShieldQuestion: ShieldQuestionIcon,
  Eye: EyeIcon,
  EyeOff: EyeOffIcon,
  Users: UsersIcon,
  User: UserIcon,
  Trophy: TrophyIcon,
  Flag: FlagIcon,
  Target: TargetIcon,
  LogOut: LogOutIcon,
  MapPin: MapPinIcon,
  Search: SearchIcon,
  Filter: FilterIcon,
  Info: InfoIcon,
  Help: HelpIcon,
  File: FileIcon,
  Image: ImageIcon,
  Video: VideoIcon,
  Database: DatabaseIcon,
  Box: BoxIcon,
  Package: PackageIcon,
  Key: KeyIcon,
  Bell: BellIcon,
  BellOff: BellOffIcon,
  Keyboard: KeyboardIcon,
  QrCode: QrCodeIcon,
  Camera: CameraIcon,
  ScanLine: ScanLineIcon,
  Play: PlayIcon,
  Pause: PauseIcon,
  Square: SquareIcon,
  Rotate: RotateIcon,
  Radio: RadioIcon,
  LayoutDashboard: LayoutDashboardIcon,
  Maximize: MaximizeIcon,
  Minimize: MinimizeIcon,
  Wifi: WifiIcon,
  WifiOff: WifiOffIcon,
  CloudOff: CloudOffIcon,
  Server: ServerIcon,
  ServerCrash: ServerCrashIcon,
  Clock: ClockIcon,
  Brain: BrainIcon,
  Lightbulb: LightbulbIcon,
  RotateCcw: RotateCcwIcon,
  RotateCcwIcon: RotateCcwIcon,
  SkipForward: SkipForwardIcon,
  Smartphone: SmartphoneIcon,
  Tablet: TabletIcon,
  Monitor: MonitorIcon,
  Wrench: WrenchIcon,
  Microphone: MicrophoneIcon,
  Trash: TrashIcon,
}
